- README.md
This links the header image back to pixie website.
> Make header image clickable

- README.md
- badge added
we have two similar looking badges next to each other but punchout to diff url. more the merrier.
> Add Awesome-Go Badge

- README.md
- fixed broken links reported in https://github.com/pixie-labs/pixie/issues/68
> Fix Broken Links in Readme

- .github/ISSUE_TEMPLATE/Live_view_request.md
- pxl_scripts/README.md
- Repurposed the issue template to request new live views. 
- Updated readme to add links
> Issue template for community scripts

- pxl_scripts/px/tracepoint_status/manifest.yaml
- pxl_scripts/px/tracepoint_status/tracepoint_status.pxl
- pxl_scripts/px/tracepoint_status/vis.json
Adding tracepoint status script to monitor your running tracepoints.
> Add tracepoint status script

- pxl_scripts/px/connections_by_ip/vis.json
To remove unnecessary dev code.
> Cleanup connections_by_ip script

- pxl_scripts/px/pod/pod.pxl
- pxl_scripts/px/pod/vis.json
Addressing https://github.com/pixie-labs/pixie/issues/115
> Modifications to Pod Live View to remove fanout to all agents #115

- pxl_scripts/px/net_flow_graph/manifest.yaml
- pxl_scripts/px/net_flow_graph/vis.json
- add variable to support grouping connections by pod, namespace
- tweak widget position to make the table full width
> Update Network Flow Graph Script

- pxl_scripts/px/tcp_retransmits/data.pxl
- pxl_scripts/px/tcp_retransmits/manifest.yaml
- pxl_scripts/px/tcp_retransmits/vis.json
BPFTrace based scripts that monitor for TCP retransmissions
> TCP retransmission scripts

- pxl_scripts/px/pod/pod.pxl
> Add container to px/pod resource_timeseries output table

- pxl_scripts/px/namespace/namespace.pxl
Needed this while we were debugging, might as well add it in.
> Adding memory to px/namespace stats

- pxl_scripts/px/most_http_data/data.pxl
This fixes https://github.com/pixie-labs/pixie/issues/143.
> Remove hardcoded value from most_http_data pxl script

- pxl_scripts/px/pod/pod.pxl
- pxl_scripts/px/pod/vis.json
> [px/pod] add widget to display node the pod runs on

- demos/simple-gotracing/http_trace/http_trace.go
- demos/simple-gotracing/http_trace_kprobe/.gitignore
- demos/simple-gotracing/http_trace_kprobe/Makefile
- demos/simple-gotracing/http_trace_kprobe/bpf_program.go
- demos/simple-gotracing/http_trace_kprobe/http_trace_kprobe.go
This is the experimental HTTP tracer demo. It's for demonstration purposes only and not suitable for stable/production use.
> Kprobe based HTTP request tracer demo

- pxl_scripts/px/dns_data/data.pxl
- pxl_scripts/px/dns_data/manifest.yaml
Similar to http_data, but for DNS requests.
> DNS data script

- pxl_scripts/px/tcp_drops/data.pxl
- pxl_scripts/px/tcp_retransmits/data.pxl
Reminder to update docs PR #181 once this lands.
> Remove unnecessary code from bpftrace programs

- pxl_scripts/px/dns_flow_graph/dns_flow_graph.pxl
- pxl_scripts/px/dns_flow_graph/vis.json
Add filters to DNS flow graph script.
> DNS flow graph: filters

- pxl_scripts/px/dns_query_summary/dns_query_summary.pxl
- pxl_scripts/px/dns_query_summary/manifest.yaml
- pxl_scripts/px/dns_query_summary/vis.json
Clusters queries originating from pods and displays summary stats about successful resolutions.
> DNS query overview graph

- pxl_scripts/px/cql_data/data.pxl
- pxl_scripts/px/cql_data/vis.json
- pxl_scripts/px/http_data/data.pxl
- pxl_scripts/px/http_data/manifest.yaml
- pxl_scripts/px/http_data/vis.json
- pxl_scripts/px/mysql_data/data.pxl
- pxl_scripts/px/mysql_data/manifest.yaml
- pxl_scripts/px/mysql_data/vis.json
- pxl_scripts/px/postgres_data/data.pxl
- pxl_scripts/px/postgres_data/manifest.yaml
- pxl_scripts/px/postgres_data/vis.json
Modernize to use vis.json, enabling future parameterization.
> Modernize protocol data capture scripts, and add postgres

- README.md
https://github.com/pixie-labs/pixie-docs/issues/199
> Update README.md to link to Pixie's requirements

- pxl_scripts/px/redis_data/manifest.yaml
- pxl_scripts/px/redis_data/trace.pxl
- pxl_scripts/px/redis_data/vis.json
.beta is an indicator of a beta feature.
> Add redis_data script for querying redis_events.beta table

- pxl_scripts/README.md
- pxl_scripts/px/redis_flow_graph/manifest.yaml
- pxl_scripts/px/redis_flow_graph/redis_flow_graph.pxl
- pxl_scripts/px/redis_flow_graph/vis.json
Graph of Redis messages in the cluster with latency and throughput stats.
> Add px/redis_flow_graph script.

- .github/PULL_REQUEST_TEMPLATE.md
This clarifies that any change that requires modification to external documentation must be tracked.
N/A
/kind cleanup
N/A
> Fix confusing message in PR template

- k8s/devinfra/jenkins-oss/values.yaml
Allowing the "ok to test" phrase approves the PR for testing without any further code review. Instead we should use "test this please" each time we want the build triggered.
N/A
/kind cleanup
Verify that test phrase does not trigger Jenkins.
> Edit github PR admins and don't allow repeated builds on jenkins

- .github/PULL_REQUEST_TEMPLATE.md
Summary: This makes the PR description more compact and easier to incorporate into the final commit message.
Test Plan: N/A
> Make PR styles more compact

- ADOPTERS.md
> Add WSO2 to adopters list

- k8s/cloud/base/ory_auth/kratos/kratos_deployment.yaml
/kind bug
`admin-create-if-not-exists` container on `kratos` deployment fails to get the health check and create the default credentials since curl is not trusting the self signed certificate. This PR make sure curl trust the self signed certificate so the admin creation process works as expected in self hosted pixie cloud setups.
N/A
```release-note
NONE
```
```docs
```
> Fix SSL verify issue in admin-create-if-not-exist

- Jenkinsfile
Summary: pxapi copybara is handled by github actions now.
Test Plan: N/A just cleanup.
> Remove pxapi.go copybara from Jenkinsfile.

- Jenkinsfile
Summary: We no longer use or trigger builds from Phabricator so remove all
of the tooling to support Phabricator from the Jenkinsfile
Test Plan: The updated Jenkinsfile should continue to be syntatcitcally valid
and work for our remaining jobs
> Remove phabricator related code from Jenkinsfile

- ci/pr_description_linter.sh
Summary: PR description linter should ignore code blocks and details, when running its checks.
This allows for example for me to put the following details block that has lines that begin with whitespace.
<details>
```
Starts with whitespace.
ends with whitespace
```
</details>
Test Plan: Testing with this PR, also tested locally with a variety of combinations of details, code blocks.
> Fix PR description linter to ignore code blocks and details.

- src/ui/yarn.lock
Summary: Addresses CVE-2022-25881
Test Plan: UI build and tests still work.
> Upgrade some UI deps to address CVEs

- bazel/cc_resource.bzl
Summary: Removes an unnecessary genrule.
In order to remove the genrule, I had to fix the path sanitization in the cc_resource_objcopy_impl.
Test Plan: Ran `bazel build //src/stirling/...` which is the only consumer of cc_resource.
> Remove unnecessary genrule

- bazel/test_runners/qemu_with_kernel/create_sysroot_disk.sh
Summary: This creates a ext4 disk image that can be used by qemu. It extracts the sysroot and install additional files into the image.
Test Plan: `./create_sysroot_disk.sh -s sysroot-amd64-test.tar.gz -o test.img -e `which bash`:/bin/mybash
> Script to create disk image from sysroot

- bazel/test_runners/qemu_with_kernel/create_sysroot_disk.sh
Summary: This makes the images smaller and makes it easier to create overlays per test.
Test Plan: verify that qcow2 image is generated.
> Use qcow2 images for qemu

- bazel/test_runners/qemu_with_kernel/create_sysroot_disk.sh
Summary: This adds kernel model extraction from our kernel packages to the disk image.
Test Plan: Verify that the kernel models exists in the disk image.
> Add kernel module extraction to qemu disk image

- src/pxl_scripts/watch.sh
Summary: The names of these configs changed a while ago; I forgot to update the instructions to match.
Test Plan: N/A
> Update `watch.sh` instructions

- src/stirling/obj_tools/elf_reader.cc
Summary: Adds support for finding ret instructions for aarch64.
Also, uses the ELF file's machine type to determine the disassembly context triple (and which ret instructions to look for), instead of basing it off of which architecture ELFReader was built for.
Test Plan: Manually checked that it can properly find the ret instruction for the prebuilt_test_exe. Need to update the elf_reader_test to actually test based on an aarch64 ELF file instead of just the x86_64 prebuilt_test_exe.
> Support finding RET instructions on ARM

- src/stirling/bpf_tools/task_struct_resolver.cc
Summary: When using our pre-packaged linux headers on ARM, the `task_struct_resolver` was failing because it found the `group_leader` value twice in the `task_struct`.
The extra occurence of the address of the task struct (which is what we use to search for the `group_leader` offset), is found inside the `cpu_context` inside the `thread_struct`. On ARM, linux will store the address of the task struct in register `x20` when it creates a thread. This will then get stored in the 2nd field of `cpu_context` inside of `thread_struct`, leading to our task struct resolver thinking it found `group_leader` twice. To avoid this issue, this PR attempts to ignore the `thread_struct` entirely when resolving `task_struct` offsets. The issue then becomes identifying the offset of the `thread_struct` …
> Ignore thread_struct when resolving task_struct offsets on ARM

- src/e2e_test/perf_tool/cmd/run.go
Summary: Create `pixie.Context` in `run` subcommand of `perf_tool`.
Test Plan: Tested that downstream users of the `pixie.Context` work.
> [perf_tool/run_cmd] Create Pixie context

- src/e2e_test/perf_tool/pkg/run/run.go
Summary: The previous PR prepared workloads. This PR adds logic to actually deploy them.
Test Plan: Tested the runner implementation as a whole.
> [perf_tool/runner] Deploy workloads

- src/e2e_test/perf_tool/cmd/run.go
Summary: Add `gke.ClusterProvider` to `run` subcommand.
Test Plan: Tested that the `run` command works with a `gke` cluster.
> [perf_tool/run_cmd] GKE Cluster Provider

- src/e2e_test/perf_tool/pkg/run/BUILD.bazel
- src/e2e_test/perf_tool/pkg/run/run.go
Summary: Add metric recording to runner.
Test Plan: Tested the `Runner` implementation as a whole.
> [perf_tool/runner] Add metric recorders

- src/e2e_test/perf_tool/cmd/run.go
Summary: TSIA
Test Plan: Tested the `run` subcommand as a whole.
> [perf_tool/run_cmd] Specify container registry to use for skaffold

- src/e2e_test/perf_tool/pkg/run/run.go
Summary: The `defer *.Close` statements don't happen in the correct order, so this explicitly calls the `Close`s in the order they should be torn down.
Test Plan: Tested the `Runner` implementation as a whole
> [perf_tool/runner] Teardown in correct order

- src/e2e_test/perf_tool/pkg/run/run.go
Summary: Get the order of the commit within the repo's commit history and attach it to the SpecRow thats sent to bigquery. This is used in datastudio to order commits in terms of the order they show up in the commit history, because commit time is the time the commit was created and not necessarily the time it was merged.
Test Plan: Tested that the commit topo order shows up in bigquery.
> [perf_tool/runner] Get commit topological order

- bazel/test_runners/qemu_with_kernel/init
Summary: Sets up networking, hostname and other missing files.
Test Plan: tested on qemu
> Update qemu init script properly setup test machine

- src/e2e_test/perf_tool/cmd/run.go
Summary: TSIA
Test Plan: Tested that `--num_runs` works.
> [perf_tool/run_cmd] Allow repeating experiments multiple times in parallel

- src/e2e_test/perf_tool/pkg/suites/suites.go
Summary: This adds two experiment suites, `main` and `http-grid`. For now `http-grid` will be run only on an ad-hoc basis. We haven't decided yet whether to run perf on every commit to main or just once a day, so I might rename that to `nightly`.
Test Plan: Tested that all experiments in both suites run successfully.
> [perf_tool/suites] Add `main` and `http-grid` experiment suites

- SECURITY.md
Summary: TSIA
Test Plan: Checked the rendered markdown.
> Update security policy to include explicit timelines

- src/ui/src/components/command-palette/providers/script/script-suggestions.tsx
Summary: Partial bugfix. In certain conditions, the Command Palette fails to sort suggested script names or argument values correctly.
This fixes some of those; there's still an issue where `validValues` suggestions are never presented to the user which will be fixed by another change.
Test Plan: Verify that suggested script names for the input `script:` account for the namespace correctly now.
> Command Palette tweak script name suggestions

- .github/workflows/perf_common.yaml
Summary: TSIA
Test Plan: Checked that the label matches the label in github's runners ui.
> [perf eval] Fix runs-on typo

- .github/workflows/codeql.yaml
Summary: Uses the CodeQL action to run CodeQL.
Test Plan: CodeQL should run on this PR.
> Add a CodeQL workflow

- .github/workflows/get_image.yaml
Summary: TSIA, minor cleanup.
Test Plan: Check the github actions UI after this change.
> Name the get_image workflow

- src/ui/src/components/command-palette/command-palette-affixes.tsx
- src/ui/src/components/command-palette/command-palette-trigger.tsx
- src/ui/src/components/command-palette/command-text-field.tsx
- src/ui/src/components/command-palette/providers/script/script-provider-common.tsx
- src/ui/src/components/icons/pixie-command.tsx
Summary: While profiling a different improvement to the Command Palette, I found a few obvious spots to improve performance a little bit. These changes don't affect much as of this moment, but the change I extracted them from does need them.
Test Plan: Smoke test. Only change should be a marginally more responsive Command Palette while typing.
> Command Palette minor performance improvements

- src/ui/src/configurables/base/create-org-extras.tsx
Summary: Oops.
Test Plan: Should build properly now.
> Fix incorrectly named export

- tools/docker/etcd_image/Dockerfile
Summary: TSIA
Test Plan: `docker buildx build` still succeeds
> [code scanning] Pin digest for alpine:3.17

- tools/linters/pr_description_linter.sh
Summary: TSIA
Test Plan: Tested with this PR, made sure all errors showed up in the log.
> [pr_description_linter] Print all issues not just the first one

- bazel/external/simdutf.BUILD
- bazel/repository_locations.bzl
Summary: The latest version of simdutf has various security and performance improvements.
Relevant Issues: Fixes the following vulnerabilities.
https://osv.dev/vulnerability/OSV-2023-281
https://osv.dev/vulnerability/OSV-2023-278
https://osv.dev/vulnerability/OSV-2023-272
Test Plan: N/A
> [third_party] Bump simdutf version

- src/carnot/funcs/builtins/math_sketches.cc
- src/carnot/funcs/builtins/math_sketches.h
- src/carnot/funcs/builtins/math_sketches_test.cc
Summary: Adds `Serialize` and `Deserialize` methods to the quantiles UDA, so that it can be used in a partial aggregate.
Test Plan: Added a test, also skaffold'd and made sure the quantiles still look reasonable.
> [carnot] Add ser/de to quantiles UDA.

- src/common/testing/test_utils/container_runner.h
- src/stirling/source_connectors/socket_tracer/http2_trace_bpf_test.cc
Summary: TSIA
Test Plan: This diff only touches comments.
> Fix comments in `container_runner.h`.

- src/stirling/source_connectors/socket_tracer/uprobe_manager.cc
Summary: TSIA
Test Plan: Existing tests.
> Improve comment and variable name in `uprobe_manager.cc`.

- src/stirling/core/unit_connector.h
Summary: In the previous impl. of `UnitConnector`, we used the "run window" concept borrowed from the main loop in Stirling proper. Since the unit connector handles only one data source at a time, the run window is not needed. In this patch, we remove the run window which simplifies and cleans the code.
In addition, we tidy a few other features. We rename `RefreshContextAndDeployUProbes` as `BlockAndDeployUProbes` to better match what happens (i.e. because context refresh is not needed when using the "everything local" context). Also, we add `SetClusterCIDR` to support future usage in the socket tracer test suite.
Test Plan: Tested locally with the next diffs that add to perf profiler tests and convert the stirling profiler binary. The underlying patch was …
> Simplify `UnitConnector` by removing the "run window" concept.

- k8s/cloud_deps/prod/elastic/elastic_storage_patch.yaml
Summary: We are above 90% again so bump it a bit.
Test Plan: Applied to cluster
> Increase elastic storage

- README.md
Summary: Added our community calendar here
Test Plan: N/A
> Update README.md to add community calendar

- .github/workflows/cloud_release.yaml
- ci/cloud_build_release.sh
Summary: TSIA
Test Plan: N/A removing stale code.
> [releases] Remove staging/prod deploys from cloud_build_release

- src/ui/src/components/auth/auth-box.tsx
- src/ui/src/pages/auth/auth0-oauth-provider.ts
- src/ui/src/pages/auth/oidc-oauth-provider.ts
- src/ui/src/pages/auth/signup.tsx
Summary: TSIA.
Test Plan: View signup page (through any means). Event should now be tracked when permitted to do so.
> Fix analytics for sign up page view

- ci/github/matrix.sh
Summary: The script does the correct thing but the logs were switched.
This fixes the logging.
Test Plan: Check script output.
> Fix gen matrix logs

- k8s/cloud_deps/prod/elastic/elastic_storage_patch.yaml
- k8s/cloud_deps/prod/nats/storage_patch.yaml
Summary: These use fewer resources than expected mainly due to certain
fixes that were made.
Test Plan: Deploy the new resources.
> Reduce NATS and Elastic PVC sizes based on usage

- src/vizier/services/cloud_connector/cloud_connector_server.go
Summary: TSIA
Test Plan: Deploy a dev vizier
> Reduce metrics scrape period

- README.md
> [bot][releases] Update readme with link to latest cli release.

- README.md
> [bot][releases] Update readme with link to latest vizier release.

- README.md
> [bot][releases] Update readme with link to latest cloud release.

- .github/workflows/trivy_images.yaml
> [actions] Remove temporary pull_request from trivy action

- .github/workflows/trivy_images.yaml
Summary: Fix sarif upload by using the correct ref.
Test Plan: Have to test after it lands in main because of pull_request_target.
> [trivy] Fix sarif upload

- bazel/external/ubuntu_packages/requirements.bazel.txt
- bazel/external/ubuntu_packages/requirements.txt
Summary: Upgrades requests python package to address [code scanning alert](https://github.com/pixie-io/pixie/security/code-scanning/167)
Test Plan: Tested that the ubuntu_packages tool still works.
> [ubuntu_packages tool] Upgrade requests python package

- src/ui/src/components/footer/footer.tsx
- src/ui/src/configurables/base/tos-privacy.tsx
Summary: The current links are outdated, and should instead point to the Linux Foundation's ToS and privacy policy.
Test Plan: Deploy testing cloud and check footer.
> Update ToS & Privacy Policy in UI

- src/carnot/exec/agg_node.cc
- src/carnot/exec/agg_node.h
- src/carnot/exec/agg_node_test.cc
Summary: Implements support for executing partial aggregates in the AggNode. The planner still has partial aggs disabled. A separate PR will flip the switch on the planner side.
Relevant Issues: #1440
Test Plan: Added tests in `agg_node_test` that exercise the partial aggregate code path. Also, tested on a cluster with partial aggregates enabled on the planner side.
> [carnot] Implement partial aggregates in AggNode

- src/ui/BUILD.bazel
Summary: Reverts pixie-io/pixie#1457
Test Plan: Check builds
> Revert "Bring back remote exec for UI builds"

- src/ui/src/containers/admin/cluster-details-test.ts
- src/ui/src/containers/admin/cluster-details.tsx
- src/ui/src/pages/live/live.tsx
Summary: Removes most of the lint suppression in this file, then fixes what is revealed.
This is so I can more easily split this file into three pages in another PR.
Test Plan: Smoke test.
> Lint cluster-details.tsx

- README.md
> [bot][releases] Update readme with link to latest operator release.

- src/cloud/artifact_tracker/controllers/server.go
- src/cloud/artifact_tracker/controllers/server_test.go
Summary: Support getting the download link directly from the manifest, using the new updates to the manifest proto definition. The old hard-coded method is still the fallback in case the artifact in the manifest doesn't set `AvailableArtifactMirrors`.
Test Plan: Added a test, also tested with a skaffolded deploy pointing to my forks manifest github page.
> [artifact tracker] Support GetDownloadLink from AvailableArtifactMirrors

- src/shared/artifacts/manifest/storage.go
Summary: Adds a `manifest.Location` based on an HTTP url. This will allow the `manifest.Poller` to poll for a manifest at an arbitrary HTTP endpoint (eg. github pages) instead of just GCS.
Test Plan: Tested along with some other changes by skaffolding cloud, saw that it could successfully poll a manifest from github pages.
> [manifests] Add HTTP based manifest.Location

- ci/update_artifact_manifest.sh
- src/utils/artifacts/manifest_updater/main.go
Summary: Previously, the manifest_updater could only update GCS manifests. This PR adds support for merging updates into a local manifest. This will be used in a future PR to merge updates into the gh-pages hosted manifest.
Test Plan: Tested along with another change by making an RC on my fork, saw that the manifest in gh-pages was updated with the new version from the RC.
> [manifest_updater] Allow updating local manifests.

- bazel/container_images.bzl
Summary: Just cleaning up unused images.
Test Plan: All existing builds and tests work
> Remove unused images from container_images.bzl

- src/ui/src/containers/admin/cluster-details/cluster-details-test.tsx
- src/ui/src/containers/admin/cluster-details/cluster-details.tsx
Summary: To prevent a bug from ever returning.
Test Plan: `yarn test`
> Unit test for cluster-details breadcrumbs

- .github/actions/bazelrc/action.yaml
- .github/workflows/build_and_test.yaml
- .github/workflows/cli_release.yaml
- .github/workflows/cloud_release.yaml
- .github/workflows/operator_release.yaml
- .github/workflows/perf_common.yaml
- .github/workflows/release_update_docs_px_dev.yaml
- .github/workflows/trivy_images.yaml
- .github/workflows/vizier_release.yaml
- ci/bes-gce.bazelrc
- ci/bes-k8s.bazelrc
- ci/bes-oss-gce.bazelrc
- ci/bes-oss-k8s.bazelrc
- ci/bes.bazelrc
- ci/github/bazelrc
Summary: This removes unused configs and refactors common options to make the configs easier to grok.
Test Plan: All the existing actions should continue to function as before.
> Simplify BES config for CI

- scripts/create_gke_cluster.sh
Summary: These config modes are no longer used.
Test Plan: N/A This is unused code.
> Cleanup unused configs in create cluster script

- k8s/cloud/prod/cloud_ingress_managed_cert.yaml
- k8s/cloud/staging/cloud_ingress_managed_cert.yaml
- k8s/cloud/testing/cloud_ingress_managed_cert.yaml
- src/cloud/proxy/nginx.conf
Summary: These configs are unused and can be removed.
Test Plan: These are unused.
> Remove unused cloud configs

- k8s/vizier/base/kelvin_deployment.yaml
- k8s/vizier/base/patch_sentry.yaml
- k8s/vizier/base/query_broker_deployment.yaml
- k8s/vizier/pem/base/pem_daemonset.yaml
- k8s/vizier/sanitizer/kelvin_deployment.yaml
Summary: Fixed inline bash command for initContainer.
Relevant Issues: https://github.com/pixie-io/pixie/issues/1596
Test Plan: None
> Fix inline bash command

- src/vizier/services/metadata/controllers/k8smeta/k8s_metadata_controller.go
- src/vizier/services/metadata/controllers/k8smeta/k8s_metadata_utils.go
Summary: This pulls out the cleanup work from #1595 to make that PR
smaller and more contained. Should be a no-op just some code refactoring.
Test Plan: Existing tests pass
> [chore] Cleanup metadata watcher

- demos/README.md
> Fix typo in demo update instructions for k8ssandra

- bazel/repository_locations.bzl
Summary: The latest version of simdutf has various security and performance improvements.
Relevant Issues: Fixes the following vulnerabilities.
https://github.com/simdutf/simdutf/pull/340
Test Plan: N/A
> Update simdutf version

- README.md
Summary: Adds an acknowledgements section to the readme.
Test Plan: N/A
> Add acknowledgements to readme

- CONTRIBUTING.md
Summary: This adds more detail about our release process and cadence. This is useful information for users and contributors to know.
Type of change: /kind docs
Test Plan: N/A, this is a doc.
> Document releases

- OWNERS
Summary: This file was out of date with our maintainers file. This updates it to make it more accurate.
Type of change: /kind docs
Test Plan: N/A, this is a doc.
> Update OWNERS to match maintainers

- .github/workflows/mirror_demos.yaml
- .github/workflows/mirror_deps.yaml
- scripts/regclient/deps.lua
- scripts/regclient/regbot_demos.yaml
Summary: Add GitHub action for mirroring demo container images
Relevant Issues: Precursor to fixing px-sock-shop (#1905)
Test Plan: Used regbot dry run to verify the following conditions
<details><summary> command output </summary>
```
$ regbot once --dry-run --config regbot_demos.yaml
INFO[2024-05-23T18:18:16Z] Copy image                                    digestTags=false dry-run=true forceRecursive=false includeExternal=false script="sync demo images" source="docker.io/kbudde/rabbitmq-exporter@sha256:12f27d6d84e6dbdd72c6bc2605e48af9910517394483c1dfa3230e49d3e32107" target="docker.io/pxio/px-sock-shop-kbudde-rabbitmq-exporter:latest@sha256:12f27d6d84e6dbdd72c6bc2605e48af9910517394483c1dfa3230e49d3e32107"
INFO[2024-05-23T18:18:16Z] Copy image …
```
> Add GitHub action for mirroring demo container images

- bazel/test_runners/qemu_with_kernel/create_sysroot_disk.sh
Summary: ![image](https://github.com/user-attachments/assets/c37bb96b-d9db-49dc-a5c7-40c6d4213a34)
Modify the parameters to keep them consistent.
Type of change: /kind chore
Test Plan: N/A
> Fix create_sysroot_disk.sh
