- demos/simple-gotracing/Readme.md
- demos/simple-gotracing/k8s_manifest.yaml
This fixes an issue where the LB may not be available. Also, updates the curl commands to work on localhost.
> Update instructions for go tracing demo

- pxl_scripts/px/pod/pod.pxl
- pxl_scripts/px/pod/vis.json
We want to be able to show the proportional contribution of each container on a pod's resource usage and request throughput.  This change adds that support to do so in the pod Live View.
> Break down resource usage and request throughput in pod Live View by container name.

- pxl_scripts/px/connections_by_ip/connections_by_ip.pxl
- pxl_scripts/px/connections_by_ip/manifest.yaml
- pxl_scripts/px/connections_by_ip/vis.json
Connections by IP helps you find the Kubernetes pods that talk to external IPs and displays them as a graph.
Helpful for finding database clients, users of an external API, etc.
> Add connections by IP

- pxl_scripts/px/node/vis.json
Made the mistake of not updating a referenced function in a vis spec after changing it in the pxl definition. This fixes that mistake.
> Fix px/node vis.json which referenced an old function

- pxl_scripts/px/net_flow_graph/net_flow_graph.pxl
- pxl_scripts/px/net_flow_graph/vis.json
After the list support in the compiler lands, we can pass IPs as a list.
> Net flow IPs as a list

- pxl_scripts/px/tcp_retransmits/vis.json
To avoid overcrowding in the visualization.
> TCP retransmission graph: Increase edge length

- pxl_scripts/px/net_flow_graph/vis.json
We should not color based on the number of bytes. More bytes != errors.
> Remove color from edges of netflow graph

- .pxl.flake8rc
Distributed bpftrace deployment requires that the `printf` statement be on one line. The current max-line-length limits us from landing https://github.com/pixie-labs/pixie/pull/135. Our internal dev repo uses 120.
> Increase max-line-length in .pxl.flake8rc rules

- pxl_scripts/px/tcp_retransmits/data.pxl
After https://phab.corp.pixielabs.ai/D6327, we can now specify column names in printf() statement in the format string:
<column_name>:<format_string> ...
There cannot be any whitespaces in column_names.
> Add column names to the printf() statement

- pxl_scripts/px/net_flow_graph/vis.json
- pxl_scripts/px/node/vis.json
New UI changes allow users to restrict the set of valid values for vis spec variables. This updates the two scripts that need this restriction to reduce user error.
> Add valid values to px/node and px/net_flow_graph

- pxl_scripts/px/tcp_drops/vis.json
tcp_drops was modified from tcp_retransmits, and the edge weight/color/hover column wasn't updated to use the drops column.
> Update px/tcp_drops edgeWeight/Color/Hover column

- pxl_scripts/px/service/service.pxl
- pxl_scripts/px/service/vis.json
- pxl_scripts/px/services/services.pxl
These filters hide results. We had them originally because we had erroneous latencies picked up by the collector. Those bugs were fixed so the hacks are unnecessary and hide real high latency scenarios.
> Remove latency filters in scripts

- .gitignore
- pxl_scripts/px/cluster/cluster.pxl
- pxl_scripts/px/cql_stats/cql_stats.pxl
- pxl_scripts/px/mysql_stats/mysql_stats.pxl
- pxl_scripts/px/namespace/namespace.pxl
- pxl_scripts/px/pod/pod.pxl
- pxl_scripts/px/pods/pods.pxl
- pxl_scripts/px/psql_stats/pgsql_stats.pxl
- pxl_scripts/px/service/service.pxl
- pxl_scripts/px/service_edge_stats/service_edge_stats.pxl
- pxl_scripts/px/service_stats/service_stats.pxl
Noticed upon closer inspection that #155 actually only removed a single latency filter but left many around. This diff does what that diff promised. Should entirely be removing the latency filter line.
> Actually remove latency filters

- pxl_scripts/README.md
- pxl_scripts/px/redis_data/manifest.yaml
- pxl_scripts/px/redis_data/trace.pxl
- pxl_scripts/px/redis_data/vis.json
Note removing org name makes this public.
The redis_table.beta naming change was released already, so this diff is now safe to merge.
> Revise redis data script so it's visible to public

- pxl_scripts/README.md
- pxl_scripts/px/dns_query_summary/vis.json
- pxl_scripts/px/jvm_stats/vis.json
- pxl_scripts/px/namespace/vis.json
- pxl_scripts/px/net_flow_graph/vis.json
- pxl_scripts/px/node/vis.json
- pxl_scripts/px/pod/vis.json
- pxl_scripts/px/pods/vis.json
- pxl_scripts/px/redis_flow_graph/vis.json
- pxl_scripts/px/service/vis.json
- pxl_scripts/px/services/vis.json
- pxl_scripts/px/slow_http_requests/vis.json
- pxl_scripts/sotw/dns_queries_filtered/vis.json
This PR should cause no visible changes. Instead, it is preparation for @NickLanam's planned UI changes that will alert users to the fact that some scripts have required arguments without which no Live View data will appear:
- Required args will be denoted with an asterisk next to the argument name.
- An error message when the user tries to run a script missing required argument values.
**Vis Spec Arguments:**
- To make a Vis Spec's argument **required**, omit the `defaultValue` field. To run the script, a value must be provided in the Live UI / CLI / API. 
- To make a Vis Spec's argument **optional**, provide a `defaultValue` field containing a string or empty string. An empty string means it's not pre-filled argument, but it's optional anyway.
> Update PxL script Vis Specs to use required arguments.

- pxl_scripts/Makefile
- pxl_scripts/pxbeta/service_endpoint/manifest.yaml
- pxl_scripts/pxbeta/service_endpoint/service_endpoint.pxl
- pxl_scripts/pxbeta/service_endpoint/vis.json
- pxl_scripts/pxbeta/service_endpoints/manifest.yaml
- pxl_scripts/pxbeta/service_endpoints/service_endpoints.pxl
- pxl_scripts/pxbeta/service_endpoints/vis.json
Adds a directory for beta scripts called `pxbeta`.
Adds a beta script to list all the endpoints and their stats for a particular service:
Adds a beta script to show stats for a specific endpoint:
Note that this can't be merged until D7559 is released.
> Adding endpoint clustering based beta scripts.

- pxl_scripts/px/pod/pod.pxl
- pxl_scripts/px/pod/vis.json
This adds a flamegraph widget at the bottom of the pod view.
> Add flamegraph widget to pod view

- pxl_scripts/px/node/vis.json
- pxl_scripts/px/perf_flamegraph/vis.json
- pxl_scripts/px/pod/vis.json
The correct capitalization in our protos is specified as StackTraceFlameGraph, so the visspecs should refer to it accordingly.
> Fix capitalization of StackTraceFlameGraph

- .github/workflows/filename_linter.yaml
Description:
Adds a github action workflow to lint filenames, including blocking any private code from accidentally being committed to the repo, and blocking filenames with hyphens.
Relevant Issues:
Type of change:
/kind cleanup
Test Plan:
Tested the github action in a test repo: JamesMBartlett/test_repo.
> [github actions] Add github action to lint filenames.

- .github/workflows/filename_linter.yaml
Summary: Removes hyphen check from the filename linter. We can add it back in later, but it currently fails on any changes to source files, so removing it for now.
Test Plan: Tested that the hyphen check currently fails on source files.
> [actions] Remove broken hyphen check.

- k8s/devinfra/jenkins-oss/values.yaml
Summary: This ensures that changes from `pixie-io` members will trigger jenkins
builds without requiring admin approval.
Test Plan: Ensure that changes from `pixie-io` member now trigger builds but
non admin `pixie-io` members cannot approve builds for other users.
> Add pixie-io to org based allowlist for test triggers

- .github/workflows/copybara_px_api.yaml
- ci/run_copybara.sh
Summary: Adds github action to run copybara to the pxapi.go repo.
The pxapi.go repo is a copy of the src/api/go tree. This copybara was previously done on Jenkins, moving it over to github actions.
Test Plan: Will test with `workflow_dispatch`.
> [actions] Add pxapi copybara action.

- k8s/devinfra/action-runners/README.md
- k8s/devinfra/action-runners/runnerdeployment.yaml
Summary: This PR adds instructions for how to deploy Github action runners on Kubernetes. We will use these action runners to improve our PR build process/release builds/etc on Github. We will likely add more changes to the runner deployment as we get a better idea of what runners we need.
Test Plan: Deploy helm chart
> Add instructions for deploying k8s runners

- k8s/devinfra/jenkins-oss/values.yaml
Summary: When Jenkins restarts, the buildURL often gets cleared out. We can use jcasc to populate the build URL.
Test Plan: Deploy to Jenkins
> Move jcasc for buildURL lower

- tools/chef/cookbooks/px_dev/recipes/linters.rb
- tools/chef/cookbooks/px_dev/recipes/python.rb
- tools/chef/cookbooks/px_dev_extras/attributes/mac_os_x.rb
Summary: This fixes chef runs on macOS
Test Plan: Ran chef on a macOS machine. Ensured it ran to completion.
> Fix chef on macOS

- k8s/devinfra/jenkins-oss/values.yaml
Signed-off-by: Michelle Nguyen <michellenguyen@pixielabs.ai>
Summary: This change adds the operator release build in jcasc, which includes adding the necessary plugins.
This change also fixes the jenkins build URL. Originally, we were adding the build URL in the jcasc configs. The config would be successfully loaded when the Jenkins pod first starts up, since the build URL isn't populated at that point. However, if we were to reload the config with the Jenkins pod already running, the config would fail to load properly because we will try to rewrite the buildURL which is now populated in the "defaultConfig". Turns out we can properly specify the build URL as a part of the ingress.
Test Plan: Deploy to Jenkins
> Add operator release build to jcasc and fix buildURL

- Jenkinsfile
Summary: We use #ci based tagging to trigger bpf builds on some runs. This
change ensures that it works for our new non Phabricator model.
Test Plan: Ensure that builds on a PR with #ci tags trigger the bpf builds.
> Ensure that non-Phabricator code review builds check for tags

- src/ui/.yarn/sdks/typescript/lib/tsserver.js
- src/ui/.yarn/sdks/typescript/lib/tsserverlibrary.js
Summary: Without doing this, the eslint plugin fails to load properly as of recent updates to VS Code.
This was done by running `yarn dlx @yarnpkg/sdks vscode` from `//src/ui`. For more information on what this is, see [Yarn's documentation](https://yarnpkg.com/getting-started/editor-sdks).
Test Plan: N/A
> Update Yarn SDK for VS Code

- .github/workflows/pr_description_linter.yaml
- ci/pr_description_linter.sh
Summary: Adds a github action to lint PR descriptions. This will lead to more consistent commit messages once PRs are merged.
Test Plan: Tested the script locally. Going to test the linter in this PR.
> [actions] Add PR description linter.

- .github/PULL_REQUEST_TEMPLATE.md
Summary: Update Pull request template with more context on the "Type of change" field
Test Plan:
When I created my first PR with the new workflow (#735), I was confused on if the `/kind ` prefix mattered. A description like this would have cleared up my confusion.
> Update Pull request template with more context on the "Type of change" field

- src/stirling/source_connectors/socket_tracer/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/redis_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/testing/protocol_checkers.h
Summary: Reduce redis_trace_bpf_test flakiness by asserting ordering of expected redis records
The redis_trace_bpf_test test has two sources of flakiness:
* VerifyBatchedCommands sometimes receives >200 traces rather than the 19 expected ones (P263). See the "which has 222 elements" output in the paste
* VerifyCommand test failures due to completely missing traces. This manifests by the error seen below:
```
src/stirling/source_connectors/socket_tracer/redis_trace_bpf_test.cc:253 Expected equality of these values: tablets.size() Which is: 0 1
src/stirling/source_connectors/socket_tracer/redis_trace_bpf_test.cc:253
Expected equality of these values:
tablets.size()
Which is: 0
1
``` 
This change addresses the first issue since it is responsible for the vast majority of test failures. I …
> Reduce redis_trace_bpf_test flakiness by asserting ordering of expected redis records

- src/datagen/pii/privy/requirements.txt
Summary: Fix privy build issues due to missing pip dependencies (setuptools, wheel)
Privy uses pytorch which needs the `setuptools` and `wheel` pip packages to build properly. This was discovered while working on #753
Test Plan: Verified that Privy's failing build on main is no longer present
```
ddelnano@turing:~/code/pixie/src/datagen/pii/privy$ bazel build //privy:all
ERROR: /home/ddelnano/code/pixie/src/datagen/pii/privy/privy/BUILD.bazel:22:11: no such package '@privy_deps_setuptools//': The repository '@privy_deps_setuptools' could not be resolved: Repository '@privy_deps_setuptools' is not defined and referenced by '//privy:privy_library'
ERROR: Analysis of target '//privy:privy_library' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.369s …
```
> Fix privy build issues due to missing pip dependencies (setuptools, wheel)

- Jenkinsfile
- ci/operator_build_release.sh
- k8s/devinfra/jenkins-oss/values.yaml
Summary: We are moving our release builds to our OSS Jenkins instance. Previous PRs created the release build in the Jenkins instance using jcasc. This change updates the Jenkinsfile so that the release build runs properly in the env.
Test Plan: Create an operator rc, ensure the build runs.
> Fix operator release build to work in OSS Jenkins

- ci/pr_description_linter.sh
Summary: Only prevent whitespace from starting lines, instead of non-word characters. This allows for:
- codeblocks
- markdown lists
- etc
Test Plan: Tested locally with markdown lists. Also testing with this PR's description.
> [PR Description Linter] Allow non-word characters at beginning of lines.

- bazel/test_runners/qemu_with_kernel/exit/BUILD.bazel
- bazel/test_runners/qemu_with_kernel/exit/exit.c
Summary: This write a value to the exit ISA buffer in qemu to quit and return the status code. We'll be using this to return the test status.
Test Plan: verified the binary is static `ldd exit` and checked it works in qemu.
> Add utility that allows us to quit QEMU on test completion

- src/stirling/source_connectors/socket_tracer/testing/protocol_checkers.h
Summary: Our coverage build uses gcc in dbg mode and was failing due to
a `range-loop-construct` warning. This fixes the warning by using a reference
type in the test.
/kind failing-test
Test Plan: `bazel coverage --remote_download_outputs=all --combined_report=lcov //src/stirling/source_connectors/socket_tracer:redis_trace_bpf_test`
no longer fails to build.
> Fix coverage build

- src/datagen/pii/privy/requirements.txt
Summary: This addresses CVE-2022-40897, CVE-2022-40898, and CVE-2022-40899
Test Plan: Privy continues to build and test successfully.
> Upgrade some privy deps to address CVEs

- .github/PULL_REQUEST_TEMPLATE/blank_template.md
- .github/PULL_REQUEST_TEMPLATE/guided_template.md
Summary: Starting comments on a newline makes it easier to delete them in an editor.
Also add a blank template with no comments for experienced contributors who already
know what the various sections should include.
Test Plan: N/A
> Update pullrequest template

- CODEOWNERS
Summary: Updates the CODEOWNERS to add reviewers for third-party code.
Test Plan: N/A. Will be tested once we have a plan for enforcing reviews from
owners.
> Update CODEOWNERS to add third-party reviewers

- bazel/repositories.bzl
- bazel/repository_locations.bzl
- src/datagen/pii/privy/requirements.txt
Summary: This upgrades the version of python being used which in turn fixes
the binary install of numpy.
Test Plan: All python buildables and tests continue to work.
> Upgrade rules_py

- k8s/cloud_deps/dev/postgres/postgres_deployment.yaml
- k8s/cloud_deps/public/postgres/postgres_deployment.yaml
Summary: The postgres deployment was matching all pods in the pl-cloud app due
to the missing name selector. This fixes the same.
Test Plan: When using k9s and selecting the postgres deployment, only the
postgres pod is listed now.
> Add missing selector fields for postgres deployments

- .github/workflows/copybara_px_api.yaml
- .github/workflows/filename_linter.yaml
- .github/workflows/pr_description_linter.yaml
- .github/workflows/pr_linter.yml
Summary: These issues were flagged by CLOMonitor. Restrict permissions to Read
only.
Test Plan: All workflows should continue to run.
> Restrict token permissions to readonly for workflows

- ci/pr_description_linter.sh
Summary: Allow "Changelog Message" part of PR description to not have any content on the same line.
The formatting for Changelog Message is to have a code block on the next line, so no need to check for content on the same line like with other stanzas.
Test Plan: Tested that the pr description linter works on Changelog message with a newline after it.
> Fix pr description linter for Changelog Message

- src/stirling/source_connectors/socket_tracer/protocols/http/body_decoder_benchmark.cc
Summary: This file had an incorrect license applied to it.
Test Plan: N/A
> Fix license header

- k8s/devinfra/jenkins-oss/values.yaml
Summary: The k8s jenkins builders should have a clean state anyway.
We don't need to call clean.
Test Plan: Updated jenkins with new configs.
> Don't clean git/workspace

- k8s/devinfra/jenkins-oss/values.yaml
Summary: `triggers` is deprecated and will be removed in the future.
Use `pipelineTriggers` as suggested by [the migration guide](https://github.com/jenkinsci/job-dsl-plugin/wiki/Migration#pipeline-job-plugin)
Test Plan: Upgraded jenkins with new configs, builds continue to trigger.
> Replace deprecated triggers with pipelineTriggers

- k8s/devinfra/jenkins-oss/values.yaml
Summary: Remove githubPush trigger. ghprb adds it's own hooks.
Also cancel builds when a new one is queued.
Test Plan: Update jenkins with new config.
> Remove unused github trigger for PR jobs

- .github/workflows/pr_linter.yml
Summary: Running the linter without trace makes it somewhat challenging to
figure out why it failed.
Also tell arc to apply patches and then look for changed files to see
if any autofix lint suggestions were not applied.
Test Plan: Check the output from the linter runner on this PR.
> Update linter workflow to trace and also check for autofix issues

- .github/workflows/pr_linter.yml
Summary: The prototool linter relies on a local branch called main
to compare against. This ensures it exists so that prototool
can work.
Test Plan: PRs with proto changes should not fail lint after this.
> Fix prototool linter

- k8s/vizier_deps/base/etcd/etcd_statefulset.yaml
Signed-off-by: rosenlo <rosenluov@gmail.com>
Summary: Fix missing backslash on the etcd command
Relevant Issues: #775
Test Plan: N/A
```release-note
Fix missing backslash on the etcd command
```
> Fix missing backslash on the etcd command

- .github/workflows/pr_linter.yml
Summary: `diff-index` triggers on touched files. `git status --porcelain` is
simpler to use instead.
Test Plan: Lint runs should only fail if there are changes.
> Use git status porcelain instead of diff-index to check state of tree

- src/stirling/source_connectors/socket_tracer/http_trace_bpf_test.cc
- src/stirling/testing/demo_apps/go_http/go_http_client/main.go
Summary: go 1.20 changed the default random seeding. Since we do
actually want a seeded random for this test server/client, this
change ensures that we explicitly use a seeded random.
Relevant Issues: Fixes #757
Test Plan: The disabled test assertion now passes again.
> Use seeded random to fix GoHTTPTraceTest.LargePostMessage

- .github/workflows/pr_linter.yml
Summary: eslint requires node deps to be installed. This ensures
that they are cached if possible.
Test Plan: The linter action should see some speedup when UI code
is linted.
> Add yarn cache to lint runner

- bazel/external/rules_docker_arch.patch
- bazel/repositories.bzl
Summary: Add support in rules_docker for setting the container architecture based on bazel's target platform.
This patches rules docker to automatically select the right docker architecture given the bazel target platform's CPU constraint.
I will try to upstream this patch to the rules_docker repo.
Type of change: /kind build-infra
Test Plan: Tested by running `docker inspect <image>` on an image built and pushed with this patch under `--config=aarch64_sysroot` (PR #762), saw that the Architecture was listed as arm64, where before this patch it was listed as amd64.
> Add rules docker support for selecting architecture based on platform

- k8s/cloud/base/ory_auth/kratos/kratos_deployment.yaml
- k8s/vizier/base/kelvin_deployment.yaml
- k8s/vizier/base/patch_sentry.yaml
- k8s/vizier/base/query_broker_deployment.yaml
- k8s/vizier/bootstrap/cloud_connector_deployment.yaml
- k8s/vizier/etcd_metadata/base/metadata_deployment.yaml
- k8s/vizier/pem/base/pem_daemonset.yaml
- k8s/vizier/persistent_metadata/base/metadata_statefulset.yaml
- k8s/vizier/sanitizer/kelvin_deployment.yaml
- src/e2e_test/jetstream_loadtest/k8s/subscriber_deployment.yaml
- src/e2e_test/protocol_loadtest/http/wrk/k8s/client_deployment.yaml
- src/e2e_test/protocol_loadtest/k8s/client/client_deployment.yaml
Summary: Switches curl images to use multiarch manifest lists instead of amd64 images. This way they can be deployed on clusters with mixed architectures.
This is another step along the way to supporting ARM for vizier.
Test Plan: Tested that a skaffold deploy of Pixie still works. Will test with other ARM changes to make sure deploy works on multiarch/arm clusters.
> Switch to multiarch curl images.

- src/operator/controllers/monitor.go
- src/operator/controllers/monitor_test.go
- src/operator/controllers/pvc_watcher.go
Summary: The operator tries to be smart by trying to switch the user to an etcd-based deployment based on some conditions, as long as they have been in that state for over 5 mins. These checks may be too hasty, as sometimes a user's cluster may just be slower for various reasons. This leads to some users getting unexpectedly moved to an etcd-based deploy.
There is also some extra logic to fix a state that users could have gotten into because of auto-repair. Now that the operator has been out in the wild for sometime, we can clean up this extra logic for cleanliness/simplification.
A followup PR is coming to attempt to fix etcd-based deploys which may have gotten to a bad state (lost quorum)
Test Plan: Skaffold deploy operator
> Simplify operator etcd repair

- bazel/cc_resource.bzl
- bazel/cc_toolchains/toolchain_features.bzl
- bazel/pl_bpf_preprocess.bzl
- src/stirling/bpf_tools/bcc_bpf/BUILD.bazel
- src/stirling/bpf_tools/bcc_bpf/system-headers/BUILD.bazel
- src/stirling/bpf_tools/bcc_bpf_intf/BUILD.bazel
- src/stirling/bpf_tools/testdata/BUILD.bazel
- src/stirling/source_connectors/cpu_stat_bpftrace/bt/BUILD.bazel
- src/stirling/source_connectors/perf_profiler/bcc_bpf/BUILD.bazel
- src/stirling/source_connectors/perf_profiler/bcc_bpf_intf/BUILD.bazel
- src/stirling/source_connectors/perf_profiler/testing/bpf/BUILD.bazel
- src/stirling/source_connectors/pid_runtime/bcc_bpf/BUILD.bazel
- src/stirling/source_connectors/pid_runtime/bcc_bpf_intf/BUILD.bazel
- src/stirling/source_connectors/pid_runtime_bpftrace/bt/BUILD.bazel
- src/stirling/source_connectors/proc_exit/bcc_bpf/BUILD.bazel
- src/stirling/source_connectors/proc_exit/bcc_bpf_intf/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/bcc_bpf/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/bcc_bpf_intf/BUILD.bazel
- src/stirling/upid/BUILD.bazel
Summary: Implements `pl_bpf_preprocess` as a rule instead of a genrule.
In order to select on the platform for choosing defines to the preprocessing, we need this to be a fully-fledged rule instead of a genrule.
This has the added benefit of caching the preprocessor output.
Test Plan: Tested that the preprocessed output looks sane. Also ran `bazel build //...`. Relying on #ci:bpf-build to test that the preprocessed output is correct.
> Implement pl_bpf_preprocess as a rule instead of a genrule.

- .bazelrc
- BUILD.bazel
- bazel/cc_toolchains/sysroots/BUILD.bazel
- bazel/cc_toolchains/sysroots/build/sysroot.BUILD
- bazel/cc_toolchains/sysroots/images.bzl
- bazel/cc_toolchains/sysroots/runtime/sysroot.BUILD
- bazel/cc_toolchains/sysroots/sysroots.bzl
- bazel/cc_toolchains/sysroots/test/sysroot.BUILD
- bazel/images.bzl
- bazel/pl_build_system.bzl
- bazel/test_runners/BUILD.bazel
- bazel/test_runners/sysroot_chroot/BUILD.bazel
- bazel/test_runners/sysroot_chroot/chroot.sh
- bazel/test_runners/sysroot_chroot/runner.bzl
- bazel/test_runners/sysroot_chroot/setup_unshare.sh
- ci/vizier_build_release.sh
- k8s/vizier/BUILD.bazel
- src/carnot/carnot_test.cc
- src/carnot/exec/grpc_router_test.cc
- src/carnot/exec/local_grpc_result_server.h
- src/stirling/source_connectors/perf_profiler/java/agent/BUILD.bazel
Summary: Adds pushing multi-arch images in the vizier release process.
Builds each architecture's images separately and pushes those individually. Then pushes a manifest list pointing to each architecture for each vizier image.
Test Plan: Changed the image prefix to a gcr I have access to, ran the script with a fake tag, saw that multi-arch manifest lists are correctly pushed.
> Support pushing multi-arch images in vizier_build_release.sh

- k8s/devinfra/jenkins-oss/values.yaml
Summary: This should directly link to blue ocean instead of classic jenkins
which works better with our buildstages. Also remove unused plugin.
Test Plan: Check the jenkins link on this github PR.
> Update Jenkins CASC to use blue ocean urls

- ci/jenkins.bazelrc
Summary: This metadata was set to a stale value. Update it.
Test Plan: Check buildbuddy on the CI run for this PR.
> Update build metadata repo

- ci/bpf/00_create_instance.sh
- ci/jenkins.bazelrc
Summary: We should have enough quota to support 32cpu machines.
Will keep an eye out and bump to 48 if possible.
Test Plan: N/A
> Update bpf build machines to have 32 cpus

- src/operator/controllers/monitor.go
- src/shared/status/vzstatus.go
Summary: We've noticed that a lot of clusters running etcd are in a state where etcd is crashing. This is very likely to happen if etcd loses quorum. This PR updates the operator to detect that state and attempt to fix it by restarting etcd.
Test Plan: Skaffold deploy operator
> Add auto-repair for crashing etcd in operator

- src/carnot/funcs/metadata/metadata_ops.h
- src/carnot/funcs/metadata/metadata_ops_test.cc
- src/shared/k8s/metadatapb/test_proto.h
Summary: There are some missing nullptr checks in
GetOwnerReferenceInfosFromMetadataObject causing segfaults.
The func should be rewritten but this is a quick fix to
unblock the release before I rewrite the func.
The first of two commits is a testcase that exhibits the
behavior, the latter fixes the issue.
Test Plan: Added a test case that exhibits the segfault without
the accompanying fix.
> Fix segfault in GetOwnerReferenceInfosFromMetadataObject

- ci/bpf/00_create_instance.sh
Summary: GCE doesn't have a c2-standard-32 machine, only a c2-standard-30 machine. This updates the bpf workers to use `n2d-standard-32` instead.
Test Plan: Run #ci:bpf-build
> Fix bpf machine type

- src/carnot/funcs/metadata/metadata_ops.h
- src/shared/metadata/metadata_state.cc
- src/shared/metadata/metadata_state.h
Summary: The `GetOwnerReferenceInfosFromMetadataObject` method
was a bit complex and too abstract whereas our usecases for
it were very simple. Thie introduces `OwnerReplicaSetInfo` and
`OwnerDeploymentInfo` which effectively achieve the same end
goal but also make the code easier to follow.
Relevant Issues: This is a followup from #820 where we discovered and patched
a SegFault.
Test Plan: All the metadata and metadata_ops tests pass.
> Cleanup owner references code

- Jenkinsfile
Summary: This should set the actions style checkmark
status on github after jenkins runs on main.
Should help track broken main builds.
Test Plan: Check status on main after this lands.
> Set build status on Github after Jenkins runs

- bazel/test_runners/qemu_with_kernel/create_sysroot_disk.sh
Summary: Files inside the disk image were owned by the user, they are now owned by root.
Test Plan: `sudo mount -o loop test.img <mount_path>` and the check the file permissions.
> Make sure files inside qemu disk image are owned by root

- src/stirling/obj_tools/init.cc
Summary: Adds initialization of LLVM targets for x86 and aarch64. Previously, we only initialized the native target (x86).
Relevant Issues: necessary for #147
Test Plan: No change in existing functionality. Only adds support for ARM targets to LLVM disassembler.
Will run #ci:bpf-build to make sure no changes in functionality of existing disassembler.
> Initialize both x86 and aarch64 for LLVM

- src/utils/artifacts/artifact_db_updater/BUILD.bazel
- src/utils/artifacts/artifact_db_updater/artifact_db_updater_job.yaml
- src/utils/artifacts/artifact_db_updater/main.go
Summary: Updates the artifact_db_updater_image to use a `pl_go_image` instead of a `container_image`.
This ensures that our version of glibc is pulled in, instead of the default in the `base_image_debug` distroless image.
Ideally, we wouldn't need a debug image here, but I don't want to mess with the artifact_db_updater_job too much.
Test Plan: @aimichelle is testing it on staging.
> Fix artifact_db_updater image

- k8s/vizier_deps/base/nats/nats_statefulset.yaml
Summary: Use multi-arch manifest list version of NATS.
Test Plan: Tested that if I manually deploy this version of NATS to an x86 cluster the cluster still works. Also tested that this version of NATS works on an ARM cluster.
> Use multiarch version of NATS

- .github/workflows/cacher.yaml
- .github/workflows/pr_genfiles.yml
- .github/workflows/pr_linter.yml
Summary: After reading the [docs](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache), I realized that github caches are local to PRs/branches.
This sets up a workflow on main pushes solely to populate the cache since other runs can restore from a cache on the main branch.
Test Plan: Test this to see if cache hits on PRs go up.
> Add cacher workflow to main to generate caches for PRs

- codecov.yml
Summary: Small changes in the coverage are failing the main build. Make coverage infromation "informational"
until we add PR coverage.
Test Plan: `cat codecov.yml |  curl --data-binary @- https://codecov.io/validate`
> Don't fail the main build if coverage drops

- bazel/test_runners/qemu_with_kernel/create_sysroot_disk.sh
Summary: Install busybox into the qemu test image. This will make it easier to access commands such as `mount` from the init scripts.
Test Plan: mount the image and verify that busybox and utilities are installed.
> Install busybox as part of the qemu image

- bazel/repository_locations.bzl
Summary: Support arm64 syscall prefixes in bcc.
Test Plan: Relying on #ci:bpf-build to test existing functionality. This shouldn't affect existing functionality though.
> Update bcc to support arm64 syscall prefixes

- k8s/cloud/public/artifact_tracker_versions.yaml
Summary: Public cloud users are missing CQL funcs since they
are running old viziers but new script bundles. This
should fix the same.
Relevant Issues: Addresses one of the issues found in #764
Test Plan: Once a new cloud release is tagged, deploying a
public cloud shouldn't cause errors about missing `cql_opcode_name`
> Bump versions for public cloud

- .bazelrc
- bazel/pl_build_system.bzl
- bazel/test_runners/BUILD.bazel
- bazel/test_runners/sysroot_chroot/BUILD.bazel
- bazel/test_runners/sysroot_chroot/chroot.sh
- bazel/test_runners/sysroot_chroot/runner.bzl
- bazel/test_runners/sysroot_chroot/setup_unshare.sh
- src/carnot/carnot_test.cc
- src/carnot/exec/grpc_router_test.cc
- src/carnot/exec/local_grpc_result_server.h
Summary: Adds test runner for chrooting into an environment with the sysroot installed at root.
This PR allows running all tests in either the x86 or arm64 sysroots.
The chroot environment runs in its own mount and PID namespaces (via linux's unshare command). Once we replace `docker` with `podman` we can also run the chroot in its own network namespace.
As well as mounting the sysroot at root, the chroot environment is also setup to have both bazel's output_base and the top of the Pixie repo, bind mounted into the same locations in the chroot.
This makes bazel's symlinks work as expected.
Additionally, these two mounts use an overlayfs, such that the actual filesystem is not changed if there are any changes made inside the chroot environment.
Type of change: /kind …
> [build/sysroots] Add test runner for sysroot builds.

- bazel/test_runners/qemu_with_kernel/hostname
- bazel/test_runners/qemu_with_kernel/init
- bazel/test_runners/qemu_with_kernel/passwd
Summary: This some of the basic files needed to be added to the qemu disk image.
Test Plan: Check and make this works:
```bash
./create_sysroot_disk.sh -s sysroot-amd64-test.tar.gz -o test.qcow2 \
-e init:/bin/init,passwd:/etc/passwd,hostname:/etc/hostname -b busybox
qemu-img create -f qcow2 -F qcow2 -b test.qcow2 overlay.qcow2
qemu-system-x86_64 \
-append "console=ttyS0 root=/dev/sda" \
-device isa-debug-exit,iobase=0xf4,iosize=0x4 \
-hda overlay.qcow2 \
-kernel bzImage \
-cpu host \
-m 4096 \
-cpu max \
-nographic
```
> Create hostname, init and passwd files for qemu test runner

- src/shared/metadata/standalone_state_manager.cc
Summary: Client-side tracing is currently broken in the standalone PEM. This is because we automatically disable client-side tracing for any addresses that fall within the cluster CIDR, or if no cluster CIDR is specified.
This updates the pod CIDR (which gets propagated to the context's cluster CIDR) so that client-side tracing works. Used the cluster CIDR that was specified in `StandaloneContext`.
Test Plan: Run standalone PEM and run go binary which makes outgoing HTTP calls with/without TLS.
> Fix client-side tracing in standalone PEM

- BUILD.bazel
- bazel/cc_toolchains/sysroots/BUILD.bazel
- bazel/cc_toolchains/sysroots/build/sysroot.BUILD
- bazel/cc_toolchains/sysroots/images.bzl
- bazel/cc_toolchains/sysroots/runtime/sysroot.BUILD
- bazel/cc_toolchains/sysroots/sysroots.bzl
- bazel/cc_toolchains/sysroots/test/sysroot.BUILD
- src/stirling/source_connectors/perf_profiler/java/agent/BUILD.bazel
Summary: Adds support for building images using the sysroot configs (--config=x86_64_sysroot or --config=aarch64_sysroot).
This means we can now build our images targetting aarch64!
Relevant Issues: https://github.com/pixie-io/pixie/issues/147
Type of change: /kind build
Test Plan: Tested that `pem_image` builds under both `--config=x86_64_sysroot` and `--config=aarch64_sysroot`.
Also, tested that the built image doesn't have any shared library loading issues.
> [build/sysroots] Allow building docker images with sysroots. 

- src/common/base/arch.h
- src/common/base/base.h
- src/stirling/obj_tools/elf_reader.cc
- src/stirling/source_connectors/socket_tracer/bcc_bpf/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/bcc_bpf/go_trace_common.h
Summary: Adds support for ARM inside of stirling.
- Adds support to the bpf probes for targetting ARM. Specifically changes where we get the pointer to thread local storage, and how we access registers.
- Adds support in ELF reader for disassembling ARM binaries.
All of these changes are behind ifdefs based on the architecture being compiled for.
Test Plan: Tested that the deployed images work on an ARM cluster. Saw HTTP data, process data, flamegraph data and more.
More testing needs to be done to ensure that all the data being collected is still correct.
Additionally, once we have the infrastructure to run bpf tests through QEMU, we should make sure those tests work for ARM.
> Add support for ARM in the datacollector.

- skaffold/skaffold_vizier.yaml
Summary: Add profiles to skaffold deploy sysroot images.
Test Plan: Tested that skaffold works with both profiles.
> Add sysroot profiles to vizier skaffold

- tools/docker/Makefile
- tools/docker/sysroot_creator/build_tar_for_packages.sh
- tools/docker/sysroot_creator/package_groups/runtime.yaml
Summary: Adds support in sysroot creator for adding arbitrary empty directories in the sysroot.
Then uses this support to add `/tmp` to the runtime sysroot.
Without `/tmp` `std::tmpfile` fails on some systems, which was leading to segfaults when I deployed on nodes without installed kernel headers.
Test Plan: Tested that the created sysroots have an empty `/tmp`. Also tested that if you put `/tmp` in the image `std::tmpfile` no longer fails.
> Add /tmp to runtime sysroot

- BUILD.bazel
Summary: A previous diff added support for building images with the sysroot configs.
However, I forgot to update the debug image in that diff, so this updates the debug image to work with the sysroot configs.
Test Plan: Tested that you can now run programs built under `--config={x86_64,aarch64}_sysroot` in the debug image, where before you would get glibc errors loading shared libs.
> Add sysroot to cc debug image

- src/stirling/obj_tools/BUILD.bazel
- src/stirling/obj_tools/dwarf_reader_benchmark.cc
- src/stirling/obj_tools/dwarf_reader_test.cc
- src/stirling/source_connectors/socket_tracer/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/uprobe_symaddrs_test.cc
- src/stirling/testing/demo_apps/go_grpc_tls_pl/client/BUILD.bazel
- src/stirling/testing/demo_apps/go_grpc_tls_pl/server/BUILD.bazel
Summary: Building with go 1.16 blocks us from upgrading some go libs
that depends on features introduced in go 1.17
go 1.16 has been EOL since 15 Mar 2022 and we don't see too many
folks running it in the wild so it should be fine to remove these
tests.
Relevant Issues: #846
Test Plan: All test pass locally. Check Jenkins for BPF tests.
> Remove more uses of go 1.16 binaries

- src/stirling/binaries/stirling_profiler.cc
Summary: We switch to using gflags command line args in the stirling profiler binary.
This reduces the code that we need to read and maintain in this file. Next, we plan to continue to cleanup this binary by reducing its dependency on the full stirling cc-lib and then we plan to add pprof proto output (and remove the text output).
Test Plan: Tested new cmd line args locally.
> Cleanup cmd line args in stirling profiler binary.

- src/stirling/source_connectors/socket_tracer/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/protocols/pgsql/stitcher.cc
- src/stirling/source_connectors/socket_tracer/protocols/pgsql/stitcher_test.cc
- src/stirling/source_connectors/socket_tracer/protocols/pgsql/types.h
Summary: Prevent pgsql stitcher from assuming that a matching response will exist when a request is seen
The pgsql_trace_bpf_test has been flaky and led us to disabling it recently #697. This phab addresses the underlying issue so the test is more reliable.
The source of the flakiness is due to how the pgsql stitcher works. It previously assumed that when it sees a request that the matching response exists during the same invocation to StitchFrames. For our test harness, this is true the majority of the time. However, there are times where stirling sees the request in isolation, calls StitchFrames and then receives the response by the second call to StitchFrames. The previous stitcher implementation discards all requests at the [end of a …
> Prevent pgsql stitcher from assuming that a matching response will exist when a request is seen

- Jenkinsfile
- k8s/devinfra/jenkins-oss/values.yaml
Summary: We are in the process of adding our release builds to the new OSS Jenkins. This adds our cloud release build to the new Jenkins via jcasc. This also required some renaming in the Jenkinsfile to make sure our cloud builds don't conflict.
Test Plan: Create a tag in staging, push it, and ensure that the build runs properly. (This tag has now been deleted)
> Add cloud release build to Jenkins

- bazel/repository_locations.bzl
Summary: Updates to a new commit of our fork of ELFIO. This commit adds the EM_AARCH64 value that is on serge1/ELFIO main.
Putting off rebasing on serge1/ELFIO, because our patches don't apply cleanly.
Test Plan: Relying on existing tests, since its only a change to the name of a constexpr in ELFIO (and we didn't rely on the previous name).
> Update ELFIO to include EM value for AARCH64

- bazel/test_runners/qemu_with_kernel/exit_qemu_with_status/BUILD.bazel
- src/stirling/BUILD.bazel
- src/stirling/source_connectors/perf_profiler/java/agent/BUILD.bazel
Summary: To get aarch64 images to work I added a select on cpu:x86_64 for the java agent. I put this select in the wrong place, because it causes test builds to fail.
This PR moves the select to where its only used for the image and not for the tests.
Test Plan: Ran `bazel test --config=aarch64_sysroot //...` and saw only 7 failed tests as expected.
> Fix config=aarch64_sysroot build

- bazel/cc_toolchains/sysroots/sysroots.bzl
Summary: Updates the sysroots to pl3 revision. This revision ensures there's a tmp directory in the runtime sysroots.
Relevant Issues: #147.
Test Plan: Ran `bazel test //... --config=x86_64_sysroot` and `bazel test //... --config=aarch64_sysroot` and both worked (ignoring the expected 7 failed tests for aarch64).
> Update sysroots to pl3 revision.

- src/stirling/obj_tools/BUILD.bazel
- src/stirling/obj_tools/vaddr_to_baddr_tool.cc
Summary: Adds vaddr_to_baddr_tool that converts a virtual address from a running process to a binary address, i.e. a specific location in the underlying binary.
Relevant Issues: https://github.com/pixie-io/pixie/issues/719.
Type of change: /kind feature.
Test Plan: Used this to convert virtual addresses captured by the perf profiler and find their disassembly. Confirmed the hypothesis that sampled stack traces with missing frames pointed to either function entry or function exit.
Signed-off-by: Pete Stevenson <jps@pixielabs.ai>
> Add vaddr_to_baddr_tool to convert virtual addrs on the command line.

- src/utils/template_generator/vizier_yamls/vizier_yamls.go
Summary: We have been seeing errors from several clusters where their deploy has failed due to being on an earlier K8s version without policy/v1 PodDisruptionBudgets. The API version change for pdb is currently the only item preventing us from supporting older K8s versions.
This PR templatizes the etcd YAMLs so that we can choose between policy/v1 and policy/v1beta1 for PodDisruptionBudgets based on the K8s version. Currently, without the flag being set it selects `policy/v1` which is status quo.
Test Plan: Create and deploy Vizier rc with etcd option enabled
> Template PodDisruptionBudget apiVersion to enable support for older K8s versions

- ci/bpf/00_create_instance.sh
Summary: This flag was accidentally duplicated. Cleanup.
Test Plan: The BPF test runners continue to work.
> Remove duplicate flag in create_instance script

- bazel/pl_build_system.bzl
- src/stirling/obj_tools/testdata/go/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/protocols/http2/testing/go_grpc_client/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/protocols/http2/testing/go_grpc_server/BUILD.bazel
- src/stirling/testing/demo_apps/go_grpc_tls_pl/client/BUILD.bazel
- src/stirling/testing/demo_apps/go_grpc_tls_pl/server/BUILD.bazel
- src/stirling/testing/demo_apps/go_https/client/BUILD.bazel
- src/stirling/testing/demo_apps/go_https/server/BUILD.bazel
Summary: Maintaining all the various `go_cross_binary` rules and
their corresponding images is a lot of manual work.
Instead we can use list comprehension to generate the rules
for all the supported SDK versions and then use them for any
tests as needed. This should make it easier to add/remove
support for go sdks.
Test Plan: All existing build and test rules work.
> Convert go_cross rules to use list comprehension

- k8s/vizier/base/arch_tolerations/deployment.yaml
- k8s/vizier/base/arch_tolerations/job.yaml
- k8s/vizier/base/arch_tolerations/statefulset.yaml
- k8s/vizier/base/kustomization.yaml
- k8s/vizier/pem/base/arch_tolerations/daemonset.yaml
- k8s/vizier/pem/base/kustomization.yaml
- k8s/vizier/persistent_metadata/aarch64/daemonset.yaml
- k8s/vizier/persistent_metadata/aarch64/deployment.yaml
- k8s/vizier/persistent_metadata/aarch64/job.yaml
- k8s/vizier/persistent_metadata/aarch64/kustomization.yaml
- k8s/vizier/persistent_metadata/aarch64/statefulset.yaml
- k8s/vizier/persistent_metadata/x86/daemonset.yaml
- k8s/vizier/persistent_metadata/x86/deployment.yaml
- k8s/vizier/persistent_metadata/x86/job.yaml
- k8s/vizier/persistent_metadata/x86/kustomization.yaml
- k8s/vizier/persistent_metadata/x86/statefulset.yaml
- skaffold/skaffold_vizier.yaml
Summary: Adds k8s tolerations for aarch64 and x86.
The base has patches for multiarch.
For skaffold deploys we use single arch versions of the patches.
Test Plan: Tested that I can build the yamls, and skaffold deploy. Will cut an RC to test that the yamls look good there.
> Add k8s tolerations for aarch64 and x86

- Jenkinsfile
- ci/bpf/03_run_tests.sh
Summary: The Jenkins test reporter reports stats on test that
were run and failed. However we don't upload to test stashes
when the tests fail, which means we lose this data.
Instead capture retval 3 from bazel and ensure that stash
uploads happen when retval is 3. This will ensure that we
get aggredate test reports from jenkins.
Test Plan: Broke some tests to try this out.
> Upload testresults to stash even when some tests fail

- .github/workflows/pr_genfiles.yml
Summary: The script in the workflow had a stale retval reference.
Fix it and exit with 1 instead.
Test Plan: The workflow should exit with a non-zero code when
genfiles need to be updated.
> Fixup genfiles workflow

- src/ui/cypress/integration/live/keyboard-shortcuts.spec.ts
- src/ui/cypress/integration/live/navbars.spec.ts
- src/ui/src/components/command-palette/command-palette-trigger.tsx
- src/ui/src/containers/App/sidebar.tsx
Summary: A handful of Cypress tests weren't correctly specified or weren't updated for the existence of the Command Palette.
Fixing these also found a couple of minor typos elsewhere, which this change also fixes.
Test Plan: Run Cypress tests.
Type of change: /kind failing-test
> Fix failing Cypress tests

- k8s/devinfra/jenkins-oss/values.yaml
Summary: This fixes the ingress issues with the ManagedCertificate.
Now managed certs work properly and should auto renew.
This also sets up a GKE backend config with CDN caching enabled.
This should make Jenkins feel snappier.
Test Plan: Deployed to Jenkins
> Update jenkins ingress configs

- src/operator/BUILD.bazel
- src/operator/controllers/vizier_controller.go
- src/operator/manager.go
Summary: You can now send your K8s cluster version to the config manager service, which allows the config manager service to modify the Vizier YAMLs accordingly based on your cluster version.
This PR updates the operator to fetch the K8s cluster version and pass it to the configmanager service when deploying a Vizier.
Test Plan: Skaffold deploy operator and verify that K8s version is fetched properly
> Operator: Fetch and send K8s cluster version to ConfigManager

- src/cloud/config_manager/controllers/BUILD.bazel
- src/cloud/config_manager/controllers/server.go
Summary: We can now change the apiVersion of podDisruptionBudget in our Vizier YAMLs. The configmanager service can decide to do so based on the K8s version provided by the operator.
Test Plan: Skaffold deploy testing cloud
> ConfigManager service should determine which PodDisruptionBudget apiVersion to use based on K8s version

- tools/docker/Makefile
Summary: When I added building of ARM headers, I didn't test the gsutil cp command part of the upload process. This fix is necessary so that both architectures' header tars get uploaded, instead of just the first one.
Test Plan: Tested by uploading to a bucket I have access to.
> Fix linux headers upload

- tools/docker/linux_headers_image/Dockerfile
Summary: The linux kernel has a confusing naming system for x86_64 which includes x86_64,x86, and amd64 as names for the same architecture in different parts of the code base. When I added support for ARM headers, I accidentally removed the arch/x86 folder. This diff ensures that folder remains.
Test Plan: Tested a skaffold deploy on both aarch64 and x86_64.
> Fix linux headers for x86

- bazel/linux_headers.bzl
- src/stirling/BUILD.bazel
- src/stirling/utils/linux_headers.cc
- src/stirling/utils/linux_headers_test.cc
Summary: PR #883 added the docker build for an ARM version of linux headers. This PR pulls those linux headers into our Pixie build.
Which set of merged headers to use is determined by the platform bazel is building for.
Test Plan: Tested a skaffold deploy on each of x86_64 and aarch64.
> Use new linux headers that support ARM

- src/carnot/engine_state.h
- src/carnot/exec/exec_metrics.cc
- src/carnot/exec/exec_metrics.h
- src/carnot/exec/exec_state.h
- src/carnot/exec/otel_export_sink_node.cc
- src/carnot/exec/otel_export_sink_node.h
Summary: This PR adds a timeout to our OTLP span/metrics exports. It also adds a metrics counter for tracking how many OTLP timeouts have occurred, if any.
Test Plan: Skaffold deploy Vizier
> Add timeout to OTLP export

- tools/docker/Makefile
- tools/docker/sysroot_creator/build_tar_for_packages.sh
- tools/docker/sysroot_creator/package_groups/runtime.yaml
Summary: Adds `ca-certificates` package to runtime sysroots. Also creates a default cert chain by concatenating all of the `ca-certificates` certs. Debian usually creates this chain by running `update-ca-certificates`, which is a shell script that concatenates the certs based on a config file. However, it requires `sed` and other utilities. Instead of having to run this script inside the sysroot, we just manually concatenate the certs.
Test Plan: Ran `skaffold run -f skaffold/skaffold_vizier.yaml -p x86_64_sysroot` with the new sysroots, no longer saw errors in OTEL export.
> Add default root cert to sysroots

- bazel/cc_toolchains/sysroots/sysroots.bzl
Summary: Update sysroots to new revision that includes a root cert chain from the `ca-certificates` package.
See #905 for the sysroot changes.
Test Plan: Ran `skaffold run -f skaffold/skaffold_vizier.yaml -p x86_64_sysroot` and saw that there were no longer errors in Kelvin from the otel export.
> Update to new sysroots with root cert.

- src/stirling/source_connectors/socket_tracer/conn_tracker.cc
- src/stirling/source_connectors/socket_tracer/data_stream.cc
- src/stirling/source_connectors/socket_tracer/data_stream.h
- src/stirling/source_connectors/socket_tracer/data_stream_test.cc
- src/stirling/source_connectors/socket_tracer/metrics.cc
- src/stirling/source_connectors/socket_tracer/metrics.h
Summary: This updates the `SocketTracerMetrics` class to differentiate between plaintext and tls metrics. Since we are working to instrument BoringSSL based applications more broadly (#692), this will allow us to experiment with the underlying tls tracing implementation and verify that there aren't protocol parsing issues introduced (indicated by more data loss).
Test Plan: Updated the `mux_trace_bpf_test` and `netty_tls_trace_bpf_test` with the following diff to verify that they increment the correct counter ([P317](https://phab.corp.pixielabs.ai/P317))
> Update the socket tracer metrics to differentiate between tls and plaintext metrics

- src/stirling/e2e_tests/probe_cleaner_bpf_test.sh
- src/stirling/scripts/kprobe_leak_test.sh
- src/stirling/scripts/profile_stirling_wrapper.sh
- src/stirling/scripts/stirling_wrapper.sh
Summary: The uses of `bazel info` to find built binaries were
inaccurate in some places. Additionally calling out to bazel
in a test causes issues when running under qemu. This cleans up
`bazel info` calls in non-test helpers and updates the tests
to not invoke bazel and expect the relevant args to always be
supplied.
Test Plan: All the updated scripts and tests should continue to work.
> Remove uses of bazel info in scripts and tests

- bazel/cc_toolchains/sysroots/sysroots.bzl
- tools/docker/Makefile
- tools/docker/sysroot_creator/package_groups/test.yaml
Summary: Add curl to test sysroot. Its need for `bpf_map_leak_bpf_test`.
Test Plan: Made sure the curl binary is in the test sysroot now.
> Add curl to test sysroot

- src/common/testing/test_utils/container_runner.cc
Summary: Podman seems to print both  "Loaded image:" and "Loaded image(s):". This relaxes the check to make it less flaky.
Test Plan: Tested locally on qemu.
> Relax podman loaded image check

- src/common/testing/test_utils/container_runner.cc
- src/common/testing/test_utils/container_runner.h
Summary: This uses the native podman mechanism to terminate containers instead of launching a background process.
Test Plan: existing tests should pass
> Add container lifetime to podman containers

- src/common/testing/test_utils/container_runner.cc
Summary: Reduces noise in test output.
Test Plan: existing tests should pass
> Add -q to podman commands to reduce output

- src/ui/src/configurables/base/breadcrumb-extras.tsx
- src/ui/src/containers/live/breadcrumbs.tsx
Summary: Just a stub for now.
Test Plan: Try returning something, even just plain text, from 'breadcrumb-extras.tsx`. It should appear under the breadcrumbs on the right.
> Allow custom component underneath breadcrumbs

- bazel/cc_toolchains/sysroots/debug/BUILD.bazel
- bazel/cc_toolchains/sysroots/debug/sysroot.BUILD
- bazel/cc_toolchains/sysroots/sysroots.bzl
- bazel/test_runners/sysroot_chroot/chroot.sh
- tools/docker/Makefile
- tools/docker/sysroot_creator/build_all_sysroots.sh
- tools/docker/sysroot_creator/package_groups/debug.yaml
Summary: Adds a debug sysroot with gdb, lldb, and other llvm tools (eg. dwarfdump, objdump, etc).
Test Plan: Tested that using the flag `--//bazel/cc_toolchains/sysroots:debug_sysroot` I get a chroot with a functional `gdb` in it.
> Add debug sysroot

- src/stirling/source_connectors/socket_tracer/dyn_lib_trace_bpf_test.cc
Summary: Some versions of pgrep don't like --parent. Instead use -P which works more broadly.
Test Plan: existing tests, on qemu sysroot
> Use -P in pgrep to be compatible with more versions of pgrep

- src/common/testing/test_utils/container_runner.cc
Summary: The --timeout needs to be specified before the container name.
Test Plan: Make sure bpf tests actually pass.
> Fix podman timeout command

- src/utils/shared/k8s/auth.go
Summary: Adds `GetKubeconfigPath()` method to `k8s` package.
This method allows reusing the logic to find the kubeconfig that the `k8s` package uses.
Test Plan: No effect on existing code. Will be used for the `perf_tool`.
> Add GetKubeconfigPath method to k8s auth

- src/common/testing/test_utils/container_runner.cc
Summary: The previous PR did not run bpf tests and did not catch this regression.
Test Plan: Run BPF tests.
> Remove -q from podman rm

- src/stirling/source_connectors/socket_tracer/go_tls_trace_bpf_test.cc
Summary: This test used to rely on implicit container termination to progress. This change reduces the number of iterations
to make sure the test progresses.
Test Plan: Tested locally.
> Fix Go TLS trace test by reducing number of iterations

- src/stirling/source_connectors/perf_profiler/BUILD.bazel
- src/stirling/source_connectors/perf_profiler/perf_profiler_bpf_test.cc
Summary: We fix and re-enable the flaky perf profiler test. The underlying issue was stack trace aliasing due to missing stack frames. We document this issue in https://github.com/pixie-io/pixie/pull/896. In brief, because the stack trace walker sometimes skips a stack frame, the test logic could find two different stack traces that matched by leaf symbol. We previously did not realize this, and hence we used assign (vs. accumulate) when building the leaf symbol histogram. In this patch, we accommodate the missing stack frames by accumulating when building the leaf symbol histogram.
After the switch to `podman`, the Java tests started failing, on Jenkins, based on expected sample rate. It is hard to predict the actual number of samples that will occur for a Java process because we do not …
> [2 of 2] Fix & re-enable perf profiler test: accomodate leaf node aliasing in histogram.

- src/stirling/testing/demo_apps/go_grpc_tls_pl/client/client.go
- src/stirling/testing/demo_apps/go_grpc_tls_pl/k8s/client_deployment.yaml
- src/stirling/testing/demo_apps/go_grpc_tls_pl/k8s/kustomization.yaml
- src/stirling/testing/demo_apps/go_grpc_tls_pl/k8s/server_deployment.yaml
- src/stirling/testing/demo_apps/go_grpc_tls_pl/k8s/server_service.yaml
- src/stirling/testing/demo_apps/go_grpc_tls_pl/skaffold.yaml
Summary: Adds a skaffold deploy mechanism for the `go_grpc_tls_pl` demo app which we currently use in bpf tests.
Test Plan: Tested the skaffold deploy on both x86 and ARM.
> Add skaffold deploy for go_grpc_tls_pl demo app

- src/common/exec/subprocess.cc
Summary: This makes it easier to see which binary is actually erroring out.
Test Plan: N/A
> Update log message in container_runner to give more debug information

- bazel/container_images.bzl
- src/stirling/source_connectors/socket_tracer/testing/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/testing/container_images.h
- src/stirling/source_connectors/socket_tracer/testing/containers/BUILD.bazel
Summary: Remove the docker container fetch and replaces it with the bazel version. This should help us with a more hermetic
build and allow running tests where we don't have internet access.
Test Plan: Existing tests should pass.
> Move test container using product catalog service to bazel

- k8s/vizier/persistent_metadata/base/metadata_statefulset.yaml
Summary: The metadata stateful set was missing the multiarch tolerations, because we previously only added them to base.
Test Plan: Tested that kustomize build of `persistent_metadata` has the multiarch tolerations, and that kustomize build of `persistent_metadata/x86` only has x86 tolerations and `persistent_metadata/aarch64` only has arm64 tolerations.
> Add multiarch tolerations to metadata statefulset

- .bazelrc
- src/common/system/BUILD.bazel
- src/stirling/source_connectors/jvm_stats/BUILD.bazel
- src/stirling/utils/BUILD.bazel
Summary: Some tests use features that aren't supported by userspace qemu emulation, and will require full qemu kernel emulation to work.
This adds a tag that is filtered out by the aarch64_sysroot config, so that these tests never run in userspace qemu emulation.
Test Plan: Tested that the tests in question no longer get run by the `aarch64_sysroot` config.
> Disable tests for aarch64_sysroot config that don't work without full kernel emulation

- src/stirling/source_connectors/socket_tracer/BUILD.bazel
Summary: Enable the `grpc_trace_bpf_test` since the switch to podman stabilized the test
Before switching to `podman`, `grpc_trace_bpf_test` was failing with the [following error](https://phab.corp.pixielabs.ai/P323). Although the test has stabilized, we may still have a bug. We created #290 to track this because the switch to `podman` may have merely papered over the issue.
The test failures originate from the py grpc test case (see output below), which use docker unlike the other go grpc test cases. I tested a variety of commits and confirmed that 5fa450de3e6f8304f45eb018feb33f4a4bca5338 was the commit that fixes the flakiness.
Relevant Issues: #698
Test Plan: Ran the `grpc_trace_bpf` tests and bisected the failures until it passed on the podman commit
> Enable `grpc_trace_bpf_test` since switch to podman stabilized the test

- src/cloud/api/ptproxy/request_proxyer.go
Summary: The request proxyer is very sensitive to the state of downstream clusters. It is possible for this error to get triggered due to a single unhealthy cluster. We can add some of the cluster information to the error so we can determine if this error is occurring across many viziers, or just a single one.
Test Plan: This is just a log change and affects no functionality
> Add clusterID to requestproxyer error

- src/cloud/metrics/BUILD.bazel
- src/cloud/metrics/metrics_server.go
- src/cloud/shared/messages/BUILD.bazel
- src/cloud/shared/messages/nats_metrics.go
- src/cloud/vzconn/BUILD.bazel
- src/cloud/vzconn/vzconn_server.go
- src/cloud/vzmgr/BUILD.bazel
- src/cloud/vzmgr/vzmgr_server.go
Summary: The metrics server is known to heavily drop NATs messages due to a `slow consumer` error. We track the count of dropped messages for both vzconn and vzmgr, but don't track it for the metrics server yet. This PR adds the NATSErrorCounter so we can easily track nats errors in our cloud services.
Test Plan: Deploy to a testing cloud, ensure metrics server doesn't crash.
> Add NATSErrorCounter for tracking NATS errors

- src/stirling/source_connectors/socket_tracer/protocols/amqp/parse.cc
Summary: We fix an off-by-one error in `amqp/parse.cc` that was causing segfaults when parsing traffic for the same.
We also change the parse state to `kNeedsMoreData` (vs. `kInvalid` its previous state update) if the parser returns early when the buffer does not have enough data to read the entire payload.
Closes #942.
We opened #945 to track test coverage.
Test Plan: Ran `stirling_wrapper` both with and without the fix on a node with `px-sock-shop` deployed (with load testing up). Without the off-by-one fix, we wbserved segfaults matching the original issue reported. With the fix, observed no segfaults.
> Fix off by one error in `amqp/parse.cc`.

- src/common/testing/test_utils/container_runner.cc
- src/common/testing/test_utils/container_runner.h
Summary: Currently we can only read stdout from containers until the ready message. This allows
us to read the rest of the stdout, even for containers that have exited.
Test Plan: Test infrastrcture. Tested on QEMU environment on various tests.
> Allow fetching stdout from container_runner

- src/stirling/e2e_tests/stirling_wrapper_container_bpf_test.sh
Summary: Init is not needed here and was making podman in qemu unhappy.
Test Plan: Jenkins, no functional change.
> No need to call init on podman command

- bazel/pl_build_system.bzl
Summary: If kwargs are present then we pass them through. Allows us to access cc_test parameters without                                                                                                                                                                                  hardcoding the entire list.
Type of change: /kind test-inra
Test Plan: Jenkins, no functional change.
> Pass through kwargs on pl_cc_test rule

- src/vizier/services/agent/shared/manager/heartbeat.cc
- src/vizier/services/agent/shared/manager/heartbeat_test.cc
Summary: We've had user reports of PEMs failing to heartbeat to metadata because their heartbeat messages are too large for NATS. Upon closer inspection, it looks like the cmdline for some processes were very large (in one particular case, 20k+ characters--which can occur in Java processes).
This PR truncates the cmdline before we add it to the heartbeat update info. 4096 was chosen since that the maximum cmdline character limit in Linux. However, no further analyses were done to find the distribution of cmdline lengths.
Test Plan: Unit test
> Add truncation to process cmdline in agent heartbeats

- src/e2e_test/perf_tool/BUILD.bazel
- src/e2e_test/perf_tool/cmd/BUILD.bazel
- src/e2e_test/perf_tool/cmd/root.go
- src/e2e_test/perf_tool/main.go
Summary: Add root command for `perf_tool` that other commands will be a subcommand of.
This doesn't currently do anything and will only be used once other commands are added.
Test Plan: No functional changes, just boilerplate for future changes.
> [perf_tool] Add perf_tool root command

- src/e2e_test/perf_tool/pkg/bq/BUILD.bazel
- src/e2e_test/perf_tool/pkg/bq/table.go
Summary: The `bigquery.Schema` is required for some bigquery operations, so its useful to be able to access the `bigquery.Table` and `bigquery.Schema` in a unified way. This diff adds a thin wrapper around `bigquery.Table` that also stores the schema. In addition, this diff adds a unified way to create a bigquery Table/Schema pair (creating the gcloud resources if necessary). Currently, this is only used in `perf_tool` but we could consider pulling it up for our other services that rely on bigquery.
Test Plan: Tested the table (and dataset) creation with the `perf_tool run` command coming in future diffs.
> [perf_tool] Add thin wrapper around bigquery Table, to store the schema alongside it.

- go.mod
- src/e2e_test/protocol_loadtest/client/client.go
- src/e2e_test/protocol_loadtest/k8s/client/loadtest_config.yaml
- src/e2e_test/vizier/seq_tests/client/cmd/seq_http.go
- src/e2e_test/vizier/seq_tests/client/pkg/httpclient/BUILD.bazel
- src/e2e_test/vizier/seq_tests/client/pkg/httpclient/client.go
Summary: Add `target_rps` parameter to `protocol_loadtest`. This parameter sets a target for requests per second for the loadtest. It is only a limit on the RPS, so if the target RPS can't be achieved given the CPU/network of the cluster, the RPS will end up lower than the target.
This is useful to ensure consistency of the `protocol_loadtest` across different CPU loads. For example, without this change running the `protocol_loadtest` on an empty cluster would reach significantly higher RPS than running on a loaded cluster.
Also fixes a misnaming of one of the return values in the httpclient (`resp_size` -> `body_size`).
Test Plan: Tested a skaffold deployment of the `protocol_loadtest`, saw that it reached the target RPS (with roughly 10% margin).
> Add target_rps parameter to protocol_loadtest

- src/e2e_test/perf_tool/pkg/cluster/BUILD.bazel
- src/e2e_test/perf_tool/pkg/cluster/context.go
- src/e2e_test/perf_tool/pkg/cluster/provider.go
Summary: `cluster.Provider` specifies the interface for any providers of k8s clusters. This interface returns a `cluster.Context` pointing to a k8s cluster that matches the spec provided to `cluster.Provider.GetCluster`. The `cluster.Context` stores the kubeconfig, and allows consumers to either access the k8s golang API client connected to the given cluster or run commands with the given cluster using the `KUBECONFIG` environment variable. There are currently no implementations of `cluster.Provider` but future diffs will add a `local` provider for using your local kubeconfig, and a `gke` provider for creating clusters on GKE.
Test Plan: This just adds the interface, the implementations of the interface are tested in future diffs.
> [perf_tool] Add `cluster` package interface

- src/e2e_test/perf_tool/pkg/pixie/BUILD.bazel
- src/e2e_test/perf_tool/pkg/pixie/context.go
Summary: Adds a `pixie.Context` object for storing the credentials necessary to talk to Pixie Cloud and/or a Pixie vizier. Once a vizier is deployed using this context, it can set the cluster ID for that vizier on the context, so future uses of the context will use the correct cluster ID.
Test Plan: Tested that `RunPXCmd` works and can `deploy`, `auth login`, `delete`, etc, along with future changes.
> [perf_tool] Add `pixie.Context`

- src/e2e_test/perf_tool/experimentpb/experiment.proto
- src/e2e_test/perf_tool/pkg/deploy/BUILD.bazel
- src/e2e_test/perf_tool/pkg/deploy/checks/BUILD.bazel
- src/e2e_test/perf_tool/pkg/deploy/checks/common.go
- src/e2e_test/perf_tool/pkg/deploy/steps/BUILD.bazel
- src/e2e_test/perf_tool/pkg/deploy/steps/common.go
- src/e2e_test/perf_tool/pkg/deploy/workload.go
Summary: Adds interface to use `WorkloadSpec` to deploy a workload. Currently, there are no implementations of this interface.
Test Plan: No functional changes, just declaring an interface without any implementations of that interface.
> [perf_tool] Add interface for deploying workloads

- src/e2e_test/perf_tool/pkg/cluster/local/BUILD.bazel
- src/e2e_test/perf_tool/pkg/cluster/local/local.go
Summary: Adds a `ClusterProvider` implementation which ignores the `ClusterSpec`, and just uses whatever cluster is pointed to by your "local" kubeconfig. The kubeconfig used defaults to `$HOME/.kube/config`, unless the `KUBECONFIG` environment variable is set or `--kubeconfig` is set on the command line.
Test Plan: Tested that I can get a working `ClusterContext` for my local cluster from `GetCluster`.
> [perf_tool] Add `local.ClusterProvider`

- demos/sock-shop/sock-shop-loadgen.yaml
Summary: We change the container image for sock shop load test init from `alpine:3.6` to `gcr.io/pixie-oss/pixie-dev-public/curl:multiarch-7.87.0`. The new image comes with curl baked in. This avoids a potential problem where (for unknown reasons) the init pod fails because apk fails to install curl. Our curl image is created from `tools/docker/curl_image/Dockerfile`.
Test Plan: Tested locally by applying the sock shop demo yamls on my dev cluster. The new load test yaml worked (as expected).
> Use curl image for sock shop load test init.

- src/ui/package.json
- src/ui/yarn.lock
Summary: Bumps [vega](https://github.com/vega/vega) from 5.22.1 to 5.23.0 and [vega-typings](https://github.com/vega/vega-typings) from 0.19.3 to 0.23.0. Supercedes [#948](https://github.com/pixie-io/pixie/pull/948).
Relevant Issues: [GHSA-4vq7-882g-wcg4](https://github.com/advisories/GHSA-4vq7-882g-wcg4) and [GHSA-w5m3-xh75-mp55](https://github.com/advisories/GHSA-w5m3-xh75-mp55)
Test Plan: Existing unit and integration tests
> Bump Vega and its typings

- src/stirling/source_connectors/socket_tracer/redis_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/testing/container_images.h
Summary: Move the redis tests to use containers from bazel instead of pulling them
from the registry. This allows the tests to run without internet access and not be subject to
pull limits.
This changes also removes some output assertions because redis does not always produce message when running outside
of a terminal environemnt. The assertions aren't important for coverage since we check the test expectations as well.
Test Plan: existing tests should pass.
> Move the redis tests to use containers from bazel

- src/stirling/source_connectors/perf_profiler/perf_profiler_bpf_test.cc
Summary: Updates our use of taskset to improve compatibility with smaller versions from Busyboy.
In addition, we change the path to where it's found on more systems.
Test Plan: Existing tests should pass.
> Change taskset usage to improve compatibility

- src/e2e_test/perf_tool/pkg/bq/BUILD.bazel
- src/e2e_test/perf_tool/pkg/bq/batch_inserter.go
Summary: BigQuery `Inserter().Put` calls can be quite slow, so we don't want to run that for every single metric row we receive during an experiment.
This adds a utility that reads from a channel of arbitrary data, and batches it up before sending it to bigquery. This reduces the number of `Put` calls.
Test Plan: Tested that rows sent to the BatchInserter show up in bigquery. Also tested that if not enough rows are sent the timeout will trigger a push anyway.
> [perf_tool] Add BatchInserter for bigquery

- src/e2e_test/perf_tool/pkg/deploy/steps/BUILD.bazel
- src/e2e_test/perf_tool/pkg/deploy/steps/common.go
Summary: This PR implements deploying of a rendered YAML, using the `shared/k8s` package. This will be used by both the `skaffold` and `prerendered` `DeployStep`s.
It also implements a method to get the namespace the rendered yamls are deployed to.
Test Plan: Tested along with future changes, that rendered yamls get deployed as expected.
> [perf_tool/deploy] Implement rendered YAML deploy.

- src/e2e_test/perf_tool/experimentpb/experiment.pb.go
- src/e2e_test/perf_tool/experimentpb/experiment.proto
- src/e2e_test/perf_tool/pkg/deploy/BUILD.bazel
- src/e2e_test/perf_tool/pkg/deploy/workload.go
Summary: Adds an implementation of the `Workload` interface, which creates `DeploySteps` and `HealthChecks` based on the `WorkloadSpec`.
Currently, none of the deploy steps or healthchecks are implemented so this implementation won't do much yet, but all of the logic is there once those steps/checks can be added.
Test Plan: Tested along with future changes. Made sure all steps in the spec are deployed and all checks run.
> [perf_tool/deploy] Implement `Workload` interface

- src/cloud/plugin/controllers/server.go
Summary: We have seen cases where the `GetRetentionScripts` call errors. Unfortunately, the current logging/error doesn't give us enough information as to what is actually going wrong. This PR adds some additional logging so we can track more details about the error and see why some plugins get into this error state. Although very uncommon, it can prevent users from loading the Data Export page.
Test Plan: This just adds additional logging and has no functionality change.
> Add logging for pluginService getRetentionScripts error

- src/stirling/protocol_inference/data_collection.py
Summary: Update data_collection protocol inference script to work with cri cli tool
The previous implementation for the protocol inference data collection script relied on the docker cli. GKE clusters running k8s 1.24 and later do not support docker anymore, so this prevents the script from working on newer clusters. This change adds support for clusters using CRI (`crictl`) in addition to keeping the existing docker interface. The docker implementation had complicated parsing logic that was also simplified in this change.
Relevant Issues: #913 (script was used as part of the investigation)
Test Plan: Followed the instructions in the protocol inference [docs](src/stirling/protocol_inference/README.md) and verified pcaps were successfully captured
``` …
```
> Update data_collection protocol inference script to work with cri cli tool

- bazel/pl_workspace.bzl
Summary: This adds kernel deps for the QEMU testing build.
It currently only adds support for one kernel, but will plan to add the other kernels shortly.
Test Plan: jenkins, bazel builds.
> Add QEMU kernel deps

- src/e2e_test/perf_tool/pkg/metrics/BUILD.bazel
- src/e2e_test/perf_tool/pkg/metrics/recorder.go
- src/e2e_test/perf_tool/pkg/metrics/results.go
Summary: Adds the interface for creating a `metric.Recorder` based on a `MetricSpec`. Currently, there are no implementations of `metric.Recorder` so this is just a stub.
Test Plan: No functional changes here, just adding an interface that will be implemented in future PRs.
> [perf_tool] Add interface for recording metrics

- src/e2e_test/perf_tool/pkg/bq/BUILD.bazel
- src/e2e_test/perf_tool/pkg/bq/row.go
Summary: Add definitions for how both results and specs will be stored in bigquery. Specs and results will be stored in separate tables. The spec table is only written to on experiment success, so joining the spec and result tables on the ExperimentID will remove all result rows from failed experiments.
Test Plan: Tested that bigquery tables get created correctly based on the implicit schemas of these structs.
> [perf_tool] Add bigquery storage format definitions

- src/e2e_test/perf_tool/pkg/suites/BUILD.bazel
- src/e2e_test/perf_tool/pkg/suites/suites.go
Summary: Adds the interface for the `suites` package. This package defines a set of experiment "suites" which are essentially just a named set of `ExperimentSpecs`. For example, one of the suites will be the `main` suite which we'll run on each commit to `main`.
Test Plan: This is just an interface, will be tested along with the implementation.
> [perf_tool] Add `suites` package for defining experiment specs

- bazel/test_runners/qemu_with_kernel/exit_qemu_with_status/exit_qemu_with_status.c
Summary: QEMU already does the transformation for us so we don't need to scale the exit code.
Test Plan: Tested on qemu environment.
> Fix qemu exit program status code

- src/e2e_test/perf_tool/pkg/cluster/gke/BUILD.bazel
- src/e2e_test/perf_tool/pkg/cluster/gke/cluster_ops.go
- src/e2e_test/perf_tool/pkg/cluster/gke/kubeconfig.go
Summary: Implement operations for calling out to GKE to create, healthcheck, and delete a cluster. We use the `backoff` package to retry all the GKE operations, because they can often fail transiently.
Test Plan: A follow-up PR adds the subcommand `test_gke_cluster` to `perf_tool` which allows creating and deleting a cluster with the GKE cluster provider. I used that command to verify these operations work.
> [perf_tool/cluster] Implement GKE cluster operations.

- src/e2e_test/perf_tool/experimentpb/experiment.pb.go
- src/e2e_test/perf_tool/experimentpb/experiment.proto
- src/e2e_test/perf_tool/pkg/deploy/steps/BUILD.bazel
- src/e2e_test/perf_tool/pkg/deploy/steps/common.go
Summary: Allows patching rendered workload YAMLs via kustomize. This will be used by both skaffold, and prerendered deploy steps. This allows workloads to have parameters that can be easily changed in the spec without having to mess with the prerendered yamls, or the skaffold config.
Test Plan: Tested as part of broader changes, that the patching works as expected.
> [perf_tool/deploy] Allow patching rendered YAML before deploy

- src/e2e_test/perf_tool/pkg/run/BUILD.bazel
- src/e2e_test/perf_tool/pkg/run/run.go
Summary: I've split the experiment `Runner` implementation into many small diffs. This first one just calls `cluster.Provider` to get a cluster.
Test Plan: Tested along with all `Runner` implementation PRs to make sure the runner works as expected.
> [perf_tool/runner] Get cluster in runner

- src/e2e_test/perf_tool/experimentpb/experiment.pb.go
- src/e2e_test/perf_tool/experimentpb/experiment.proto
- src/e2e_test/perf_tool/pkg/metrics/BUILD.bazel
- src/e2e_test/perf_tool/pkg/metrics/pxl_script_recorder.go
- src/e2e_test/perf_tool/pkg/metrics/recorder.go
Summary: Implements a `metrics.Recorder` using a PxL script. The recorder runs the PxL script either as a streaming query or periodically.
The output is translated to metrics for bigquery using `PxLScriptOutputSpec`. Currently, there are no types of `PxLScriptOutputSpec`s defined, but future PRs will add handlers to take either single metrics from a column, or to count data loss based on a seq_id column.
Test Plan: Tested along with future PRs that both streaming a periodic queries work.
> [perf_tool/metrics] Implement PxL script based `metrics.Recorder`

- src/e2e_test/perf_tool/cmd/BUILD.bazel
- src/e2e_test/perf_tool/cmd/run.go
Summary: Add an initial implementation of the `run` subcommand of `perf_tool`. This doesn't yet create the `pixie.Context`, the `bq.Table`s, or the `cluster.Provider` necessary for running the experiment. Those are left for future PRs.
Test Plan: Tested along with future PRs that add the rest of the functionality to this `run` subcommand.
> [perf_tool] Add `run` subcommand

- src/e2e_test/perf_tool/pkg/suites/BUILD.bazel
- src/e2e_test/perf_tool/pkg/suites/clusters.go
Summary: Add default `ClusterSpec` to use for default experiments. For now we use 1 `n2-standard-4` node.
Test Plan: Tested along with other changes that the experiments work on a cluster of this spec.
> [perf_tool/suites] Add default cluster spec

- src/e2e_test/perf_tool/pkg/bq/BUILD.bazel
- src/e2e_test/perf_tool/pkg/bq/row.go
Summary: This adds a conversion utility from the `ResultRow` format in `metrics` to the row format that is stored in bigquery. This is useful so that the `metrics` package doesn't have to know anything about experiment IDs, and also can store its tags in the more logical `map[string]string` format, rather than a json encoded string.
Test Plan: Tested that the conversion works as part of broader changes.
> [perf_tool] Add converter from `metrics.ResultRow` to `bq.ResultRow`

- src/e2e_test/perf_tool/pkg/run/BUILD.bazel
- src/e2e_test/perf_tool/pkg/run/run.go
Summary: Another PR that adds to the implementation of the experiment runner. This PR adds preparation of workloads in parallel to getting a cluster. The workloads aren't yet deployed that will be in a future PR.
Test Plan: Tested all of the runner implementation as a whole.
> [perf_tool/runner] Prepare workloads

- src/e2e_test/perf_tool/cmd/BUILD.bazel
- src/e2e_test/perf_tool/cmd/test_gke_cluster.go
Summary: Adds a subcommand to `perf_tool` to test the `gke.ClusterProvider`.
Test Plan: Ran this `test_gke_cluster` subcommand and saw that `gke.ClusterProvider` creates clusters that conform to the spec given.
> [perf_tool] Add `test_gke_cluster` subcommand for testing GKE cluster creation

- src/e2e_test/perf_tool/cmd/BUILD.bazel
- src/e2e_test/perf_tool/cmd/run.go
Summary: Create bigquery tables in `run` subcommand. These tables are used by the runner to store experiment results and specs.
Test Plan: Tested that results end up in bigquery with the full implementation of the `run` subcommand.
> [perf_tool/run_cmd] Create bigquery tables

- src/e2e_test/perf_tool/pkg/run/BUILD.bazel
- src/e2e_test/perf_tool/pkg/run/run.go
Summary: Add sleeps based on the `RunSpec`. We sleep once after `vizier` is deployed and before the other workloads are deployed, as a burn-in period. We then sleep after the rest of the workloads are deployed for the duration of the rest of the experiment.
Test Plan: Tested with the full `Runner` implementation.
> [perf_tool/runner] Add sleeps

- src/e2e_test/perf_tool/cmd/test_gke_cluster.go
- src/e2e_test/perf_tool/pkg/cluster/gke/cluster_ops.go
- src/e2e_test/perf_tool/pkg/cluster/gke/gke.go
Summary: Add support to the `gke.ClusterProvider` for creating clusters with on demand subnetworks, rather than a preset subnetwork name.
Test Plan: Tested with `test_gke_cluster` that the `gke.ClusterProvider` can create a cluster with a dynamic subnetwork.
> [perf_tool/cluster] Allow dynamic subnetwork creation

- src/e2e_test/perf_tool/pkg/run/BUILD.bazel
- src/e2e_test/perf_tool/pkg/run/run.go
Summary: After a successful experiment run, the `Runner` now pushes a row to the bigquery `specs` table with the spec and experiment ID of the successful experiment.
Test Plan: Tested that the spec shows up in bigquery after a successful experiment.
> [perf_tool/runner] Push spec to bigquery on success

- src/stirling/protocol_inference/model/ruleset_basic.py
Summary: Fix mux protocol inference bug which causes certain frames to be labeled as 'unknown'
Our protocol inference will indefinitely attempt to identify a connection's protocol until it matches something other than `unknown`. Once the protocol is determined, its classification will not change for the lifetime of the connection. What this means is that it's possible for earlier payloads to be labeled as unknown as long as it doesn't match an incorrect protocol. Mux is a session layer protocol and therefore has a handshake process that occurs before the core frames are sent (TDispatch, RDispatch).
This change fixes a bug that prevented Tinit, Rinit, Rerr and RerrOld frames from being identified (initial frames in the [handshake process](https://github.com/pixie-io/pixie/blob/dd6545240ae39 …
> Fix mux protocol inference bug which causes certain frames to be labeled as 'unknown'

- src/stirling/protocol_inference/dataset_generation.py
- src/stirling/protocol_inference/model/metadata.py
Summary: Update protocol inference scripts to take into account tls packets
While investigating #913, I deployed stirling with verbose logging to identify which processes are contributors to the mux protocol confusion: kubelet, metrics-server, query broker, cloud connector ([P325](https://phab.corp.pixielabs.ai/P325)). After fixing the data collection script (#968) and using it on these pods, I realized that it didn't change the output of the protocol confusion matrix. This is because the dataset generation script ignores anything that is encrypted ([source](https://github.com/pixie-io/pixie/blob/9d16ad1f218beb2b01e879192859b4a0e99adfce/src/stirling/protocol_inference/dataset_generation.py#L179)). Essentially if `tshark` doesn't recognize the protocol as one of …
> Update protocol inference scripts to take into account tls packets

- src/e2e_test/perf_tool/pkg/suites/scripts/healthcheck/http_data_in_namespace.pxl
- src/e2e_test/perf_tool/pkg/suites/scripts/healthcheck/vizier.pxl
- src/e2e_test/perf_tool/pkg/suites/workloads.go
Summary: Add funcs for creating workload specs for common workloads such as Vizier, sock shop, and `protocol_loadtest`. Also adds pxl scripts to healthcheck those workloads.
The vizier healthcheck script, makes sure it sees as many nodes as there are in the cluster, and the http healthcheck script makes sure there is some http data being traced in the given namespace.
Test Plan: Tested that all of these workloads deploy successfully during experiments.
> [perf_tool/suites] Add workload specs for HTTP loadtest, Vizier, and sock shop workloads

- src/e2e_test/perf_tool/cmd/BUILD.bazel
- src/e2e_test/perf_tool/cmd/run.go
Summary: Allow using the `local.ClusterProvider` in the `run` command instead of a `gke.ClusterProvider`.
Test Plan: Tested that an experiment on a `local.ClusterProvider` works.
> [perf_tool/run_cmd] Allow using local cluster provider

- bazel/test_runners/qemu_with_kernel/run_qemu.sh
Summary: This adds a script that runs qemu with the correct set of
arguments based on the environment variables. It also captures and
transform the return code so upstream scripts don't have to worry about it.
Test Plan: Tested locally on qemu environment.
> Add script to launch qemu and capture status

- src/e2e_test/perf_tool/pkg/suites/BUILD.bazel
- src/e2e_test/perf_tool/pkg/suites/metrics.go
- src/e2e_test/perf_tool/pkg/suites/scripts/heap_size.pxl
- src/e2e_test/perf_tool/pkg/suites/scripts/http_data_loss.pxl
- src/e2e_test/perf_tool/pkg/suites/scripts/process_stats.pxl
Summary: Add specs for metric recorders to record cpu usage, heap size (including how much of the heap is used for table store), and data loss.
Test Plan: Tested that these metrics show up in bigquery and look reasonable.
> [perf_tool/suites] Add specs for cpu, heap, and data loss metrics

- src/e2e_test/perf_tool/cmd/BUILD.bazel
- src/e2e_test/perf_tool/cmd/run.go
Summary: Experiments sometimes fail because pixie becomes unhealthy during the course of the experiment or for other transient reasons. This adds a retry mechanism to the `run` command so that each experiment is retried multiple times if it fails.
Test Plan: Tested that failed experiments get retried.
> [perf_tool/run_cmd] Add experiment retries

- src/e2e_test/perf_tool/pkg/run/run.go
Summary: Send a metric row with the timestamp that workloads finish deploying and pass their healthchecks. This will be used to ignore results before this point in the datastudio views.
Test Plan: Tested that the workloads_deployed row shows up in bigquery.
> [perf_tool/runner] Send ResultRow with timestamp of when workloads are deployed

- src/e2e_test/perf_tool/cmd/BUILD.bazel
- src/e2e_test/perf_tool/cmd/run.go
Summary: Use the `suites` package to get experiment specs for the `run` command. Optionally, select just one experiment from the suite, or run all of the experiments in the suite.
Test Plan: Tested along with the `suites` package PRs that I can specify a `--suite` and it will run the corresponding experiments.
> [perf_tool/run_cmd] Get specs from `suites` package

- src/e2e_test/perf_tool/pkg/suites/BUILD.bazel
- src/e2e_test/perf_tool/pkg/suites/experiments.go
Summary: Adds experiment specs for running a sock shop experiment and arbitrary throughput http protocol_loadtest experiments. All these experiments have cpu and heap metrics, and the protocol loadtest experiments have a data loss metric as well.
Test Plan: Tested that both sock shop and the protocol loadtest experiments successfully complete.
> [perf_tool/suites] Add ExperimentSpecs for a sock shop and http loadtest experiments

- src/e2e_test/perf_tool/cmd/root.go
- src/e2e_test/perf_tool/cmd/run.go
Summary: Adds a wrapper around the `run` command, which ignores the first interrupt, starts to gracefully exit (cleaning up the cluster and other resources) on the second interrupt, and then ungracefully exits on the third interrupt.
Test Plan: Tested that two interrupts cause a graceful exit.
> [perf_tool/run_cmd] Gracefully exit after second interrrupt

- .github/workflows/cacher.yaml
- .github/workflows/get_image.yaml
- .github/workflows/pr_genfiles.yml
- .github/workflows/pr_linter.yml
Summary: Adds a `get_image.yaml` github action that can be reused by the various actions that need to look at `docker.properties` to get the image name for their subsequent job.
This reduces the need to repeat code for all the different actions that require our custom dev image.
Test Plan: Testing the actions with this PR.
> [actions] Refactor actions to reuse common `get-image` action

- src/e2e_test/perf_tool/pkg/suites/suites.go
Summary: We are currently only going to run perf nightly, so renaming the suite of experiments we will run to `nightly`.
Test Plan: No functional changes just a rename
> [perf_tool] Rename `main` suite to `nightly`

- src/cloud/metrics/BUILD.bazel
- src/cloud/metrics/metrics_server.go
Summary: Previous changes added a counter for NATS error messages in the metrics server. After taking a look at the metrics, I didn't see any data from the metrics server despite the NATS errors showing up in the logs. Turns out I forgot to register the metrics handler. This is unfortunately a little harder to test, since our testing/staging instances don't generate enough traffic to actually trigger the error.
Test Plan: Skaffold deploy to testing cloud and ensure things continue running as expected.
> Register metrics handler for metrics server

- src/stirling/protocol_inference/model/ruleset_basic.py
- src/stirling/source_connectors/socket_tracer/bcc_bpf/protocol_inference.h
- src/stirling/source_connectors/socket_tracer/protocols/mux/types.h
Summary: Enforce stricter checks on mux's TDispatch and RDispatch frames during protocol inference
This change addresses a large portion of the mux protocol misclassification identified in #913. As verified in #981, mux protocol traffic is very likely to be matched against tls traffic. This change addresses the 0.6% of traffic mislabelled in our test dataset.
Relevant Issues: #913
Test Plan: Performed the following tests outlined below
<p float="left">
</p>
> Enforce stricter checks on mux's TDispatch and RDispatch frames during protocol inference

- bazel/test_runners/qemu_with_kernel/launcher.sh
Summary: Setup BPF testing in qemu by doing the following steps:
1. Fixing environment variables so they are correct inside qemu.
2. Setting up qemu sandbox directory.
3. Copy the runfiles over.
4. Copy the test logs back.
5. Cleanup.
Test Plan: tested on qemu
> Add script that orchestrates qemu bpf testing

- k8s/cloud/base/metrics_deployment.yaml
Summary: Previous changes registered the metrics handler to the metrics server... But unfortunately we were still missing some annotations in the deployment YAML to make sure the prometheus metrics get propagated correctly.
Test Plan: Deploy with skaffold
> Add prometheus annotations to metrics-server YAML

- .bazelrc
- bazel/test_runners/BUILD.bazel
- bazel/test_runners/qemu_with_kernel/BUILD.bazel
- bazel/test_runners/qemu_with_kernel/runner.bzl
- src/stirling/source_connectors/perf_profiler/BUILD.bazel
Summary: This adds the bazel test runner for BPF tests using qemu. After this change
test should work by adding in
`bazel test -c opt --config=qemu-bpf`
The next step is adding in the ability to debug within the launched qemu environments.
Relevant Issues: #709.
Test Plan: Ran `bazel test -c opt --config=qemu-bpf //src/stirling/...`, There is one more change needed to fix tmpfs in some cases.
> QEMU test runner for bpf tests.

- src/ui/package.json
- src/ui/yarn.lock
Summary: Unpin the forced resolution for vega-functions so that it can be
upgraded.
Relevant Issues: GHSA-4vq7-882g-wcg4 and GHSA-w5m3-xh75-mp55
Test Plan: Existing unit tests should cover this.
> Unpin and upgrade vega-funtions

- src/e2e_test/perf_tool/cmd/BUILD.bazel
- src/e2e_test/perf_tool/cmd/github_matrix.go
Summary: This subcommand of `perf_tool` will print out all the different experiments in the given suites, in a JSON format that can be used in github actions `strategy.matrix` field.
Test Plan: Tested that the output format of the `github_matrix` command can be used by github actions.
> [perf_tool] Add `github_matrix` subcommand

- src/e2e_test/perf_tool/cmd/BUILD.bazel
- src/e2e_test/perf_tool/cmd/run.go
Summary: Prints out experiment_name, suite, and a link to a datastudio view for all successful experiment runs, in json format. This will be used by github actions to parse the output and get datastudio links. It's also useful for humans to associate suite/experiment name to a datastudio view. This diff also ensures that the run command errors on failed experiments.
Test Plan: Tested that the info is printed in valid json format, and that the datastudio links work.
> [perf_tool/run] Print info for successful experiments

- src/e2e_test/perf_tool/pkg/run/BUILD.bazel
- src/e2e_test/perf_tool/pkg/run/run.go
Summary: When workloads fail to prepare theres most likely an issue in the experiment spec, or the state of the workloads in the repo, so retrying will not help. This avoids the retries if preparing workloads fails.
Test Plan: Tested that the experiment is not retried if workload preparation fails.
> [perf_tool/run] Avoid retrying when workload prepartion fails

- bazel/pl_workspace.bzl
- bazel/test_runners/qemu_with_kernel/BUILD.bazel
- bazel/test_runners/qemu_with_kernel/runner.bzl
Summary: This allows kernel version to be passed via a flag. There is a set list of kernels that can be executed and they are built using
//tools/docker/kernel_builder.
Test Plan: `bazel test -c opt --config=qemu-bpf  --cache_test_results=no --remote_download_outputs=all //src/stirling/source_connectors/socket_tracer:redis_trace_bpf_test --test_output=streamed --//bazel/test_runners/qemu_with_kernel:kernel_version=4.14.304`
`--//bazel/test_runners/qemu_with_kernel:kernel_version` can be set to different values. There is a bug with the 4.14.304 kernel config that'll be fixed next, but the others are working.
> Allow kernel version to be configurable for qemu

- src/ui/src/containers/live/breadcrumbs.tsx
- src/ui/src/utils/string-search-test.ts
- src/ui/src/utils/string-search.ts
Summary: There were still a few scenarios where the filtering was a bit too aggressive, or the sorting of results didn't make much sense. This should fix quite a few of them.
Test Plan: Try all of the following searches in the `script` breadcrumb, and a few of them in the Command Palette as well.
They should both get similar results...
- The search `exec` should now find `bpftrace/EXEC_snoop` before it finds weaker matches
- The search `pod` should now greatly prefer scripts that have the string `pod` in them, even over shorter-named scripts that have vaguely similar spelling.
- The search `px/ace` should now do the same: `PX/namespACEs` should now be a stronger match than `PX/nodE`.
- And the same for `px/stat`.
- Finally, most searches should keep more results than before (further past …
> Improve Command Palette and Breadcrumb sorting

- .github/workflows/perf.yaml
- .github/workflows/perf_common.yaml
Summary: Adds a github action to run performance evaluations. The github action can be triggered three ways:
- automatically each night
- manually through github's workflow dispatch
- on PRs by having an admin comment `/perf <suites> <tags>`
Test Plan: See #1037. I tested this by making a pull_request trigger for the action and testing on a separate pull request. We don't actually want that trigger so I removed it here.
> [perf_tool] Add github action to run perf_tool

- src/ui/src/components/command-palette/command-text-field.tsx
Summary: Without this change, the browser already tries to scroll the selected option into view. However, due to `position: sticky`, there's a header that can obscure it. To account for that header, we use `scroll-margin-top` and force the browser to try again with `scrollIntoView`, which accounts for that property.
Fixes #1045
Relevant Issues: #1045
Test Plan: Open the Command Palette. Enter a query like script:. Using the arrow keys, scroll down a couple of pages, then scroll back up the same way. When moving to an option that's above the current scroll view, it should now fully scroll that option into view.
> Always scroll hovered item into view in Command Palette

- .github/workflows/perf.yaml
Summary: Used a hash that didn't have `dist/*` files, this fixes it by using a release hash.
Test Plan: Checked that this hash has the `dist/*` files.
> Use release hash for xt0rted/slash-command-action

- tools/docker/Makefile
Summary: This write out the appropriate lines that can be directly copy pasted in the bazel file.
Test Plan: `make upload_kernel_build`
> Update makefile for kernel targets to write out bzl file contents

- .bazelrc
Summary: Tmpfs does not work with qemu because we can't use tmpfs to host a plan9 volume right now.
Test Plan: This works without changing sandbox tmpfs setting:
```bazel test -c opt --config=qemu-bpf  --cache_test_results=no --remote_download_outputs=all //src/stirling/source_connectors/socket_tracer:redis_trace_bpf_test --test_output=streamed --//bazel/test_runners/qemu_with_kernel:kernel_version=latest```
The rest of the test should pass in Jenkins. #ci:bpf-build.
> Exempt qemu from tmpfs sandbox

- bazel/pl_qemu_kernels.bzl
- tools/docker/Makefile
Summary: Updates the kernel build to latest config. Makefile to maintain consistent timestamps.
Test Plan: Tested that the 4.14 kernel now functions without giving an l5 page table error.
```bazel test -c opt --config=qemu-bpf  --cache_test_results=no --remote_download_outputs=all //src/stirling/source_connectors/socket_tracer:redis_trace_bpf_test --test_output=streamed --//bazel/test_runners/qemu_with_kernel:kernel_version=oldest```
> Update kernels with latest config for qemu tests

- .bazelrc
Summary: There was a typo in the config name.
Test Plan: `bazel test //...`
> Fix typo in sandbox build config

- ci/bazel_build_deps.sh
Summary: We implicitly ignored `bazel cquery` failures in `ci/bazel_build_deps.sh`, causing issues with .bazelrc configs to run 0 tests instead of failing when running `ci/bazel_build_deps.sh`.
This adds `set -o pipefail` so that piped commands still cause errors.
Test Plan: Tested that `./ci/bazel_build_deps.sh` returns an exit code when there's an error in the .bazelrc config.
> [ci/bazel_build_deps] Fail if any piped command fails

- bazel/pl_workspace.bzl
Summary: We appear to be getting read timeouts for busybox.net on Jenkins, so I moved to using a mirror of the busybox binary on our own gcs.
Test Plan: Tested that the binary has the same sha as before when downloaded from the mirror.
> Use gcs mirror for busybox

- src/ui/src/components/command-palette/command-palette.tsx
Summary: When opening the Command Palette while working on the Scratch Pad script, it was failing to quote the space in the name (resulting in an invalid command).
This makes it use an existing utility function to correctly quote both the script name and any arguments that need it, when opening the Command Palette in the live view.
Test Plan: Open the Command Palette when editing the Scratch Pad script or a script whose arg values include a character that requires quoting.
> Command Palette: Fix missing quote logic

- bazel/test_runners/qemu_with_kernel/launcher.sh
Summary: If files already exist (due to a previous flaky run) we fail to copy the new test results. This makes
the copy forced to make sure it's overriden.
Test Plan: bazel test, jenkins
> Force copy the files in qemu runner

- src/stirling/source_connectors/socket_tracer/BUILD.bazel
Summary: This test currently fails under qemu and needs to be debugged.
Test Plan: N/A
> Disable kafka_bpf_test under qemu

- src/stirling/source_connectors/socket_tracer/protocols/http/parse.cc
Summary: Changing the value of `max_body_bytes` by setting the `PL_STIRLING_MAX_BODY_BYTES` does not allow for sizes over `http_body_limit_bytes` for the body of ebpf traffic captured in the http setting. I've added an environment variable for setting `http_body_limit_bytes` using `PX_STIRLING_MAX_BODY_BYTES`.
Test Plan: Deployed Stirling in a self-hosted environment with a variety of values.
Signed-off-as: AdityaAtulTewari <adityaatewari@gmail.com>
> Make http_body_limit_bytes able to be set by environment variable

- src/stirling/source_connectors/perf_profiler/perf_profiler_bpf_test.cc
Summary: In the perf profiler bpf test, we add a tmpfs volume mount to the podman cmd line. This fixes a test flake where the perf profiler refuses to attach the Java symbolization agent because it cannot found enough tmpfs capacity.
Test Plan: Existing tests pass.
> Add a tmpfs volume mount for Java containers in the perf profiler test.

- bazel/container_images.bzl
- src/stirling/source_connectors/socket_tracer/testing/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/testing/container_images.h
- src/stirling/source_connectors/socket_tracer/testing/containers/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/testing/containers/ssl/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/testing/containers/ssl/index.html
Summary: Add nginx container image with OpenSSL v3 for future tls tracing test
The tls tracing method developed for #692 will support dynamically linked OpenSSL v3 in addition to BoringSSL. In order to validate that the new tracing method works (in addition to its feature flag), I wanted to a test case that would prove the new implementation is in use.
The mirrored upstream nginx image added in this PR has a different `/index.html` compared to our existing images. This change adds a container layer containing the expected `index.html` so that the future test assertions can remain the same.
Test Plan: Verified that the resulting nginx container returns the same html file as our …
> Add nginx container image with OpenSSL v3 for future tls tracing test

- bazel/test_runners/qemu_with_kernel/exit_qemu_with_status/exit_qemu_with_status.c
- bazel/test_runners/qemu_with_kernel/run_qemu.sh
Summary: The test runner was overloading the exit codes so we can't differentiate qemu errors from test errors.
This makes the test errors return values offset by 128 so we assume that errors > 128 are test errors.
Test Plan: `bazel test -c opt --config=qemu-bpf  --cache_test_results=no --remote_download_outputs=all //src/stirling/source_connectors/socket_tracer:redis_trace_bpf_test --test_output=streamed`
Also tested with qemu failing to start.
> Fix overloaded exit codes with qemu test runner

- src/stirling/source_connectors/perf_profiler/perf_profiler_bpf_test.cc
Summary: We reduce the perf profiler test run time from 30 sec. to 10 sec. per test case.
Test Plan: Ran locally with `--runs_per_test 16` and all tests passed.
> Reduce perf profiler test run time.

- k8s/cloud/overlays/plugin_job/plugin_job.yaml
- src/cloud/plugin/load_db/BUILD.bazel
Summary: Build changes broke the plugin updater job. This PR updates the build configs/YAMLs for the plugin updater job to match the artifact updater job, since they both require `busybox` to set a TRAP.
Relevant Issues: #1084
Test Plan: Skaffold deploy cloud and verify plugin job runs
> Fix "`GLIBC_2.32' not found" error in plugin updater job

- src/pixie_cli/pkg/utils/checks.go
- src/utils/shared/k8s/BUILD.bazel
- src/utils/shared/k8s/kubectl.go
support kubeconfig options when using kubectl command
Summary: When deploy using  `px --kubeconfig THE_KUBE_FILE deploy`,
it failed with error `✕    Kubectl > 1.10.0 is present  ERR: exit status 1`.
And I found the px cli has the `--kubeconfig` option, but the internal
kubectl command didn't respect it.
Test Plan: Run `px deploy` with `--kubeconfig` option should work without
problem.
> support kubeconfig options when using kubectl command

- src/shared/artifacts/manifest/BUILD.bazel
- src/shared/artifacts/manifest/json.go
- src/shared/artifacts/manifest/manifest.go
- src/shared/artifacts/manifest/manifest_test.go
- src/shared/artifacts/manifest/sorted.go
Summary: This PR adds `ArtifactManifest` which is a golang representation of an artifact manifest file. In the future, the artifact tracker will pull a manifest file from GCS, decode it into this type, and then query for artifacts from `ArtifactManifest` directly. This PR adds support for json serialization/deserialization for artifact manifests. Internally, the artifacts in the manifest are stored in version sorted order, such that newer versions are first. This will enable faster version-ordered queries of manifests in the future.
Test Plan: Added tests for `ArtifactManifest` serialization/deserialization.
> [artifact manifests] Add `ArtifactManifest` type to represent a manifest file

- src/utils/artifacts/manifest_updater/BUILD.bazel
- src/utils/artifacts/manifest_updater/main.go
Summary: Adds a tool to pull a current manifest from GCS, merge in some updates and then reupload it. This tool checks that the manifest hasn't changed between reading and writing the new one, so that multiple people can run the tool simulataneously without creating invalid manifests.
Test Plan: Tested that the updater tool uploads new manifests with any changes in the updates file its given.
> [artifact manifests] Add `manifest_updater` tool for updating artifact manifest files in GCS

- .github/workflows/get_image.yaml
Summary: TSIA
Test Plan: The workflow should continue to run without issues.
> Restrict GITHUB_TOKEN permissions for get_image workflow

- src/shared/artifacts/manifest/BUILD.bazel
- src/shared/artifacts/manifest/poller.go
Summary: Adds `manifest.Poller` to poll for new changes to a GCS manifest. The poller checks the GCS metadata to see if the MD5 hash has changed, and only downloads the manifest if the hash has changed.
When the manifest changes the poller parses the manifest from GCS and calls the callback given with the new manifest.
Test Plan: Tested that the poller only calls the callback on new changes to the manifest.
> [artifact manifests] Add manifest poller to poll for manifest changes

- .github/workflows/pr_3p_deps.yaml
Summary: Use a github provided action to check third party
deps and streamline license checks.
Test Plan: Check the action results from this PR.
> Add check for third_party deps

- src/shared/artifacts/manifest/BUILD.bazel
- src/shared/artifacts/manifest/manifest_test.go
- src/shared/artifacts/manifest/query.go
Summary: Adds `GetArtifact` and `ListArtifacts` methods to the `ArtifactManifest`. `GetArtifact` returns an artifact with the given name and version. `ListArtifacts` returns a list of artifacts of the requested size, in version-sorted order with the newest versions first. `ListArtifacts` accepts filters as well to eg filter out prereleases from the list, or filter to only artifacts with a given artifact type available.
Test Plan: Added tests for `GetArtifact` and `ListArtifacts`, also tested end-to-end as part of a change to artifact tracker.
> [artifact manifests] Allow querying `ArtifactManifest` for artifacts

- .github/workflows/perf.yaml
Summary: TSIA
Test Plan: Perf eval workflows should continue to work.
> Restrict GITHUB_TOKEN permissions for perf eval workflow

- ci/update_artifact_manifest.sh
Summary: Adds script to run `manifest_updater` using the `VERSIONS.json` file to update the current manifest. This script will be run as part of each of the release processes.
Test Plan: Tested that the script properly updates the manifest file on GCS with any changes from the VERSIONS.json file.
> [artifact manifests] Add script for updating artifact manifest file

- k8s/devinfra/action-runners/README.md
- k8s/devinfra/action-runners/bb_bazelrc_secret.yaml
- k8s/devinfra/action-runners/runners/base/autoscaler.yaml
- k8s/devinfra/action-runners/runners/base/deployment.yaml
- k8s/devinfra/action-runners/runners/base/kustomization.yaml
- k8s/devinfra/action-runners/runners/base/name_reference.yaml
- k8s/devinfra/action-runners/runners/kustomization.yaml
- k8s/devinfra/action-runners/runners/kvm/deployment.yaml
- k8s/devinfra/action-runners/runners/kvm/kustomization.yaml
- k8s/devinfra/action-runners/runners/nokvm/deployment.yaml
- k8s/devinfra/action-runners/runners/nokvm/kustomization.yaml
- k8s/devinfra/action-runners/runners/shared/docker_config.yaml
- k8s/devinfra/action-runners/runners/shared/kustomization.yaml
Summary: Adds a new k8s github action runner with KVM support. Also adds autoscalers for the runners. The current autoscaler is poll-based, if this becomes an issue we can switch to a push based autoscaler with webhooks, but its significantly more effort.
Test Plan: Tested that `qemu` based BPF tests can run on the new kvm runners. Also tested that the autoscaler works in a reasonable time frame.
> [action-runners] Add k8s action runner with KVM support

- go_deps.bzl
Summary: `gazelle` wasn't run on a previous diff.
Test Plan: Ran `gazelle`
> [gazelle] Fix go_deps.bzl

- .github/workflows/pr_genfiles.yml
Summary: Run `make gazelle` and `make go-setup` on PRs and fail if there are any changes as a result.
Test Plan: Testing with this PR to see if a change to `go.mod` causes a check failure.
> [actions] Run gazelle and go mod tidy on PRs

- src/ui/src/components/command-palette/command-providers.tsx
- src/ui/src/components/command-palette/providers/script/empty-input-provider.tsx
- src/ui/src/components/command-palette/providers/script/script-provider.tsx
Summary: It wasn't presenting the right type of icon or description before, nor the Scratch Pad.
Before...
After...
Test Plan: Try the empty input in the Command Palette.
> Match EmptyInputProvider style to other providers

- k8s/vizier/base/metadata_role.yaml
- k8s/vizier/bootstrap/cloud_connector_role.yaml
- src/shared/services/election/election.go
Summary: There have been multiple vizier releases since we
introduced Lease locks. This means that vizier installs should
be transitioned over and we no longer need endpoint locks. So
remove it.
Test Plan: Deploy a prod vizier and skaffold a dev vizier afterwards.
> Remove endpoint lock

- k8s/cloud/overlays/exposed_services_nginx/cloud_ingress_grpcs.yaml
Summary: We have observed that the existing gRPC ingress is not functioning properly for any API call made for the `/px.cloudapi.*` path. This issue is due to the problem with the nginx ingress, where it sets the $HOST header of the request to upstream_balancer. This issue has been reported and documented in https://github.com/kubernetes/ingress-nginx/issues/8843.
As a result, when the traffic hits the cloud proxy service, it returns a 404 error since the request is picked up from the [default_server](https://github.com/pixie-io/pixie/blob/main/src/cloud/proxy/nginx.conf#L78) instead of [@PL_DOMAIN_NAME@](https://github.com/pixie-io/pixie/blob/main/src/cloud/proxy/nginx.conf#L101) server. To resolve this issue, we have set the ingress controller to direct the route to traffic to …
> Fixed a ingress issue which prevented `px.cloudapi` calls

- bazel/external/ubuntu_packages/debs.json
- bazel/external/ubuntu_packages/packages.bzl
Summary: This upgrades all debs to latest avilable versions.
The addresses a CVE in our published images.
Test Plan: All RCs should continue to work as expected.
> Upgrade debs used in images

- .github/workflows/release.yaml
Summary: Adds github actions to build and push vizier and operator releases, whenever a release tag is pushed to the repo. The release builds also update the artifact manifest in GCS with the new artifact versions.
Test Plan: Built vizier and operator releases on my own fork of the repo. Deployed the new artifact tracker in a self-hosted cloud, and was able to deploy vizier with my new operator and vizier prerelease versions.
> [actions] Add github action for building vizier and operator releases

- third_party/BUILD.bazel
Summary: Building libarchive on a system that has bzlib installed
currently fails since CMake detects it and enables it but the
sysroot doesn't include bzlib. Since we don't rely on bzip support,
lets explicitly disable it in the CMAKE config.
Test Plan: libarchive now builds successfully on my machine
> Disable BZip2 when building libarchive

- .github/workflows/codeql.yaml
Summary: CodeQL go analysis happens to be using some older version
of the toolchain. This fixes the same.
Test Plan: Check the codeql go run after this lands.
> Download a specific go toolchain for the codeql workflow

- src/stirling/source_connectors/socket_tracer/testing/containers/thriftmux/BUILD.bazel
Summary: The netty_tls test started failing on main a few commits
ago. The failure is due to libcrypt not finding GLIBC_2.36.
The test last passed at 007a542 and first failed at f6821ed.
The `thriftmux_base` depends on `libcrypt1` and `libc6` but was not
explicitly including `libc6` as a deb dependency. Before 59a945e the
version of `libcrypt1` installed needed `GLIBC_2.25` and the base image
glibc was `GLIBC_2.30`. Now `libcrpyt1` needs `GLIBC_2.36` but the
base image is the same. So we need to explicitly include the newer deb
as a dependency to satisfy the requirement.
Test Plan: Run the netty_tls test locally, it passes now.
> Fix netty_tls test

- ci/bpf/00_create_instance.sh
Summary: In #1149 I saw the test instances running out of disk space.
I manually watched the disk as the tests were running and saw disk
usage peak north of 100Gi. This new limit should be enough for now
and leave us room for growth.
Test Plan: Run BPF tests on #1149 with additional space. They pass.
> Increase disk size for BPF test instances

- bazel/test_runners/qemu_with_kernel/launcher.sh
Summary: The qemu test runner wasn't updating the runfile manifests with the paths inside of the qemu sandbox, leading to errors trying to load docker containers. This rewrites the manifest files inside of the qemu sandbox to use `/test_fs` based paths.
Test Plan: Tested that `go_tls_trace_bpf_test --config=qemu-bpf` works inside of a docker container now, where before it didn't
> [qemu test runner] Fix runfile manifests

- WORKSPACE
Summary: The presense of `incompatible_remove_rule_name_parameter` in
our bazelrc means that the repo doesn't build with bazel 5.
So update the check to indicate the same.
Test Plan: Builds still work with bazel 6.
> Update the bazel version check

- src/ui/src/configurables/base/create-org-extras.tsx
- src/ui/src/pages/setup/setup.tsx
Summary: Allows custom tasks both immediately before and after the creation of a new org. Also allows providing extra UI on the Create Org page to configure these tasks, and marking the overall form as valid/invalid accordingly.
Test Plan: Org creation should not behave any differently by default; the base implementation is a no-op.
> Allow custom tasks during Create Org

- .github/dependabot.yml
Summary: This will let dependabot auto create security
fixes but not version bumps for the various deps we have.
Test Plan: Wait for the next dependabot run after this lands.
> Update dependabot file to track all possible deps

- go.mod
- go.sum
- go_deps.bzl
Summary: Upgrade this test dep to address some CVEs.
Relevant Issues: GHSA-232p-vwff-86mp, GHSA-33pg-m6jh-5237 and GHSA-6wrf-mxfj-pf5p
Test Plan: All existing tests continue to pass.
> Upgrade moby test dep for golang

- .github/workflows/codeql.yaml
- Makefile
Summary: The golang codeql autobuilder invokes the top level makefile without any arguments. This
means that we run `bazel clean` by default. Instead add a `make go` command that runs a simple go
compilation. Also skip the use of our devimage since we need to install golang on the running via an
action anyway.
Test Plan: Ensured that the codeql analyses still work.
> Update and cleanup codeql action

- ci/github/bazelrc
Summary: Set role to not `CI` since releaase or scan builds shouldn't
affect the test matrix. Also set visiblity to `PUBLIC`.
Test Plan: Check Buildbuddy for release scans and trivy runs after this lands.
> Update github bazelrc

- src/pixie_cli/pkg/cmd/deploy.go
Summary: `px deploy` currently doesn't count nodes with `NoSchedule` taints during its deploy process. This means that if the cluster only has nodes with `NoSchedule` then the deploy won't proceed. PEM has a toleration for `NoSchedule` taints so this seems unnecessary.
Test Plan: Tested that `px deploy` works on a cluster where all nodes have a `NoSchedule` taint.
> [CLI] Count nodes with NoSchedule taints in cluster node count

- go.mod
Summary: We rename and import docker/docker as moby/moby but the dependabot
tooling seems to not accurately detect that the replaced version is new enough
to address the open CVEs. So upgrade the docker/docker import too.
Test Plan: This change is a no-op.
> Upgrade docker dep in go.mod

- .github/workflows/trivy_fs.yaml
- .github/workflows/trivy_images.yaml
- k8s/cloud/BUILD.bazel
Summary: Add trivy based scanning for our repo and our built images.
Repo scanning is done on every commit, PR and nightly.
Image scanning will be done nightly (and on releases?)
Test Plan: Check github actions output from this PR.
> Add trivy scanning

- k8s/cloud/BUILD.bazel
- skaffold/skaffold_cloud.yaml
- src/cloud/proxy/BUILD.bazel
Summary: The proxy image had two versions, but the dev image has never been used
as far as I can tell. Remove it to reduce maintenance burden.
Test Plan: All builds and tests work. skaffold cloud works.
> Remove unused proxy_image

- .github/workflows/release.yaml
- ci/operator_build_release.sh
- ci/vizier_build_release.sh
- k8s/cloud/base/artifact_config.yaml
- src/cloud/artifact_tracker/artifact_tracker_server.go
- src/cloud/artifact_tracker/controllers/server.go
- src/cloud/artifact_tracker/controllers/server_test.go
Summary: Switches vizier and operator RCs to use the same bucket as official releases. Updates the `artifact_tracker` to not attempt to sign RC download links.
Test Plan: Existing tests pass. Will deploy to testing to make sure it works.
> [artifacts] Use the same bucket for RCs as official releases

- k8s/cloud/dev/auth_deployment_patch.yaml
- k8s/cloud/dev/kustomization.yaml
Summary: The dev cloud setup still uses auth0 and doesn't work unless these
secrets are passed through.
Test Plan: skaffolding a dev cloud works now.
> Fix skaffold dev cloud deployment

- bazel/container_images.bzl
- src/cloud/proxy/BUILD.bazel
- src/cloud/proxy/entrypoint.sh
Summary: The debian based openresty image has a lot of open CVEs due to all
the default packages and libs included in the base distro. Switch to an alpine
based image effectively lets us close all of these issues.
The alpine image also includes sed which is used by our entrypoint script but
is missing bash, so we switch to using sh instead. Ensured that the entrypoint
still behaves as expected.
Test Plan: Deployed a skaffold dev cloud. Ensured that the proxy service still
works and the UI loads and works as expected.
> Upgrade openresty and switch to an alpine based image

- src/shared/services/pg/pg.go
Summary: Update the log to ensure that the postgres password is
not logged.
Test Plan: skaffold a dev cloud and check the logs for any pod
that talks to postgres
> Update postgres db setup log

- src/ui/src/components/auth/signup-marcom.tsx
- src/ui/src/components/autocomplete/autocomplete.tsx
- src/ui/src/components/breadcrumbs/__snapshots__/breadcrumbs-test.tsx.snap
- src/ui/src/components/breadcrumbs/breadcrumbs.tsx
- src/ui/src/components/command-palette/command-text-field.tsx
- src/ui/src/components/data-table/data-table.tsx
- src/ui/src/components/mui-theme.tsx
- src/ui/src/components/snackbar/snackbar.tsx
- src/ui/src/components/split-pane/split-pane.tsx
- src/ui/src/containers/App/topbar.tsx
- src/ui/src/containers/editor/editor.tsx
- src/ui/src/containers/live-data-table/data-table-details.tsx
- src/ui/src/containers/live/convert-to-vega-spec/flamegraph.ts
- src/ui/src/containers/live/shortcuts.tsx
Summary: Simplifies to fewer colors, but still very similar to the previous ones.
Footer and `nullish` strings in table details are the only ones that are easy to notice changed; they're more muted now.
The light theme and graph colors will get their own changes when design updates are ready for them.
Before (most noticeable difference selected)
After
Test Plan: Look at the live and admin views side-by-side with and without the change.
Light mode should be unaffected.
Graphs should be unaffected.
The footer and `nullish` fields in table details are a bit more muted.
The blue in table details is almost imperceptibly different.
A few of the neutral grays are almost imperceptibly different.
> Update dark color palette

- src/stirling/source_connectors/perf_profiler/java/agent/BUILD.bazel
- src/stirling/source_connectors/perf_profiler/java/agent/agent.c
- src/stirling/source_connectors/perf_profiler/java/agent/raw_symbol_update.h
Summary: We would like to build the java agent for ARM as well as x86. We could make a fully-featured musl c++ toolchain. However, that's a lot of work and its much easier to just build musl libc with bazel and statically link it. This won't work with C++ though, because we wont have a compatible libc++. The java agent doesn't really make use of many c++ features beyond std::mutex and std::string, which are easily replaced with C versions. This PR converts the java agent to be C compatible, removing its uses of c++ features.
Relevant Issues: #891
Test Plan: Tested that java symbols still show up in the flamegraph with this new version of the agent.
> [java/agent] Make agent compatible with C.

- k8s/devinfra/jenkins-oss/values.yaml
Summary: We are adding our release builds to GH actions. As a result, we don't need this operator release job in jenkins.px.dev, since it's been completely unused.
Test Plan: Deploy to Jenkins
> Cleanup operator release job from Jenkins

- src/stirling/source_connectors/perf_profiler/bcc_bpf/profiler.c
- src/stirling/source_connectors/perf_profiler/bcc_bpf_intf/stack_event.h
- src/stirling/source_connectors/perf_profiler/perf_profile_connector.cc
- src/stirling/source_connectors/perf_profiler/perf_profile_connector.h
Summary: Fix perf profiler bug causing higher BPF map utilization and add `DCHECK` and metrics for error conditions
The perf profiler connector (and soon the socket trace connector - #1161) record error conditions in a BPF map. While the perf profiler has instrumented this value for a while, we haven't leveraged using this data in anyway. This change `DCHECK`s the error condition in addition to adding prometheus metrics.
This `DCHECK` caught a bug in our map switching logic. The perf profiler has an "A" and "B" map and alternates between them. Prior to this change we were using the A map exclusively since our variable for B was accidentally pointing to A ([source](https://github.com/pixie-io/pixie/blob/cf071f3608de5500213cef05ddb1bba88544ea66/src/stirling/source_connectors/perf_profiler/bc …
> Fix perf profiler bug causing higher BPF map utilization and add `DCHECK` and metrics for error conditions

- .github/workflows/perf.yaml
Summary: Fix permissions issues for running perf-eval on `/perf` comments on PRs.
Test Plan: Checked that the repo I tested this on had the permissions I updated here.
> [perf-eval] Fix permissions for issue_comment perf eval

- src/stirling/source_connectors/socket_tracer/bcc_bpf/openssl_trace.c
- src/stirling/source_connectors/socket_tracer/bcc_bpf/socket_trace.c
- src/stirling/source_connectors/socket_tracer/bcc_bpf_intf/socket_trace.h
- src/stirling/source_connectors/socket_tracer/openssl_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.h
Summary: Instrument OpenSSL tracing to detect validity of assumptions for new tls tracing method
After discussing #1123 with @oazizi000 and @etep, we decided that invest in stronger validation that the assumptions for that PR and our future tls tracing are valid. Instead of relying on struct offsets of user space data structures, the new tracing method will access a connection's socket fd from the underlying socket syscalls during `SSL_write` / `SSL_read` calls.
This technique should only be compatible with "BIO native" OpenSSL use cases, which are the OpenSSL use cases Pixie supports today. BIO native means that a compatible application uses a [BIO](https://wiki.openssl.org/index.php/BIO) provided by OpenSSL (via [SSL_set_fd](https://www.openssl.org/docs/manmaster/man3/SSL_set_fd.html)) …
> Instrument OpenSSL tracing to detect validity of assumptions for new tls tracing method

- src/cloud/config_manager/controllers/vizier_feature_flags.go
Summary: Add `access-tls-socket-fd-via-syscall` feature flag to cloud config manager
This feature flag will be used to opt internal clusters into the new tls tracing implementation developed in #1120. We may want a more sophisticated toggle for gradually opting in more clusters, but this will suffice for the initial set of testing (validating some hand picked clusters).
> Add `access-tls-socket-fd-via-syscall` feature flag to cloud config manager

- .github/workflows/perf.yaml
- .github/workflows/perf_common.yaml
Summary: Before, if a single perf experiment failed it would immediately cancel the other experiments and not report results for any suceeding experiments. Now it will continue to run the other experiments and report successful experiments in the PR comment.
Test Plan: N/A
> [perf-eval] Continue even if one of the perf evals fails

- src/stirling/core/data_tables.h
- src/stirling/core/unit_connector.h
- src/stirling/e2e_tests/bpf_map_leak_bpf_test.cc
- src/stirling/source_connectors/jvm_stats/jvm_stats_connector_test.cc
- src/stirling/source_connectors/proc_exit/proc_exit_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector_benchmark.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector_test.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_protocols_test.cc
- src/stirling/source_connectors/socket_tracer/testing/socket_trace_bpf_test_fixture.h
- src/stirling/testing/common.h
Summary: We add class `UnitConnector` to wrap and provide an API to a source connector. This wrapper provides the necessary logic to drive a source connector in isolation (i.e. without using `stirling.cc`). It will be used for test fixtures (e.g. in the socket tracer and perf profiler) and for individual binaries (for the profiler, and for planned work on record and replay binaries).
Test Plan: This code is not used (yet). In the next set of PRs, we will switch over test fixtures and stirling binaries to use the `UnitConnector`. Continued passing tests will be the test plan as we switch code over. See #1065.
> [1 of 4] Add `UnitConnector` to Stirling, useful as an API to one source connector.

- Jenkinsfile
Summary: Removes jenkins definitions for release builds, since they've been moved over to github actions.
Test Plan: N/A
> [cleanup] Remove jenkins configs for vizier/operator/cli releases

- .github/workflows/release.yaml
Summary: Adds a github action to build a public cloud release, whenever a `release/cloud` tag is pushed.
Test Plan: Tested on my fork that the public cloud release builds successfully.
> [actions] Add build-cloud-release github action

- codecov.yml
Summary: This is similar to #833 but for the patch level coverage instead.
Commits on mainline show a failed status if patch coverage is less than
total coverage. Instead treat it as informational only.
Test Plan:  `cat codecov.yml | curl --data-binary @- https://codecov.io/validate`
> Change codecov status reporting

- .github/workflows/release.yaml
Summary: We weren't running the `save_version_info.sh` script so all release builds were being stamped with a 0.0.0-dev version.
Test Plan: Testing an RC based off of this PR.
> [releases] Fix version stamping for github action releases

- k8s/vizier/base/metadata_role.yaml
Summary: We were seeing a bug where services weren't showing in our metadata. Turns out we accidentally removed endpoints from our metadata role. This adds it back in.
Test Plan: Skaffold deploy
> Add endpoints back to metadata role

- bazel/test_runners/qemu_with_kernel/run_qemu.sh
Summary: This fixes screen corruption issue when running qemu. The default seabios
sends a bunch of control codes that mess up the terminal.
Test Plan: Run QEMU test.
> Change to OVMF bios is available

- src/pixie_cli/pkg/cmd/deployment_key.go
Summary: We handle `--short` correctl for `px api-key`, but for some reason try to do it differently for `deploy-key`, so it doesn't actually write to stdout.
Test Plan: Bazel build CLI
> Fix --short flag for `px deploy-key`

- .github/workflows/release.yaml
Summary: The `save_version_info` and `get_workspace_status` scripts rely
on these env vars. Else the xdef-ed versions are incorrect and cannot
be parsed by the semver lib we use.
Test Plan: Will test on a fork with a separate bucket.
> Add env vars used by release version stamping

- .github/actions/bazelrc/action.yaml
- .github/workflows/perf_common.yaml
- .github/workflows/trivy_images.yaml
- ci/github/bazelrc
Summary: We don't want to have `--remote_download_outputs=toplevel` for all of the github actions build. However, trivy fails without it so we add an option to add it.
Test Plan: Testing in this PR with trivy. Will also cut an RC to make sure the release builds still work.
> [actions] Optionally add remote_download_outputs=toplevel

- src/ui/src/containers/live-widgets/table/query-result-viewer.tsx
- src/ui/src/containers/live/canvas.tsx
Summary: Makes live widgets use a tiny bit less vertical space, while looking more readable.
Moves the table "Showing X of Y rows" text into this space.
More diffs to come moving other stuff into this bar, from tables and graphs in particular.
- Before: <img width="1341" alt="image" src="https://user-images.githubusercontent.com/314133/231243915-100c43ea-5546-4db0-b348-94166138a9a7.png">
- After: <img width="1343" alt="image" src="https://user-images.githubusercontent.com/314133/231243837-47cff8c9-0cc7-461c-b838-318cba4368b5.png">
Test Plan: Load live view. Look at tables, graphs, etc.
This only affects the live view for now.
> Separate titlebar for Live widgets

- .bazelrc
- bazel/container_images.bzl
- src/common/system/socket_info_namespace_test.cc
- src/common/testing/test_utils/BUILD.bazel
- src/common/testing/test_utils/test_container.h
Summary: Removes `HOME` from the bazel `action_env` to improve caching. This was needed because we download some GCR images during the test. This moves the download to the bazel build phase to fix that issue.
Test Plan: Relying on #ci:bpf-build to make sure tests still work without the action env.
> [build] Remove HOME from action_env to improve caching.

- k8s/devinfra/action-runners/runners/base/deployment.yaml
- k8s/devinfra/action-runners/runners/kvm/deployment.yaml
- k8s/devinfra/action-runners/runners/nokvm/deployment.yaml
Summary: The cpu requests were only being applied to the runner container and not the dind container, but the cpu usage was in the dind container. I think this was leading to some CPU throttling. This PR avoids the issue by using a single container for the runner and the docker daemon. This PR also increases the CPU allocation for KVM runners.
Test Plan: Deployed the new configs to dev infra, running a bpf build&test seems to be somewhat faster.
> [action-runners] Use a single container for dind and runner

- src/api/go/pxapi/results.go
Summary: The `perf-eval` github action was often failing because the data loss streaming pxl script would fail with error "server closed the stream without sending trailers". It seems like this happens similarly to `RST_STREAM` when someone on the TCP chain decides to give up on the connection. This diff allows the script to try to reconnect if this error occurs. I tested the perf eval using these changes and it no longer errors with the above error.
Test Plan: Tested a perf eval with a streaming query and saw that it successfully completed without running into any "server closed the stream ..." errors.
> [pxapi] Allow streaming queries to reconnect if stream ends without trailers

- src/stirling/source_connectors/socket_tracer/grpc_trace_bpf_test.cc
Summary: Under qemu, there was a segfault occuring in the `grpc_trace_bpf_test`. The segfault occured because `SocketTraceBPFTestFixture` was destroyed (and subsequently `SocketTraceConnector` was also destroyed) without a call to `SocketTraceConnector::Stop` which meant the uprobe deploy threads could still be active after destruction of `SocketTraceConnector` and `UProbeManager` leading to attempts to dereference null pointers.
Test Plan: The segfault was consistent under qemu, and after this change it no longer happens. The test is still somewhat flaky about (1 in 20), but not because of segfaults.
> [grpc_trace_bpf_test] Fix test teardown to avoid segfault

- k8s/vizier_deps/base/etcd/etcd_statefulset.yaml
Summary: Updates the etcd StatefulSet to use the new etcd image built in #1229. The statefulset definition no longer needs the inline scripts, since they are now bundled into the image.
Relevant Issues:  Fixes #893
Test Plan: Tested on x86 and ARM, leads to a working Pixie cluster. Also tested that the statefulset can be upgraded, and the rolling upgrade works without issues.
> [etcd] Update statefulset to use new etcd image

- src/stirling/obj_tools/testdata/go/BUILD.bazel
Summary: TSIA
Test Plan: bazel build and test still works.
> Remove unused cross bin from test group

- k8s/vizier/etcd_metadata/aarch64/daemonset.yaml
- k8s/vizier/etcd_metadata/aarch64/deployment.yaml
- k8s/vizier/etcd_metadata/aarch64/job.yaml
- k8s/vizier/etcd_metadata/aarch64/kustomization.yaml
- k8s/vizier/etcd_metadata/aarch64/statefulset.yaml
- k8s/vizier/etcd_metadata/base/metadata_deployment.yaml
- k8s/vizier/etcd_metadata/x86/daemonset.yaml
- k8s/vizier/etcd_metadata/x86/deployment.yaml
- k8s/vizier/etcd_metadata/x86/job.yaml
- k8s/vizier/etcd_metadata/x86/kustomization.yaml
- k8s/vizier/etcd_metadata/x86/statefulset.yaml
- skaffold/skaffold_vizier.yaml
Summary: Adds tolerations for arm64 and amd64 taints to the etcd_metadata deployment.
Relevant Issues: #893
Test Plan: Tested that the metadata deployment works on arm tainted nodes now.
> [etcd_metadata] Add tolerations to metadata deployment

- src/stirling/core/connector_context.cc
- src/stirling/core/connector_context.h
- src/stirling/source_connectors/perf_profiler/perf_profile_connector.cc
Summary: We add `EverythingLocalContext` and a new method `UPIDIsInContext`. The new context type will always return true (for `UPIDIsInContext`) while other pre-existing context types will check the UPIDs list/map/set. Use of this new context type enables tracing short lived processes.
In a subsequent PR, we will switch the `UnitConnector` to use this context type when now pid filtering is desired, which will enable the profiler binary to trace all processes and symbolize all stack traces.
Test Plan: Existing tests pass. And existing tests continue to pass in subsequent PRs that switch-over `UnitConnector` and the profiler binary.
> In `stirling/core/connector_context.h`: add `EverythingLocalContext` to trace short lived processes.

- src/stirling/source_connectors/socket_tracer/protocols/amqp/amqp_code_generator/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/protocols/amqp/amqp_code_generator/requirements.bazel.txt
- src/stirling/source_connectors/socket_tracer/protocols/amqp/amqp_code_generator/requirements.txt
Summary: Upgrade pyshark to fix security vulnerability and fix amqp_code_gen missing pip dep
This upgrades the pyshark package to address [this dependabot](https://github.com/ddelnano/pixie/security/dependabot/4) vulnerability. When trying to test that the amqp code generation still works, I noticed that the `dill` dependency is not specified and so our scripts have been broken on main for some time.
```
$ bazel run //src/stirling/source_connectors/socket_tracer/protocols/amqp/amqp_code_generator:amqp_test_code_gen -- parse_packet
Traceback (most recent call last):
File "/home/ddelnano/.cache/bazel/_bazel_ddelnano/fa8604ca46879b9b1ffd44d337c531f3/execroot/px/bazel-out/k8-fastbuild/bin/src/stirling/source_connectors/socket_tracer/protocols/amqp/amqp_code_generator/amqp_test_code_gen.runfile …
```
> Upgrade pyshark to fix security vulnerability and fix `amqp_code_gen` missing pip dep

- src/ui/src/components/data-table/data-table.tsx
- src/ui/src/containers/live-data-table/live-data-table.tsx
- src/ui/src/containers/live-widgets/table/query-result-viewer.tsx
- src/ui/src/containers/live/canvas.tsx
Summary: Instead of a dedicated column with a blue button, put it in the titlebar as a gear. Also lets the column selector have up to two columns itself (if there are more than 8 options).
Looks like this now.
Relevant Issues: https://github.com/pixie-io/pixie/issues/1174
Test Plan: Load live view. Look at tables. Only the ones in the live view should be affected.
> Move data table column selector to titlebar

- src/ui/src/components/data-table/data-table.tsx
- src/ui/src/containers/live-data-table/data-table-details.tsx
- src/ui/src/containers/live-data-table/live-data-table.tsx
- src/ui/src/containers/live-widgets/table/query-result-viewer.tsx
- src/ui/src/containers/live-widgets/utils/status-indicator.tsx
- src/ui/src/pages/configure-data-export/data-export-history.tsx
Summary: Refreshing the appearance of data tables and detail views.
Adds a copy button since it was trivial to do here.
Fixes #581
Relevant Issues: #1174,#581
Test Plan: Load a script that uses a data table.
Open the data drawer.
Click a row to get details. Click the copy button within it, scroll within it.
Try resizing table columns.
New styling should be applied. More consistent colors, more visible row detail selection, subtle headers.
> New table styling

- src/pxl_scripts/px/http_trace_id/script.pxl
- src/pxl_scripts/px/http_trace_id/vis.json
Summary: Add http_trace_id pxl script for viewing http spans that contain a trace id
Many people at Kubecon asked if Pixie could view distributed traces. While our UI doesn't natively support a distributed trace visualization, pxl scripts are flexible enough to display requests that include trace ids in addition to filtering http requests to only those with a given trace id.
Test Plan: Developed this script within Pixie's scratch pad interface and verified the following
> Add http_trace_id pxl script for viewing http spans that contain a trace id

- src/pxl_scripts/README.md
- src/pxl_scripts/px/http_trace_id/manifest.yaml
Summary: Add manifest file for `http_trace_id` pxl script and update README
This was missed in #1233 and prevented the pxl script bundle from being uploaded. In addition to that, I updated the README since the templating only looks at files in the main branch.
Test Plan: Ran `make -C src/pxl_scripts` to perform README update
> Add manifest file for `http_trace_id` pxl script and update README

- scripts/create_cloud_secrets.sh
Summary: Include another SAN for NATS clustering connections. Also
update server and client CSRs to use different common names.
Relevant Issues: Closes #1082
Test Plan: Deployed a public cloud
> Update cloud deploy script

- k8s/cloud_deps/base/nats/statefulset.yaml
Summary: Upgrade nats to the latest patch version. This version includes many performance improvements for JetStream.
Also update startup, readiness and liveliness probes. These probes follow the same pattern that the [upstream](https://github.com/nats-io/k8s/blob/e0eda12d6062b9f049a7c34b4c9da9f50cb24f64/helm/charts/nats/values.yaml#L48-L106) default helm configs for NATS use.
Note that to use the readiness probes, we also need `podManagementPolicy: Parallel` since the pods won't mark themselves as ready until RAFT is established but we need quorum and all pods to be up to do so.
Test Plan: Deployed dev cloud with these changes.
> Upgrade nats for cloud and adjust lively/ready/startup probes

- k8s/cloud_deps/base/nats/statefulset.yaml
Summary: nats needs to setup RAFT and clustering to be ready but the clustering
is setup via svc based DNS lookups. So we need to tell the service config to
publishNonReadyAddresses.
Test Plan: Deploying nats to a fresh cluster succeeds.
> Tell nats svc to publish notReadyAddresses

- .github/workflows/cli_release.yaml
- ci/cli_build_release.sh
- ci/cli_merge_sign.sh
- ci/cli_upload_signed.sh
Summary: Adds a github action to build, sign, and push CLI releases. I decided to split it out into a separate workflow from the other releases because it requires multiple jobs. I may also move the other release actions into their own workflows also.
Test Plan: Tested on my fork: https://github.com/JamesMBartlett/pixie/releases/tag/release%2Fcli%2Fv0.7.19
> [actions] Add github action for CLI release.

- k8s/cloud/base/indexer_deployment.yaml
- k8s/cloud/base/metrics_deployment.yaml
- k8s/cloud/base/vzconn_deployment.yaml
- k8s/cloud/base/vzmgr_deployment.yaml
Summary: We updated the ports and scheme for prometheus metrics in
953d82850969ff04772203e78671032e70381e5e but failed to update the scrape
configs. This updates the configs so that these metrics continue to be
captured by monitoring.
Test Plan: Updated a deployment manually with the fixed config, saw the metrics
being scraped.
> Update prometheus scrape configs

- k8s/cloud/dev/auth_deployment_patch.yaml
- k8s/cloud/dev/kustomization.yaml
Summary: The yaml patch was broken and the strategic patches are easier
to grok though a bit more verbose. So I changed the patch type and ensured
that it works when you skaffold a dev cloud.
Test Plan: Deployed a dev cloud
> Fix dev cloud auth patch

- scripts/create_release_tag.sh
Summary: The current process for writing changelogs is manual. You manually compile the changelogs and pipe it to the `create_release_tag` script to be used as the tag's message.
We've now standardized our commit message formats, so we can parse commits to determine the type of commit + if it has any release notes to include. This PR updates `create_release_tag` so that it:
1. Finds all commits which touch a dependency of the artifact being released.
2. Parses the commit message to find the kind of commit (bug, feature request, cleanup).
3. Parses the commit message to get the release notes, if any.
4. Takes the commits and compiles it into a markdown-formatted changelog.
Here's an example changelog (there were no changelog updates since the last release so I set it to gather changelogs …
> Release changelogs should read release-notes from commit messages

- src/stirling/source_connectors/socket_tracer/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/bcc_bpf/openssl_trace.c
- src/stirling/source_connectors/socket_tracer/bcc_bpf/socket_trace.c
- src/stirling/source_connectors/socket_tracer/openssl_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
- src/stirling/source_connectors/socket_tracer/uprobe_manager.cc
- src/stirling/source_connectors/socket_tracer/uprobe_manager.h
Summary: Implement new tls tracing method behind stirling cli flag (feature toggle)
The tls tracing method added in this PR determines a connection's identity (socket fd) through a different mechanism from our existing tracing. Instead of relying on struct offsets of user space data structures, it accesses the socket fd via the underlying socket syscalls while `SSL_write` / `SSL_read` calls occur. This is a prerequisite to support BoringSSL because its rolling release style makes the previous method of user space offsets untenable. This has the added benefit of reducing our maintenance cost for our existing OpenSSL tracing. Assuming future versions of OpenSSL maintain the same contract, we will not require any code changes to support them -- Pixie will gain OpenSSL v3 support once this …
> Implement new tls tracing method behind stirling cli flag (feature toggle)

- src/carnot/planner/compiler/ast_visitor.cc
- src/carnot/planner/compiler/ast_visitor.h
- src/carnot/planner/compiler/ast_visitor_expression_test.cc
- src/carnot/planner/compiler/ast_visitor_test.cc
- src/carnot/planner/parser/symbol_table.h
Summary: [carnot] Optimize compiler to execute UDFs for unary operations
This optimization is needed to handle negative integer arguments to a new pxl function I'm working on in #1256 (`format_duration`). This function will simplify the brittle math performed in the `http_trace_id` script that doubles a pxl script time window upon deep linking ([source](https://github.com/pixie-io/pixie/blob/e6f7ad60905bf6a0b696cb74d2b91230017c764e/src/pxl_scripts/px/http_trace_id/script.pxl#L103-L111)).
Test Plan: New tests added pass and PR to add `format_duration` works with negative numbers now
> [carnot] Optimize compiler to execute UDFs for unary operations

- src/stirling/source_connectors/socket_tracer/socket_trace_bpf_test.cc
Summary: In the prior impl. of test case `socket_trace_bpf_test`, there was a possible test flake based on capturing eBPF perf buffer data out of order. Because the test case started two threads, depending on which CPU owned which thread and when the perf buffers were populated, we could see the test expectations out of order (even though logically that was not what happened). We fix this test flake by removing the expectation of seeing the results in order.
Test Plan: Tested locally, ran socket_trace_bpf_test with --runs_per_test 16 and did not observe this specific test flake any more.
> Fix a test flake in `socket_trace_bpf_test`.

- src/carnot/planner/objects/pixie_module.cc
- src/carnot/planner/objects/pixie_module.h
- src/carnot/planner/objects/pixie_module_test.cc
Summary: Add `format_duration` pxl function to aid duration calculations
While developing the `http_trace_id` pxl script in #1233, I had to perform some brittle math in order to parameterize the deep linked script ([source](https://github.com/pixie-io/pixie/blob/e6f7ad60905bf6a0b696cb74d2b91230017c764e/src/pxl_scripts/px/http_trace_id/script.pxl#L103-L111)). This function will simplify that logic and ensure that it works for all units (currently it would break if anything other than minutes were used).
Test Plan: Tests added for `format_duration` script pass
Changelog Message: Added the `format_duration` pxl function, which simplifies converting a duration integer to a string representation. This is useful for manipulating script …
> Add `format_duration` pxl function to aid duration calculations

- src/e2e_test/protocol_loadtest/http/BUILD.bazel
- src/e2e_test/protocol_loadtest/http/http.go
Summary: Adds prometheus instrumentation to the protocol_loadtest server. We will use this instrumentation to measure CPU/rss/etc before and after we deploy vizier, to measure vizier's overhead on the application.
Test Plan: Tested that I get prometheus process metrics at the `/metrics` endpoint of the protocol loadtest server.
> [protocol_loadtest] Add prometheus process metrics instrumentation.

- src/cloud/api/ptproxy/request_proxyer.go
- src/pixie_cli/pkg/sentryhook/hook.go
- src/shared/services/logging.go
- src/shared/services/server/grpc_server.go
Summary: This does two things, reduce the logging from grpc code
`Unavailable` and http StatusCode `Unknown` to reduce log spam
and also identify which message type errored in the request proxyer.
This should help us narrow down any API svc issues.
Test Plan: Ensure that everything builds and check logs upon deploy.
> Improve api_svc logs

- src/stirling/core/connector_context.cc
- src/stirling/core/connector_context.h
Summary: In the previous impl. of `EverythingLocalContext`, we masked a base class instance of `upids_`. We fix that in this patch, and align usage of the `EverythingLocalContext` to better match the existing work in `socket_trace_bpf_test_fixture.h`.
Test Plan: Tested locally with the next diff and along with work to de-flake socket tracer tests.
> Tidy up & fix `EverythingLocalContext`.

- src/cloud/api/ptproxy/request_proxyer.go
- src/shared/services/server/grpc_server.go
Summary: Make `processNatsMsg` wrap and return an error but not log it
since the caller already logs it.
Update grpc middleware to ignore Context Canceled errors.
Test Plan: Check logs and sentry after deploying.
> More improvements to error handling

- bazel/cc_toolchains/clang/toolchain.BUILD
Summary: `rules_docker` requires building some go binaries to be used as tools in later build steps. Since our compiler defaults to using PIE, and golang doesn't realize it defaults to using PIE, the resultant golang PIE executable is invalid. This disables PIE for host tools on the clang side, circumventing this issue.
Test Plan: Built `//:pl_go_base_iamge` with the new golang version without issue.
> [build] Disable PIE for building host tools

- src/ui/src/components/command-palette/command-providers.tsx
- src/ui/src/components/command-palette/providers/command-provider.ts
- src/ui/src/components/command-palette/providers/script/empty-input-provider.tsx
- src/ui/src/components/command-palette/providers/script/missing-script-provider.tsx
- src/ui/src/components/command-palette/providers/script/script-command-is-valid-provider.tsx
- src/ui/src/components/command-palette/providers/script/script-provider-cta.tsx
- src/ui/src/components/command-palette/providers/script/script-provider.tsx
- src/ui/src/components/command-palette/providers/script/script-suggestions.tsx
Summary: Makes the Command Palette behave more asynchronously, with some bugfixes along the way.
- Switches providers from `Promise` to `useReducer`, so they can update in stages
- Flattens the provider structure so they aren't nested (fixes a few collisions)
- Fixes `validValues` suggestions and required arg checks (side benefits of the above)
- Ultimately, results come in faster, bounce less, and handle errors better
This PR was preceded by: #939, #1046, #1047, #1053, #1076, #1079, and #1080. There will be more after it to continue improving the experience, especially when there are many results.
Test Plan: Use the Command Palette. It should feel a bit snappier, a bit less error-prone, and it should handle `validValues` correctly now (try `px/nodes`'s `groupby` …
> Command Palette Reducers

- src/e2e_test/perf_tool/pkg/metrics/pxl_script_recorder.go
- src/e2e_test/perf_tool/pkg/metrics/recorder.go
- src/e2e_test/perf_tool/pkg/run/run.go
Summary: Errors often occur in the metric recorders when a cluster goes unhealthy or a query fails for other reasons. Previously, these errors would only be surfaced after the experiment finished running. This PR adds a channel to send the errors to, so that the errors are caught as soon as they happen and the experiment can be abandoned earlier.
Test Plan: Tested that sending an error to the error channel leads to the experiment being aborted early.
> [perf_tool] Exit early on errors in metric recorders

- src/stirling/source_connectors/perf_profiler/pprof/BUILD.bazel
- src/stirling/source_connectors/perf_profiler/pprof/pprof.cc
- src/stirling/source_connectors/perf_profiler/pprof/pprof.h
Summary: We add a method `CreatePProfProfile` to convert from the perf profiler output to a pprof protobuf.
Test Plan: Tested locally with the `stirling_profiler` binary. The profiler binary, after finishing, writes a pprof .pb file to disk. The file, when opened with `go tool pprof` renders the expected flamegraph.
> Add pprof protobuf export into perf profile source connector. 

- src/ui/src/components/command-palette/command-text-field.tsx
Summary: Selects the text that it pre-fills immediately. Before, it would only put the caret at the end.
This lets you start typing immediately.
Test Plan: Open the command palette.
> Auto-select Command Palette input on open

- src/e2e_test/perf_tool/pkg/suites/experiments.go
- src/e2e_test/perf_tool/pkg/suites/suites.go
- src/e2e_test/perf_tool/pkg/suites/workloads.go
Summary: Adds a new experiment to the nightly perf suite that runs online boutique as the workload.
Test Plan: Ran the online boutique experiment locally, saw that it completed succesfully.
> [perf_tool] Add experiment running online boutique

- src/ui/src/containers/live-widgets/graph/graph-base.tsx
- src/ui/src/containers/live-widgets/graph/graph.tsx
- src/ui/src/containers/live-widgets/graph/request-graph.tsx
- src/ui/src/containers/live/canvas.tsx
Summary: TSIA. Affects network graphs, request graphs, and flamegraphs.
Also presses the edges of these graphs to the edge of their container to use the full available space.
Test Plan: Run `px/cluster` and `px/perf_flamegraph`.
The outermost borders of graphs in both should be pushed to the edges of their containers.
The extra buttons (including zoom buttons) for the request graph should be in the titlebar now, and still function.
> Move graph widget controls into titlebar

- src/e2e_test/perf_tool/pkg/suites/experiments.go
- src/e2e_test/perf_tool/pkg/suites/suites.go
- src/e2e_test/perf_tool/pkg/suites/workloads.go
Summary: Adds a perf experiment that runs the `px-kafka` demo to the nightly suite.
Test Plan: Currently, running a kafka experiment, and kafka deployed successfully. Will wait to make sure the experiment completes entirely sucessfully.
> [perf_tool] Add experiment that runs the kafka demo

- bazel/test_runners/qemu_with_kernel/run_qemu.sh
Summary: OVMF bios seems to cause kernel hangs when running enough tests concurrently. Don't have time to debug it at the moment, so for now let's just put up with the control characters from SeaBIOS.
Test Plan: Tested that running multiple tests concurrently under qemu doesn't hang anymore.
> [qemu-bpf] Remove OVMF bios

- src/e2e_test/perf_tool/pkg/metrics/prometheus_recorder.go
Summary: Comment on #1273 came through after it was already merged. This PR adds a defer `ticker.Stop()` to address that comment.
Test Plan: N/A
> [perf_tool] Cleanup comment from #1273

- src/e2e_test/perf_tool/pkg/suites/experiments.go
- src/e2e_test/perf_tool/pkg/suites/metrics.go
- src/e2e_test/perf_tool/pkg/suites/suites.go
- src/e2e_test/perf_tool/pkg/suites/workloads.go
Summary: Adds an experiment that runs an HTTP loadtest workload for 10 minutes collecting prometheus metrics on its CPU usage, RSS memory usage, etc. Then deploys Vizier and continues to run it for another 10 minutes. We can then compare the CPU usage with Vizier to the baseline, to measure Vizier's overhead on the application side.
Test Plan: Ran the application overhead experiment locally and it completed successfully.
> [perf_tool] Add application overhead experiment

- src/stirling/source_connectors/dynamic_bpftrace/dynamic_bpftrace_connector_bpf_test.cc
- src/stirling/testing/common.h
Summary: Removes dependence on sleeps/timing from the dynamic_bpftrace bpf test, by adding loops with timeouts to wait for records to show up.
Relevant Issues: Fixes #1245.
Test Plan: Along with #1278, ran `bazel test --config=qemu-bpf //src/stirling/source_connectors/dynamic_bpftrace:dynamic_bpftrace_connector_bpf_test --runs_per_test=50` without any failures.
> [bpf tests] Remove timing dependence from dynamic_bpftrace_connector_bpf_test

- k8s/cloud/base/indexer_config.yaml
- k8s/cloud/dev/indexer_config.yaml
- k8s/cloud/staging/indexer_config.yaml
- k8s/cloud/testing/indexer_config.yaml
- src/cloud/autocomplete/suggester_test.go
- src/cloud/indexer/indexer_server.go
- src/cloud/indexer/md/BUILD.bazel
- src/cloud/indexer/md/mapping.o.go
- src/cloud/indexer/md/md_test.go
- src/cloud/shared/esutils/ilm_policy.go
- src/cloud/shared/esutils/index.go
- src/cloud/shared/esutils/index_test.go
- src/cloud/shared/esutils/managed_index.go
- src/cloud/shared/esutils/managed_index_test.go
Summary: The `ManagedIndex` creates an elastic ILM policy which causes elastic to rollover the indices after the given period of time, and then delete rolled-over indices after another given period of time. Its currently setup to rollover indices after 3 days and then delete the rolled over indices after another 3 days. Since we refresh metadata every 12hours this should be plenty of leeway. This PR also fixes a couple of bugs with the way `esutils` handles updating settings when the requested index already exists.
Test Plan: Tested on dev cloud
> [indexer] Use `esutils.ManagedIndex` to create elastic index

- .bazelrc
- ci/cli_build_release.sh
- ci/cloud_build_release.sh
- ci/image_utils.sh
- ci/vizier_build_release.sh
- skaffold/skaffold_cloud.yaml
- src/stirling/k8s/run_stirling_wrapper_on_k8s.sh
- src/stirling/scripts/run_go_grpc_app_on_k8s.sh
- src/stirling/scripts/run_go_http_app_on_k8s.sh
- src/stirling/testing/demo_apps/go_http/README.md
Summary: `GH_API_KEY` being in the action env significantly reduces the performance of the cache. This PR improves that somewhat by removing in from the action env for default builds. However, it's still in the action env for stamped builds, so those will still have bad cache properties.
Test Plan: Ran `bazel build //tools/licenses:all_licenses --config=stamp` and it worked without missing licenses.
> [build] Remove GH_API_KEY from action env for default builds

- src/stirling/obj_tools/elf_reader.cc
Summary: Add bounds checking to prevent bogus ELF bytecode parsing from causing allocation errors
#1111 documents a case where attempting to deploy Go uprobes to a particular application results in `std::bad_alloc` errors. The specific application that caused this behavior was a go 1.13 binary built using include GOOS=linux GOARCH=386 CGO_ENABLED=0.
The bytecode threshold was determined by inspecting Go's `crypto/tls.(*Conn).Write` and `crypto/tls.(*Conn).Read` symbol sizes with an additional 100x multiplier applied (see Test plan for more details).
Relevant Issues: #1111
Test Plan: Created a [test program](https://github.com/pixie-io/pixie/commit/51bef3c04331d13e635532bf0dc9d23e082044fa) to isolate the ELF and DWARF parsing code to reproduce the crash and …
> Add bounds checking to prevent bogus ELF bytecode parsing from causing allocation errors

- .github/workflows/cli_release.yaml
- src/pixie_cli/BUILD.bazel
Summary: Don't create github releases for CLI RCs.
Test Plan: N/A
> [releases] Don't create github releases for CLI rcs

- .github/workflows/vizier_release.yaml
- ci/vizier_build_release.sh
Summary: Creates a github release in the github releases tab for any non-RC vizier releases. Adds `vizier_yamls.tar` and `vizier_yamls.tar.sha256` as artifacts.
Test Plan: Tested with an RC that I forced to create a github release https://github.com/pixie-io/pixie/releases/tag/release%2Fvizier%2Fv0.13.2-pre-vizier-github-release4.5.
> [releases] Create github release for vizier releases

- bazel/test_runners/qemu_with_kernel/test_runner_inside_qemu.sh
- src/stirling/source_connectors/stirling_error/stirling_error_bpf_test.cc
- src/stirling/testing/common.h
- src/stirling/testing/overloads.h
Summary: `stirling_error_bpf_test` relied a lot on timing in order to make its assertions. This removes all timing dependence, and instead waits for the expectations or timesout.
Test Plan: Ran `bazel test --config=qemu-bpf //src/stirling/source_connectors/stirling_error:stirling_error_bpf_test --runs_per_test=50` without a single failure.
> [bpf tests] Remove timing dependence from stirling_error_bpf_test

- .github/actions/comment_command/action.yaml
- .github/workflows/perf.yaml
Summary: Adds a custom slash command action, that can be used to trigger `/...` commands on PRs. This allows us to have finer grained control over the permissions, so that we can allow members to run the `/perf` command on other members PRs.
Test Plan: Tested on my fork that the command blocks non members and works for members.
> [github actions] Use custom slash command action

- src/stirling/source_connectors/socket_tracer/bcc_bpf/openssl_trace.c
Summary: Remove update to BPF map not used in status quo tls tracing
In order to vet the new style of tls tracing, we introduced a mechanism for detecting mismatched fds (#1161). This instrumented all of our tls tracing when it was first developed. When the new method of tls tracing was introduced, we removed the mismatched fd detection from the status quo tls tracing (#1123), however, this BPF map update was missed in that refactor (#1123).
Test Plan: Existing tests pass
> Remove update to BPF map not used in status quo tls tracing

- .github/workflows/operator_release.yaml
- ci/operator_helm_build_release.sh
Summary: Adds a github release for each operator non-RC release.
Test Plan: Tested by forcing an RC to create a github release: https://github.com/pixie-io/pixie/releases/tag/release%2Foperator%2Fv0.1.1-pre-z4-1-test-operator-release.4
> [releases] Create Github release for operator releases

- .bazelrc
- bazel/pl_build_system.bzl
- bazel/test_runners/qemu_with_kernel/BUILD.bazel
- bazel/test_runners/qemu_with_kernel/interactive_runner.sh
- bazel/test_runners/qemu_with_kernel/launcher.sh
- bazel/test_runners/qemu_with_kernel/run_qemu.sh
- bazel/test_runners/qemu_with_kernel/runner.bzl
- bazel/toolchain_transitions.bzl
- src/stirling/bpf_tools/BUILD.bazel
- src/stirling/e2e_tests/BUILD.bazel
- src/stirling/obj_tools/BUILD.bazel
- src/stirling/source_connectors/cpu_stat_bpftrace/BUILD.bazel
- src/stirling/source_connectors/dynamic_bpftrace/BUILD.bazel
- src/stirling/source_connectors/dynamic_tracer/BUILD.bazel
- src/stirling/source_connectors/perf_profiler/BUILD.bazel
- src/stirling/source_connectors/proc_exit/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/BUILD.bazel
- src/stirling/source_connectors/stirling_error/BUILD.bazel
- src/stirling/source_connectors/tcp_stats/BUILD.bazel
- src/stirling/utils/BUILD.bazel
Summary: Adds a way to get a shell inside qemu using SSH. To run the interactive qemu session without any test runfiles, run: `bazel run //bazel/test_runners/qemu_with_kernel:run_interactive`.
To run with a test's runfiles, run `bazel run //<path/to/test>_qemu_interactive`, eg. `bazel run //src/stirling/obj_tools:elf_reader_symbolizer_bpf_test_qemu_interactive`. Note it won't work if you add `--config=qemu-bpf` because of the way bazel's `run_under` flag works, so just leave out the `--config`.
Test Plan: Tested that the interactive runner opens a shell with the expected runfiles. Also tested that closing the shell at any point doesn't leave zombie qemu processes.
> [qemu] Add interactive runner using ssh

- src/stirling/binaries/BUILD.bazel
- src/stirling/binaries/stirling_profiler.cc
Summary: We update the `stirling_profiler` binary to directly write a ppprof protobuf file.
Test Plan: Ran the binary locally. Opened the resulting pprof pb file using `go tool pprof`. Observed expected flamegraph.
> Write pprof from stirling profiler.

- src/stirling/core/unit_connector.h
- src/stirling/source_connectors/perf_profiler/BUILD.bazel
- src/stirling/source_connectors/perf_profiler/perf_profiler_bpf_test.cc
Summary: we convert `perf_profiler_bpf_test` to use `UnitConnector` to share code across different tests and binaries.
We also refactor the Java test case to separately test the expectation that Java symbolization artifacts are removed after processes stop. The main Java test case then conforms to the pattern established for Go and cpp.
We also update some of the helper functions in the test to tidy up the common test cases.
Test Plan: existing tests & runs per test.
> Update `perf_profiler_bpf_test` to use `UnitConnector`.

- .github/workflows/cloud_release.yaml
- ci/cloud_build_release.sh
Summary: TSIA
Test Plan: Forced an RC to create a github release, saw that the github release was created properly with the changelog.
> [releases] Create Github release for cloud releases.

- .github/workflows/cloud_release.yaml
Summary: There was a slight bug that slipped through which meant GitHub releases were only being created for cloud RCs instead of only for full releases.
Test Plan: N/A
> [releases] Don't create github releases for cloud RCs

- .bazelrc
- .github/actions/bazelrc/action.yaml
- .github/workflows/build_and_test.yaml
- bazel/test_runners/qemu_with_kernel/run_qemu.sh
- ci/bazel_build_deps.sh
- ci/github/bazelrc
- ci/github/matrix.sh
- ci/github/matrix.yaml
- ci/run_clang_tidy.sh
- scripts/bazel_ignore_codes.sh
- src/stirling/source_connectors/tcp_stats/BUILD.bazel
Summary: Adds a github action to run builds and tests, including bpf tests. The action uses the configs defined in `ci/github/bazelrc` along with the `bazel_build_deps.sh` script to decide what tests to run and under what configurations to run them.
Test Plan: Tested in this PR that all the tests (including BPF tests) work. Also, tested that failing tests are reported properly, by adding an `ASSERT_EQ(0, 1)` only in opt configs, and saw that only opt configs failed.
> [actions] Add build-and-test github action

- .github/workflows/build_and_test.yaml
Summary: Pins versions to shas for external actions used by the build-and-test github action.
Test Plan: N/A should be no changes.
> [build-and-test] Pin external github action versions

- .github/workflows/build_and_test.yaml
- ci/github/matrix.sh
Summary: Passing the full github context to `matrix.sh` was unreliable, instead just pass the things we need.
Test Plan: Testing with this PR, also rebasing #1316 which previously failed to make sure it doesn't anymore.
> [build-and-test] Fix passing of github context to matrix.sh

- .github/workflows/build_and_test.yaml
Summary: When there are no matrix configs to run, without this change, a check is added with an ugly ${{ matrix.name }}. This PR removes the custom naming, which removes the ugly ${{matrix.name}}
Test Plan: Testing with this PR, since there shouldn't be any matrix configs to run.
> [build-and-test] Remove custom name from matrix checks.

- .github/workflows/build_and_test.yaml
Summary: Adds a github action to run code coverage on commits to main.
Test Plan: Testing in this PR that the coverage runs (not testing the upload to codecov so I don't mess with the metrics). The code coverage output looked roughly the same as when I ran it locally, and numbers looked comparable to the main report. Will test the actual upload after landing, but it shouldn't be any different from on Jenkins.
> [actions] Add code coverage github action.

- src/cloud/config_manager/controllers/server.go
Summary: Passing a quantity which cannot be parsed will lead to a crashloopbackoff.
Test Plan: Deploy to staging
> Fix quantity parsing in configmgr service

- src/stirling/source_connectors/tcp_stats/tcp_stats_bpf_test.cc
- src/stirling/testing/overloads.h
- src/stirling/utils/tcp_stats.h
Summary: Update `tcp_stats_bpf_test` to work with qemu
Test Plan: Verified that the test ran successfully for our various test runners
> Update `tcp_stats_bpf_test` to work with qemu

- .github/workflows/build_and_test.yaml
Summary: This should fix the tcp_socket_test that is failing for
coverage builds.
Test Plan: Check coverage run on main after this lands.
> Enable IPV6 in github actions for coverage build

- .github/workflows/build_and_test.yaml
Summary: These regression tests are quite expensive to run, because it runs BPF tests across all kernels for 4 hours each. I don't really see much value in running it nightly, I think weekly should suffice.
Test Plan: N/A
> [build-and-test] Only run flakiness regression tests weekly

- src/stirling/source_connectors/tcp_stats/BUILD.bazel
Summary: Remove `no_qemu` tag for tcp_stats_bpf_test
The long lived PR for adding our CI jobs to GitHub actions finished up just as the qemu incompatibility was addressed. We can now opt this test into qemu testing.
Type of change: /kind buf
Test Plan: Verified in #1308 that this test works with qemu
> Remove `no_qemu` tag for tcp_stats_bpf_test

- k8s/vizier/base/kelvin_deployment.yaml
- k8s/vizier/pem/base/pem_daemonset.yaml
- src/carnot/funcs/metadata/metadata_ops.cc
- src/carnot/funcs/metadata/metadata_ops.h
- src/carnot/funcs/metadata/metadata_ops_test.cc
- src/shared/metadata/metadata_state.cc
- src/shared/metadata/metadata_state.h
- src/shared/metadata/standalone_state_manager.h
- src/shared/metadata/state_manager.h
- src/shared/metadata/state_manager_test.cc
- src/vizier/services/agent/kelvin/kelvin_main.cc
- src/vizier/services/agent/shared/manager/manager.cc
- src/vizier/services/agent/shared/manager/test_utils.h
Summary: Adds a new `px.vizier_namespace()` function usable from PxL scripts to discover the namespace that the Vizier components are deployed into.
Test Plan: Added some unit tests.  Manually tested on a minikube.
Relevant Issues: Fixes #1304
> Add UDF to discover namespace where Vizier is deployed

- src/stirling/source_connectors/socket_tracer/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/openssl_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
- src/stirling/source_connectors/socket_tracer/uprobe_manager.cc
Summary: Enable TLS tracing for applications using dynamically linked OpenSSL v3
Test Plan: Existing tests provide the necessary coverage
```release-note
TLS tracing now supports applications using OpenSSL v3
```
> Enable TLS tracing for applications using dynamically linked OpenSSL v3

- src/ui/src/components/data-table/data-table.tsx
Summary: Makes table headers a bit more visible and consistent.
Test Plan: Look at live data tables. Header row should be more visible and distinguishable from body rows. Gear icon should be a bit smaller too, and the row/column borders are now the same color.
> Table style tweaks

- src/shared/pprof/pprof.cc
- src/shared/pprof/pprof.h
- src/stirling/binaries/stirling_profiler.cc
Summary: Previously we divided the sample time duration by CPU count, i.e. such that total time would match wall clock time. Here we stop that practice because it is more correct to report the time spent on core (even if the total time reported is longer than wall clock time).
Test Plan: Tests will be merged with #1336.
> Do not adjust pprof sample time by dividing by CPU count.

- src/ui/src/components/autocomplete/autocomplete.tsx
- src/ui/src/components/autocomplete/completions.tsx
- src/ui/src/components/autocomplete/input.tsx
- src/ui/src/components/breadcrumbs/__snapshots__/breadcrumbs-test.tsx.snap
- src/ui/src/components/breadcrumbs/breadcrumbs.tsx
- src/ui/src/components/select/select.tsx
- src/ui/src/containers/live/breadcrumbs.tsx
- src/ui/src/containers/live/cluster-selector.tsx
Summary: Rounds off borders, changes colors somewhat, and visually connects the dropdown with its anchor.
https://github.com/pixie-io/pixie/assets/314133/5d48cee2-4230-4474-b11d-7bb2e1556d0a
Test Plan: In the Live view, play with the cluster selector, the script selector, and the arguments. Try scripts that have several arguments, too.
> Update dropdown styling

- src/operator/controllers/vizier_controller.go
Summary: We currently decide whether or not to deploy an etcd-backed metadata store or pv-backed metadata store if a user doesn't have any default storage classes set.
However, we've been seeing instances where the storageclass exists, but persistent volumes still can't be used unless the CSI driver is enabled. This leads to many failed deployments. Instead, we can autodetect this case since it is fairly common.
Test Plan: Skaffold deploy operator to a cluster
> During deploy time operator should check for CSI Driver and switch to etcd

- README.md
Summary: Adds a link to the latest github release for vizier, cli, and cloud components. (Will add a link to the operator release once there is one on github).
Test Plan: Made sure the new readme changes render reasonably.
> [README] Add links to latest component releases

- k8s/vizier/base/metadata_role.yaml
- k8s/vizier/bootstrap/cert_provisioner_job.yaml
- k8s/vizier/bootstrap/cert_provisioner_role.yaml
- k8s/vizier/bootstrap/cloud_connector_role.yaml
- k8s/vizier/bootstrap/kustomization.yaml
- k8s/vizier/bootstrap/updater_role.yaml
- src/utils/template_generator/vizier_yamls/vizier_yamls.go
Summary: Cleans up RBAC rules for Vizier in order to reduce the privileges required to install it.  Removes `pl-updater` service account and its RBAC, which included non-functional `ClusterRole` and `ClusterRoleBinding` and doesn't appear to be used by the current operator-based upgrade workflow.
Test Plan: Tested new yamls on a local minikube using `skaffold` as suggested in DEVELOPMENT.md, deleted `proxy-tls-certs` manually and re-ran the cert-provisioner-job successfully.  Tested change to vizier_yaml.go by running the template generator against a local build of the base yaml tar, observed that the new binding's subject namespace is templated as expected.
Fixes: #634 and #1353
> Reduce privileges required to install Vizier

- .github/workflows/cli_release.yaml
- .github/workflows/cloud_release.yaml
- .github/workflows/operator_release.yaml
- .github/workflows/release_update_readme.yaml
- .github/workflows/vizier_release.yaml
- ci/update_readme_with_latest_release.sh
Summary: Adds a github workflow to create a PR to update the release links in the README. Note that github won't recursively run workflows, so all of the release workflows need to use the pixie-io-buildbot token to create the releases instead of the default github action token.
Test Plan: Tested on my fork, saw that the PR gets created as expected: https://github.com/JamesMBartlett/pixie/pull/18.
> [releases] Automatically create PR to update readme on releases.

- README.md
Summary: Update links to latest releases in readme. Until #1366 lands we have to keep doing this manually.
Test Plan: N/A
> [README] Update latest releases

- .github/actions/sign_artifacts/action.yaml
- .github/workflows/cloud_release.yaml
- .github/workflows/operator_release.yaml
- .github/workflows/vizier_release.yaml
Summary: GPG sign release artifacts for vizier, operator and cloud releases. Eventually we should refactor the CLI release to use the same signing method, but I'm going to leave it as is for now. Not sure whether we should sign the `.sha256` files, since it seems a bit weird to do, but it might be the case that the CLO monitor check requires it. In any case, I made it a flag that's easy to change, so if we do want to sign sha files we can flip the flag.
Test Plan: Tested on my fork, saw releases with `.asc` signature files: [vizier](https://github.com/JamesMBartlett/pixie/releases/tag/release%2Fvizier%2Fv0.13.6-pre-test-sign-release-artifacts.2), [operator](https://github.com/JamesMBartlett/pixie/releases/tag/release%2Foperator%2Fv0.1.2-pre-test-sign-release-a …
> [releases] GPG sign release artifacts

- k8s/vizier_deps/base/nats/nats_statefulset.yaml
Summary: We were already using TLS for our NATS communications. This option adds validation for the client certificate.
Test Plan: Create a Vizier RC and deploy it to a cluster. Ensure that everything continues running as expected.
```release-note
Add TLS verification to NATS.
```
> Add TLS verify to NATS

- demos/README.md
- demos/manifest.json
Summary: Add k8s manifests for k8ssandra px cli demo
Relevant Issues: #680
Test Plan: Verify the demo works by deploying it as described below:
```release-note
Add a k8ssandra demo to the `px` cli
```
> Add k8s manifests for the k8ssandra px cli demo

- demos/README.md
- src/pixie_cli/pkg/cmd/demo.go
Summary: We are working on adding the px-k8ssandra demo in our demo apps. However, this demo app is more complex. It requires cluster-scoped resources such as mutating webhooks, and proper cleanup requires the K8ssandraCluster to be deleted first or else things will hang.
We can control the delete process through labels. Adding labels to the demo resources allow us to target cluster-scoped resources that wouldn't be deleted from just deleting the namespace. We can use an additional label for resources that need to be cleaned up first.
Relevant Issues: #680
Test Plan: Deploy px-k8ssandra demo app and delete. Make sure resources all get cleaned up and delete runs without error. Also make sure delete still works on existing demo-apps, such as px-sock-shop. …
> Refine `px demo delete` logic for more complex demo applications

- ci/image_utils.sh
- ci/operator_build_release.sh
- ci/vizier_build_release.sh
Summary: These args were used to define image registries. Now we use
config flags to do the same and the args are unset/unused.
Test Plan: Unused args, release scripts should continue to work.
> Remove unused extra bazel args

- src/cloud/api/controllers/session_middleware.go
Summary: This event can be quite spammy and doesn't give us very useful information. This PR removes it.
Test Plan: This does not affect any functionality
> Remove API Request analytics event

- src/stirling/source_connectors/socket_tracer/protocols/cql/parse_test.cc
Summary: Fix test data used in CQL parser tests
The CQL protocol defines that messages have a [256 MiB size limit](https://github.com/apache/cassandra/blob/fad1f7457032544ab6a7b40c5d38ecb8b25899bb/doc/native_protocol_v3.spec#LL199C24-L199C24). The CQL parser test cases used a 16 MiB message size (0x1000000) rather than one that was greater than 256 MiB. The inconsistencies in this test were identified as I've been investigating #1375.
Relevant Issues: #1375
Test Plan: Verified with gdb that each test case returns the `kInvalid` from its specific branch and existing tests pass
> Fix test data used in CQL parser tests

- src/stirling/source_connectors/socket_tracer/fd_resolver_test.cc
Summary: Update the FDResolver stdin test to pass when resolution returns a file or pipe
This test was failing when run under bazel remote execution. The source of the error was due to the FDResolver returning a string like `pipe:[15235525]`. This updates the test assertion to handle the pipe and file path case.
Test Plan: Hard coded `pipe:[15235525]` as the return value and verified the test passes
> Update the FDResolver stdin test to pass when resolution returns a file or pipe

- src/ui/package.json
- src/ui/yarn.lock
Summary: The version of canvas we depended on didn't have pre-built
binaries for node v18 and node-gyp was failing during the build step
on some machines.
This upgrades canvas to a version that publishes pre-built binaries
for node v18 and fixes the issue.
Type of change: /kind devinfra
Test Plan: `yarn install` doesn't call node-gyp for canvas and succeeds.
> [chore] upgrade canvas

- .github/workflows/cloud_release.yaml
- .github/workflows/operator_release.yaml
- .github/workflows/vizier_release.yaml
- ci/cloud_build_release.sh
- ci/image_utils.sh
Summary: This uses cosign to sign all of our images.
Test Plan: Created RCs for operator, cloud, and vizier. Verified that they were all signed as expected.
> Sign images using cosign

- src/ui/src/components/autocomplete/completions.tsx
Summary: Restore the bold highlight of matched terms in breadcrumbs.
Test Plan: Use the breadcrumbs. Search for something. Highlight should be restored.
> Fix highlight CSS in autocomplete dropdowns

- src/ui/src/components/breadcrumbs/__snapshots__/breadcrumbs-test.tsx.snap
- src/ui/src/components/breadcrumbs/breadcrumbs.tsx
Summary: There was an elevation shadow from Material that was no longer needed.
Without change...
With change...
Test Plan: Open live view in light mode. No more weird boxy shadow on the breadcrumbs.
> Remove unintended drop shadow in light mode

- k8s/devinfra/equinix_k3s/README.md
- k8s/devinfra/equinix_k3s/setup_k3s.sh
- k8s/devinfra/equinix_k3s/teardown.sh
Summary: Adds a script to setup a k3s cluster on equinix. The script assumes you have nodes already provisioned with public IPs, and that your ssh key has access to those nodes.
Test Plan: Tested that the script creates a working equinix cluster. The teardown side has some fragility around the EIP being set as an addr on the loopback device, but I added a `ip addr del` that should take care of that.
> [equinix] Add k3s setup script

- src/stirling/bpf_tools/BUILD.bazel
- src/stirling/e2e_tests/BUILD.bazel
- src/stirling/source_connectors/jvm_stats/BUILD.bazel
- src/stirling/source_connectors/perf_profiler/BUILD.bazel
- src/stirling/source_connectors/perf_profiler/java/agent/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/BUILD.bazel
Summary: Removes the "exclusive" tags from bpf tests. Since we now run bpf tests under qemu, the exclusive tags aren't necessary. This has the added benefit of making these tests work with remote execution. The only downside is that `bazel test //... --config=bpf` won't run these tests exclusively anymore, but as far as I'm aware nobody runs that because it requires root.
Test Plan: Tested that all the tests still work running simulataneously under qemu. Ran with `--runs_per_test=20` only saw 2 failures in `grpc_trace_bpf_test` and 2 failures in `http2_trace_bpf_test`, which is inline with the flakiness we usually see.
> [build] Remove exclusive tags from bpf tests

- .bazelrc
- bazel/BUILD.bazel
Summary: Add bazel configs for running against buildbuddy remote executors. In addition to these configs, a buildbuddy api key is needed.
Test Plan: Tested that remote builds work (`--config=clang`, `--config=x86_64_sysroot` and `--config=qemu-bpf`)
> [build] Add --config=remote, for running builds against buildbuddy remote executors.

- src/ui/src/components/data-table/data-table.tsx
- src/ui/src/containers/live-widgets/table/query-result-viewer.tsx
Summary: In some cases, `react-window` would get itself stuck in a computation loop relating to overscroll.
This turned out to be a consequence of an interaction between `react-window` and [scroll anchoring](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor/Guide_to_scroll_anchoring).
By disabling scroll anchoring in this virtualized list, and fixing a performance bug in the table summary's render, the issue goes away completely.
Test Plan: Run `px/cluster` in Chrome, or `px/http_data` in Firefox (in the latter case, resize the table to be one "grid unit" shorter and run again).
Then, scroll to the bottom of the result tables.
Before, they would jitter nonstop in Chrome, or only for a moment in Firefox before it blocks scroll anchoring with a …
> Fix jittery scrolling at bottom of some tables in Chrome

- k8s/devinfra/buildbuddy-executor/README.md
- k8s/devinfra/buildbuddy-executor/values.yaml
Summary: Adds the values were using to deploy self-hosted buildbuddy executors. Currently, it relies on my fork of the buildbuddy helm chart, but I think the last PR will be merged in soon and we can just use the main buildbuddy-helm repo.
Test Plan: Tested the buildbudy executor deploy on equinix.
> Add config for buildbuddy-executor helm deploy

- .bazelrc
- .github/actions/bazelrc/action.yaml
- .github/actions/env_protected_pr/action.yaml
- .github/workflows/build_and_test.yaml
- ci/github/matrix.sh
Summary: Uses buildbuddy remote execution to run build and test bazel commands. Uses Github "environments" to access the authorize access to the BB_IO_API_KEY secret.
Test Plan: Tested on my fork. Had @vihangm create a PR, saw that it required me to approve the environment before it would run.
> [build-and-test] Use buildbuddy remote execution for build and test actions.

- src/stirling/source_connectors/perf_profiler/perf_profile_connector.cc
- src/stirling/source_connectors/perf_profiler/perf_profile_connector.h
Summary: We implement some additional metrics for case where the profiler detects an overrun vs. the number of expected stack trace samples. Although this overrun may not cause issues (because of over-provisioning), we want to understand the magnitude and frequency of the issue so that we can re-assess our provisioning.
Test Plan: Existing tests. We know these metrics are reporting infrequent overruns, we expect to see more granular data after these new metrics roll out. Also, added some [verbose logging](https://phab.corp.pixielabs.ai/P400) to capture both expected values and actual values in the metrics. For this experiment, we lowered the provisioned number of stack traces to ensure that the overflow condition was triggered.
> `perf_profiler.cc|h`: Implment better metrics for overrun of expected number of stack trace samples.

- .github/actions/env_protected_pr/action.yaml
Summary: Typo in action file causes build to fail on main.
Test Plan: Test on main
> [build] Fix build on main

- .github/actions/gcloud_creds/action.yaml
- .github/workflows/cli_release.yaml
- .github/workflows/cloud_release.yaml
- .github/workflows/operator_release.yaml
- .github/workflows/vizier_release.yaml
Summary: Uses remote buildbuddy execution for release actions.
Test Plan: Tested all release workflows with RCs.
> [actions] Use remote buildbuddy execution for release builds

- .github/workflows/trivy_images.yaml
Summary: Uses remote buildbuddy execution for trivy image scan actions.
Test Plan: Tested on my fork that the pull_request_target works, also testing in this PR with a temporary pull_request.
> [actions] Use remote buildbuddy execution for trivy_images action

- src/carnot/planner/objects/pixie_module.cc
- src/carnot/planner/objects/pixie_module.h
Summary: Ensure the `px.format_duration` pxl function has its doc string set
When working on #1407 I noticed that the docs.px.dev site didn't include the `px.format_duration` function despite being updated recently. This change addresses the issue causing the missing docs. Rather than updating the docs.px.dev site manually, I'll wait to propagate this change to that repo once #1408 is complete.
Test Plan: Verified that the function exists in the documentation json file ([P401](https://phab.corp.pixielabs.ai/P401))
> Ensure the `px.format_duration` pxl function has its doc string set

- k8s/devinfra/buildbuddy-executor/values.yaml
Summary: Add memory limits to buildbuddy executor deployments.
Test Plan: Tested by deploying buildbuddy executor.
> [buildbuddy-executor] Add memory limits

- src/common/testing/test_utils/container_runner.cc
- src/common/testing/test_utils/container_runner.h
Summary: With qemu and lack of network access, we expect all images
to be pulled by bazel and available as runfiles for tests. So we can
drop the support for pulling images in container_runner.
Test Plan: All builds and tests continue to work.
> Remove unused image pull support in container_runner

- .bazelrc
- ci/collect_coverage.sh
Summary: Fix coverage build when running on remote executors.
Test Plan: Tested that `./ci/collect_coverage` works now
> [build] Fix coverage on remote

- .github/actions/env_protected_pr/action.yaml
- .github/workflows/trivy_images.yaml
Summary: The upload sarif action requires both sha and ref if either are provided.
Test Plan: N/A
> [trivy] Provide sha as well as ref

- .github/workflows/trivy_fs.yaml
- .github/workflows/trivy_images.yaml
Summary: Only run trivy images on main. I gave the sarif upload's categories so hopefully the trivy-fs and trivy-images will be considered separate by github.
Test Plan: Testing in this PR to see if trivy-fs will still show as missing configurations.
> [trivy] Only run trivy-images action on main

- .github/workflows/trivy_fs.yaml
- .github/workflows/trivy_images.yaml
Summary: Change the trivy tool names so that `trivy-images` and `trivy-fs` are treated as separate code scanning tools. This makes the PR checks not complain about missing code scanning configurations.
Test Plan: Tested with this PR, saw that code scanning no longer complains about missing configurations.
> [trivy] Change tool name

- bazel/container_images.bzl
- src/stirling/source_connectors/socket_tracer/testing/container_images/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/testing/container_images/nginx_openssl_3_0_8_container.h
- src/stirling/source_connectors/socket_tracer/testing/containers/BUILD.bazel
Summary: I accidentally named the 3.0.8 image with casing that was
inconsistent with all the other images in #1424
This fixes the same.
Test Plan: All the affected tests pass.
> Fix naming for nginx 3.0.8 image

- .github/workflows/release_update_docs_px_dev.yaml
Summary: Add github action for updating autogenerated pxl and python api docs
Test Plan: The following PR was successfully created with the missing docs https://github.com/pixie-io/docs.px.dev/pull/261 and verified the following:
```release-notes
Automatically create pull requests to update the pxl and python api documentation on docs.px.dev 
```
> Add github action for updating autogenerated pxl and python api docs

- src/pxl_scripts/px/http_trace_id/script.pxl
Summary: Replace duration calculation in http_trace_id script with `px.format_duration`
The `px.format_duration` function was added in https://github.com/pixie-io/pixie/pull/1256, but the http_trace_id pxl script was not updated since end users must upgrade in order to get access to that function. It's been one month since that change was made, so let's update the pxl script to use the new function.
Test Plan: Used the pxl scratch pad to verify that the time window is 2x'ed and rounded down to nearest whole number upon deep linking (35m x 2 = 70m -> 1h)
> Replace duration calculation in http_trace_id script with `px.format_duration`

- bazel/container_images.bzl
Summary: This swaps out some of our container images for smaller
versions of the same by picking Debian `slim` or `alpine` based
images instead of ones that include the full debian distro.
This shouldn't affect test coverage but speeds up runs by
reducing the size of the images being downloaded and sent to QEMU.
Test Plan: All of the affected tests continue to pass.
> Use smaller versions of some test images

- .github/workflows/trivy_images.yaml
Summary: Trivy images wrongly assumed a single sarif file for changing the tool name. This fixes that bug.
Test Plan: Testing by temporarily enabling trivy-images on this PR.
> [trivy] Fix trivy-images

- bazel/BUILD.bazel
- k8s/devinfra/buildbuddy-executor/values.yaml
Summary: Updating the bb remote exec pool name to use the latest images. I'm running an extra pool of executors on px-dev-infra in the meantime to allow for both pools during the transition. I will then upgrade the equinix pool and teardown the px-dev-infra one.
Test Plan: Testing the new pool in this PR.
> [bb-executor] Update pool to latest images

- .github/workflows/perf_common.yaml
Summary: Uses the remote buildbuddy executors to run bazel builds for perf experiments.
Test Plan: Tested by pushing a branch and [manually triggering](https://github.com/pixie-io/pixie/actions/runs/5191523093). Cancelled it before the last one finished because I tore down the executors it was running on but it clearly works if the other 5 experiments were passing.
> [actions] Use remote buildbuddy execution for perf actions

- k8s/vizier_deps/base/etcd/etcd_statefulset.yaml
- tools/docker/Makefile
- tools/docker/etcd_image/Dockerfile
Summary: We need the busybox tools for the etcd setup scripts etc
but don't really need alpine. This change makes the etcd image
distroless but includes the static musl based busybox tools so that
the init, healthcheck etc scripts continue to work.
Relevant Issues: Partially addresses #1363
Test Plan: Deployed new etcd image to cluster via kustomize and ensured
that it came up successfully.
> Update etcd image to include busybox tools but not use alpine

- src/carnot/funcs/metadata/metadata_ops_test.cc
Summary: These tests use the same metadata state and the duplicate
construction of the state makes it difficult to keep track of the
state and update it.
Test Plan: The metadata_ops_test still passes.
> Cleanup metadata_state dupes in test

- src/common/testing/event/simulated_time_system.cc
- src/common/testing/event/simulated_time_system.h
- src/vizier/services/agent/pem/tracepoint_manager_test.cc
- src/vizier/services/agent/shared/manager/heartbeat_test.cc
- src/vizier/services/agent/shared/manager/k8s_update_test.cc
- src/vizier/services/agent/shared/manager/registration_test.cc
Summary: This adds a constructor for SimulatedTime that uses a default
timestamp. It also makes the SetMonotonicTime and SetSystemTime methods
private and updates the tests to use the Sleep method to update the clock.
This allows the tests to not need to keep track of the current_time
and makes it simpler to bump the clock.
Test Plan: All the existing tests that use the SimulatedTime and the
unit tests for the SimulatedTime provide coverage.
> Update SimulatedTimeSystem to simplify it's usage in tests

- .bazelrc
- src/stirling/source_connectors/socket_tracer/uprobe_manager.cc
Summary: Enable TLS tracing python interpreters linked with libpython
Relevant Issues: Fixes #1347
Test Plan: `openssl_trace_bpf_test`'s Python 3.10 test case passes, which covers this scenario
```release-note
Enhance TLS tracing to support Python interpreters that link libpython
```
> Enable TLS tracing python interpreters linked with libpython

- src/carnot/udf/udf_definition.h
- src/carnot/udf/udf_definition_test.cc
- src/carnot/udf/udf_wrapper.h
Summary: In preparation for implementing partial aggregates on the exec side, this PR adds Serialize/Deserialize methods to the UDADefinition. This will allow the exec side to execute udas' Serialize and Deserialize methods in a type erased way, just as we do for Update, Merge, Finalize, etc.
Relevant Issues: #1440
Test Plan: Added a test for the SerializeArrow and Deserialize methods. Also tested as part of broader partial aggregate implmentation.
> [carnot] Add Serialize/Deserialize to UDFDefinition

- src/carnot/plan/operators.cc
- src/carnot/plan/operators.h
- src/carnot/planner/distributed/splitter/partial_op_mgr/partial_op_mgr.cc
- src/carnot/planner/distributed/splitter/partial_op_mgr/partial_op_mgr_test.cc
- src/carnot/planner/distributed/splitter/splitter_test.cc
- src/carnot/planner/ir/blocking_agg_ir.cc
- src/carnot/planpb/test_proto.h
Summary: Prior to this change, the compiler would output a single column called `serialized_expressions` for any partial agg. This isn't particularly convenient for the execution side. Instead, the compiler will now output a column per UDA involved in the agg node. For example, if you have an agg node that has a `min` and `max` output the partial agg will now output two columns (plus any group columns) called `serialized_min` and `serialized_max`, where before it would output an unspecified `serialized_expressions` column.
Relevant Issues: #1440
Test Plan: Modified existing tests to test the new behaviour. Also tested as part of broader partial aggregate changes.
> [carnot] Output column per UDA in a partial aggregate

- src/carnot/funcs/metadata/BUILD.bazel
- src/carnot/funcs/metadata/metadata_ops_test.cc
- src/experimental/standalone_pem/standalone_pem_manager.cc
- src/shared/metadata/BUILD.bazel
- src/shared/metadata/metadata_state.cc
- src/shared/metadata/metadata_state.h
- src/shared/metadata/metadata_state_test.cc
- src/shared/metadata/standalone_state_manager.cc
- src/shared/metadata/standalone_state_manager.h
- src/shared/metadata/state_manager.cc
- src/shared/metadata/state_manager.h
- src/shared/metadata/state_manager_test.cc
- src/stirling/e2e_tests/stirling_wrapper_size_test.cc
- src/vizier/services/agent/shared/manager/manager.cc
- src/vizier/services/agent/shared/manager/test_utils.h
Summary: Using a TimeSystem instead of directly calling the system
clock allows us to use a simulated clock for tests.
This already exists on the Manager base class, and needed to be
threaded into the AgentMetadataState.
Test Plan: All the existing tests pass. The metadata_state tests
are now a bit cleaner.
> Inject an overrideable TimeSystem into the AgentState

- src/ui/BUILD.bazel
Summary: The UI build seems unstable on the remote executors and
flakes sometimes. Let's just try to make it build locally at all
times.
Type of change: /kind devinfra
Test Plan: Check build runs on this PR.
> Make UI build not use remote executors

- src/ui/src/components/version-info/version-info.tsx
- src/ui/src/utils/env.tsx
- src/ui/webpack.config.js
Summary: Now that we use semver for cloud builds, we can use the
STABLE_BUILD_TAG to include the semver and not rely on the commit
hash.
Test Plan: skaffold a dev cloud
> Update version info in UI build

- .bazelrc
Summary: tcmalloc was causing strange linker errors with CGO builds when linker with gold. Not really sure what's going on, since lld can link these things without issue. We should probably investigate this more, but for now this is a stop-gap that will unblock the coverage build. Since we don't ever deploy GCC built binaries, removing tcmalloc shouldn't matter too much for now.
Test Plan: Ran `bazel build //src/vizier/services/query_broker:query_broker --config=gcc` without error, this was failing on main before this PR.
> [build] Disable tcmalloc for GCC build

- src/shared/metadata/metadata_state.cc
- src/shared/metadata/metadata_state.h
- src/shared/metadata/metadata_state_test.cc
Summary: This tracks a IP to Pod map by start time in the agent
metadata state allowing us to lookup the historic state of which
IP corresponds to which pod.
Relevant Issues: #885
Test Plan: Added a unit test.
```release-note
We now track all pods (in the last 24hrs) that use a given cluster IP
address instead of just the last pod to use a particular IP address.
```
> Add time based IP to Pod tracking to agent metadata

- src/cloud/plugin/controllers/server.go
Summary: To allow for an audit trail in Pixie, we were suggested to add logging for when plugins are enable/disabled. Added some logging in the plugin service.
Test Plan: No functionality change, just adds logging
> Add logging for when plugins are enabled/disabled

- src/cloud/vzmgr/deployment/BUILD.bazel
- src/cloud/vzmgr/deployment/deployment.go
- src/cloud/vzmgr/deployment/deployment_test.go
- src/cloud/vzmgr/deploymentkey/deployment_keys.go
- src/cloud/vzmgr/deploymentkey/deployment_keys_test.go
Summary: We were recommended to add logging for when a Vizier registers. This is useful for auditing, so users can track when/who/how Viziers were registered to an org.
Test Plan: Unit tests
> Add logging for when Vizier registers

- src/ui/src/api/api-context.tsx
- src/ui/src/api/api-manager.ts
- src/ui/src/containers/App/live.tsx
Summary: Moving PixieAPIManager out of React's scope was a risky move.
As it turns out, PixieAPIContext wasn't catching one of the updates during the embed authentication procedure because of this.
By implementing an unholy hack to tell React when this happens, the `authorized` network call still fires with a bearer token.
Test Plan: Try to embed Pixie using `embedPixieToken` to authenticate. Before, it would give up trying right before the `postMessage` comes through. After, it should try once more as soon as the auth token is provided to Pixie.
> Fix an update issue caused by React being out of scope at a bad time

- src/shared/metadata/metadata_state.cc
Summary: This map copy was missed in #1445 which caused the ip_by_time
map to reset on every clone. Now it is maintained across clones.
Relevant Issues: #885
Test Plan: Tested with a skaffolded vizier.
> Ensure that pods_by_ip_and_start_time_ is carried over in metadata state clones

- src/carnot/funcs/metadata/metadata_ops.cc
- src/carnot/funcs/metadata/metadata_ops.h
- src/carnot/funcs/metadata/metadata_ops_test.cc
- src/shared/k8s/metadatapb/test_proto.h
Summary: This adds a UDF to resolve IP to Pod given the time of the trace.
This UDF uses the newly added `pods_by_ip_and_start_time_` tracker to
do the resolution and can handle IPs being reused in a cluster.
Relevant Issues: #885
Test Plan: Added unit tests for the UDF. Did some end-to-end testing
on a cluster with a skaffolded vizier and a limited IP range and a
cronjob to spam pods.
> Add UDF to convert IP to Pod given a trace time

- src/datagen/pii/privy/privy/analyze.py
- src/datagen/pii/privy/privy/generate/generate.py
- src/datagen/pii/privy/privy/generate/truncate.py
- src/datagen/pii/privy/privy/generate/utils.py
- src/datagen/pii/privy/privy/generate/visualize.py
- src/datagen/pii/privy/privy/hooks.py
- src/datagen/pii/privy/privy/payload.py
- src/datagen/pii/privy/privy/providers/english_us.py
- src/datagen/pii/privy/privy/providers/generic.py
- src/datagen/pii/privy/privy/providers/german_de.py
- src/datagen/pii/privy/privy/route.py
- src/datagen/pii/privy/privy/sql.py
- src/datagen/pii/privy/privy/tests/test_json.py
- src/datagen/pii/privy/privy/tests/test_providers.py
- src/datagen/pii/privy/privy/tests/test_sql.py
- src/datagen/pii/privy/privy/tests/utils.py
- src/datagen/pii/privy/privy/train/flair_ner.py
Summary: Run `isort` to organize the imports and make it a bit more
clear as to which imports are third party deps.
Type of change: /kind clenaup
Test Plan: This change should be a noop.
> Run isort on privy imports

- src/ui/BUILD.bazel
Summary: After the fixes in #1455, I'm hoping that remote
exec works for UI builds again. This tries to re-enable it.
Test Plan: Check results on build run for this PR.
> Bring back remote exec for UI builds

- .github/workflows/trivy_images.yaml
Summary: This prevents BES upload failures from causing a action failure.
Test Plan: Trivy images shouldn't fail on main after this.
> Run trivy_images using bazel wrapper script

- src/operator/controllers/monitor.go
Summary: This switches to using the CA from the cluster certs
when monitoring vizier instead of skipping TLS Verify.
Test Plan: skaffolded an operator and verified that it got the
CA and used it.
```release-note
The Pixie Operator monitor now uses the Vizier CA in it's TLS Config
when making connections to NATS and CloudConn to check their status.
```
> Use service-tls CA in operator when monitoring vizier

- src/carnot/funcs/builtins/BUILD.bazel
- src/carnot/funcs/builtins/builtins.cc
- src/carnot/funcs/builtins/pprof_ops.cc
- src/carnot/funcs/builtins/pprof_ops.h
- src/carnot/funcs/builtins/pprof_ops_test.cc
- src/shared/pprof/pprof.cc
Summary: We add a new UDA that converts profiling data to pprof protobuf format.
Long term, we see this as useful in several scenarios:
1. For OTel export (it seems likely that OTel will add profiling data and include pprof as a supported wire format).
2. For general purpose download, e.g. a user wants to directly download profiling data in pprof format.
Test Plan: Added a new test `pprof_test` into `src/carnot/funcs/builtins`. The new test covers both the UDA and its underlying serialize and deserialize methods found in `src/shared/pprof`.
> Add a UDA for converting profiling data to pprof protobuf format.

- .github/actions/env_protected_pr/action.yaml
- .github/workflows/build_and_test.yaml
Summary: TSIA. This ensures that the `build-and-test` action runs
on the new image when running on a PR that bumps the image.
Type of change: /kind devinfra
Test Plan: Check the github actions run on a PR that bumps the docker
tag.
> Use the ref from env-protect-setup to get the docker image tag

- src/shared/artifacts/manifest/json.go
- src/shared/artifacts/manifest/manifest_test.go
Summary: Allow unknown fields in the artifact manifest. This is in preparation for changes to the manifest format, which will add a field. This PR ensures that clouds that are unaware of the new changes to the format, won't error when trying to decode the manifest.json.
Test Plan: Added a test that ensures that the new manifest field can be in the manifest, and it can still be successfully decoded.
> [artifacts] Allow unknown fields in the artifact manifest

- src/operator/controllers/monitor.go
- src/operator/controllers/monitor_test.go
- src/utils/shared/k8s/BUILD.bazel
- src/utils/shared/k8s/dns_addr.go
- src/utils/shared/k8s/dns_addr_test.go
- src/vizier/services/cloud_connector/vzmetrics/scrape.go
Summary: Using the pod advertised DNS addr instead of the IP address
ensures that the SSL cert is valid and that we can scrape with TLS.
Relevant Issues: Followup to a breakage caused by #1480
Test Plan: skaffold the operator to test.
> Use pod dns addrs instead of IPs to check status

- .github/workflows/operator_release.yaml
- ci/operator_helm_build_release.sh
Summary: Originally the path was just `helm_chart/index.yaml`. However if we name it `helm_charts/operator/index.yaml`, then we can potentially add more helm charts in the future.
Test Plan: Build runs
> Rename operator helmchart directory

- .github/workflows/release_update_docs_px_dev.yaml
Summary: Fix bug preventing GitHub action for pxl documentation updates from running
There was a vizier release today and the GitHub workflow [triggered](https://github.com/pixie-io/pixie/actions/runs/5272284093) from that was skipped. I believe this was because the `github.ref` field was likely prefixed with `refs/tags`. This change relaxes the criteria for the check to ensure that it matches on future vizier releases.
Test Plan: Looked at the [GitHub docs](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) to see what the `github.ref` context would be populated with
> Fix bug preventing GitHub action for pxl documentation updates from running

- k8s/cloud/base/ory_auth/kratos/kratos_config.yaml
Summary: By default Kratos has some pretty strict password settings: https://github.com/pixie-io/docs.px.dev/pull/258 which may make it harder for some users to try out the control plane.
Users can easily edit the settings to make them more strict if needbe, however we should make the defaults easy-to-use.
Test Plan: Kustomize build
> Update default password settings for Kratos

- bazel/container_images.bzl
Summary: Bumps the base alpine version and included OpenSSL version
to address a CVE.
Relevant Issues: CVE-2023-2650
Test Plan: cloud proxy should still work.
> Bump openresty to address CVE

- go.mod
- go.sum
- go_deps.bzl
Summary: Upgrading pgx drops the dependency on `github.com/satori/go.uuid`
which in turn addresses a CVE.
Relevant Issues: CVE-2021-3538
Test Plan: All existing tests pass. The pgx changelog doesn't indicate any
significant changes.
> Upgrade pgx

- src/cloud/auth/auth_server.go
Summary: We support `oidc` based auth too and have done so for a while.
However this flag wasn't updated, so update it to reflect `oidc` support.
Test Plan: Running the auth server with a help flag should show the new
help text.
> Update stale flag description for the auth service

- .arclint
- .golangci.yaml
Summary: `golint` is archived and deprecated. `golangci-lint` suggests
using `revive` instead.
`deadcode` and `varcheck` are covered by `unused` instead.
Test Plan: Ran the linters, they seem to work. Will fix newly
found issues as a followup.
> Replace deprecated linters

- src/stirling/source_connectors/socket_tracer/testing/containers/thriftmux/byteman_rule.txt
Summary: Delete byteman file no longer used for by `netty_tls_trace_bpf_test`
This was cleanup that was missed in #606.
Test Plan: `netty_tls_trace_bpf_test` still passes
> Delete byteman file no longer used by `netty_tls_trace_bpf_test`

- bazel/repository_locations.bzl
Summary: Upgrade rules_jvm_external to address maven install bugs
The thriftmux container used in the `netty_tls_trace_bpf` test previously ran into https://github.com/bazelbuild/rules_jvm_external/issues/686. This required us to manually install maven dependencies and override things to break the dependency loop (see TODO and `fetch_netty_tcnative_jars` from https://github.com/pixie-io/pixie/pull/562). This issue was fixed in rules_jvm_external v4.3, however, I opted to bump this to the latest version.
After this is merged, I will follow up with the netty dependency install cleanup.
Test Plan: Verified that `netty_tls_trace_bpf_test` containers avoid maven install issue and that antlr grammar builds and carnot tests pass (`bazel build …
> Upgrade rules_jvm_external to address maven install bugs

- src/vizier/utils/datastore/datastore_test.go
- src/vizier/utils/datastore/pebbledb/pebbledb.go
- src/vizier/utils/datastore/pebbledb/pebbledb_utils.go
- src/vizier/utils/datastore/pebbledb/pebbledb_utils_test.go
Summary: `golang` supports fuzz testing as of go `1.18`.
This adds a couple of simple fuzz tests to serve as an
example of how we can use fuzzing.
Type of change: /kind testing
Test Plan: Newly added tests run normally and also under
fuzzing.
> Add some inital fuzz tests for datastore

- src/utils/shared/yamls/templates.go
- src/utils/template_generator/vizier_yamls/vizier_yamls.go
Summary: Before adding the operator, we used to push Helm charts for Vizier. Since the introduction of the operator helm charts, we neglected maintenance and testing of the old Vizier helm charts. After doing some testing, these charts were very close to working properly minus two issues:
- When adding autopilot mode, we needed to wrap the autopilot YAMLs with a check for whether autopilot is enabled. Otherwise, these YAMLs would be deployed every time regardless of whether autopilot is enabled or not.
- We added some templating for customRegistries. When generating the template YAMLs, we iterate through each of the images and templatize the image paths to support custom registries. At this point, we are processing the resources as JSONs. However, when we convert these JSONs to YAMLs, …
> Fix Vizier Helm templates

- src/ui/src/containers/admin/cluster-details.tsx
- src/ui/src/containers/admin/clusters-list.tsx
- src/ui/src/containers/admin/utils.tsx
- src/ui/src/pages/admin/admin.tsx
- src/ui/src/pages/live/live.tsx
Summary: Fixes a few alignment and spacing issues in the cluster list table.
Moves the details of a cluster into a modal instead of a separate page.
Another PR will be created for each details tab, to improve their look and feel too.
Cluster list now has limited width, doesn't align titles strangely anymore.
Details now open in a modal with tabs.
Test Plan: Open `/admin`. Use the clusters table. Click a cluster for details. Click the tabs within the modal that comes up. Try scrolling in the modal.
> Refresh cluster list look and feel

- src/cloud/auth/controllers/login.go
Summary: We currently throw a "PermissionDenied" error if a user already exists. However, a "AlreadyExists" error is more accurate.
Test Plan: Existing tests pass
> Throw more accurate error if trying to create existing user

- src/cloud/api/BUILD.bazel
- src/cloud/artifact_tracker/BUILD.bazel
- src/cloud/auth/BUILD.bazel
- src/cloud/config_manager/BUILD.bazel
- src/cloud/cron_script/BUILD.bazel
- src/cloud/indexer/BUILD.bazel
- src/cloud/metrics/BUILD.bazel
- src/cloud/plugin/BUILD.bazel
- src/cloud/plugin/load_db/BUILD.bazel
- src/cloud/profile/BUILD.bazel
- src/cloud/project_manager/BUILD.bazel
- src/cloud/scriptmgr/BUILD.bazel
- src/cloud/vzconn/BUILD.bazel
- src/cloud/vzmgr/BUILD.bazel
- src/operator/BUILD.bazel
- src/utils/cert_provisioner/BUILD.bazel
- src/utils/pixie_deleter/BUILD.bazel
- src/utils/pixie_updater/BUILD.bazel
- src/vizier/services/agent/kelvin/BUILD.bazel
- src/vizier/services/agent/pem/BUILD.bazel
- src/vizier/services/cloud_connector/BUILD.bazel
- src/vizier/services/metadata/BUILD.bazel
- src/vizier/services/query_broker/BUILD.bazel
Summary: We build and push most of our distributed images using
container bundles. We use skaffold to test local dev builds. So
these one off push targets are unused and increase maintenance
burden. Instead just remove them.
Test Plan: All existing builds and deploys work.
> Remove one off container push targets

- src/e2e_test/jetstream_loadtest/k8s/publisher_deployment.yaml
- src/e2e_test/jetstream_loadtest/k8s/subscriber_deployment.yaml
- src/e2e_test/jetstream_loadtest/publisher/BUILD.bazel
- src/e2e_test/jetstream_loadtest/skaffold_loadtest.yaml
- src/e2e_test/jetstream_loadtest/subscriber/BUILD.bazel
- src/e2e_test/profiler_loadtest/go/BUILD.bazel
- src/e2e_test/profiler_loadtest/k8s/go_loadtest_deployment.yaml
- src/e2e_test/profiler_loadtest/skaffold_loadtest.yaml
- src/e2e_test/protocol_loadtest/BUILD.bazel
- src/e2e_test/protocol_loadtest/client/BUILD.bazel
- src/e2e_test/protocol_loadtest/k8s/client/client_deployment.yaml
- src/e2e_test/protocol_loadtest/k8s/server/server_deployment.yaml
- src/e2e_test/protocol_loadtest/skaffold_client.yaml
- src/e2e_test/protocol_loadtest/skaffold_loadtest.yaml
- src/pixie_cli/BUILD.bazel
Summary: The container push targets for the e2e tests rely on a hardcoded
registry that folks might not have access to push to. Instead we can
switch to relying on skaffold to build the images, replace them in the k8s
yamls and deploy them as needed.
While this makes the yamls for these k8s tests not deployable via just
kustomize (since the referenced images don't exist), IMO it cleans things
up by relying on just having one way to run the tests (via skaffold).
Test Plan: Skaffolded an e2e test and ensured that it was built
and deployed to my cluster.
> Remove some more container_push targets

- src/utils/artifacts/versions_gen/BUILD.bazel
- src/utils/artifacts/versions_gen/main.go
Summary: Adds support to `versions_gen` to allow backfilling manifests with download links to artifacts. It will now read the `artifact_mirrors.yaml` file, to decide where to look for artifacts. Then it will add download links to the manifest's `available_artifact_mirrors` fields, for any artifacts it finds in the expected mirror locations. This will be used in a one off way to create the gh-pages manifest from scratch with the new style (`available_artifact_mirrors` instead of `available_artifacts`). Also, backwards compatibility is maintained so the GCS manifest can still be updated in the old format.
Test Plan: Tested by running `versions_gen` pointing to `artifact_mirrors.yaml`. Saw that the manifest had the correct download links including some links to …
> [versions_gen] Support backfilling release manifests with links to artifacts.

- .github/workflows/vizier_release.yaml
- ci/helm_build_release.sh
- ci/vizier_build_release.sh
Summary: Our Vizier Helm chart now works again. This updates our build so that it builds the Helm chart and publishes it to our gh-pages.
We used to write our helm charts to GCS, however since we haven't maintained/publicized these charts + we are renaming the chart, I cleaned that up and move straight to gh instead.
Relevant Issues: #1350
Test Plan: Create an rc and inspect the build
> Publish Vizier helm charts to release build

- bazel/cc_toolchains/sysroots/sysroots.bzl
- tools/docker/Makefile
- tools/docker/sysroot_creator/package_groups/test.yaml
Summary: Add `iproute2` to test sysroot to install `tc` cli
This is a prerequisite for creating network interfaces that will exhibit packet delays during bpf tests via a `netem` qdisc. This will allow us to improve test coverage for the tcp stats source connector by causing tcp retransmissions to occur within the test.
While `busybox` does include a `tc` command, I believe it doesn't support the `tc qdisc add` command. See test plan below to see the error caused when using busybox's version. I also looked at busybox's source code and it doesn't appear to handle the `add` command from what I can tell. I don't see any documentation that confirms this suspicion, but using the `iproute2` version works as expected.
If there aren't concerns with this change, I will need assistance with pushing …
> Add `iproute2` to test sysroot to install `tc` cli

- .github/workflows/release_update_docs_px_dev.yaml
- .github/workflows/release_update_readme.yaml
Summary: Only run the release triggered jobs on actual releases, instead of also on prereleases.
Test Plan: N/A
> [actions] Do not run release triggered actions on prereleases

- src/ui/src/containers/admin/cluster-details/cluster-details-pods.tsx
- src/ui/src/containers/admin/cluster-details/cluster-details-utils.ts
Summary: See screenshots
Before...
After...
Test Plan: `/admin/clusters`, open a cluster that doesn't have a lot going on, go to pods tab.
> Fix min height of heading in admin pods

- src/ui/src/containers/admin/admin-overview.tsx
- src/ui/src/containers/admin/invite-user-button.tsx
- src/ui/src/containers/admin/keys-overview.tsx
- src/ui/src/containers/admin/org-users.tsx
Summary: Admin buttons were floating in weird spots. Now they aren't.
Test Plan: Load `/admin/keys` and `/admin/users`. The buttons in the top right should no longer overlap other content weirdly.
> Fix positioning of extra admin tab buttons

- src/ui/src/containers/admin/admin-overview.tsx
- src/ui/src/containers/admin/clusters-list.tsx
Summary: Moves the error/loading text to the center, and doesn't hide already-loaded clusters when refreshing the list.
First load...
Refreshing...
Test Plan: Load `/admin/clusters`. Wait about a minute for the automatic refresh.
> Prettier cluster loading state

- .github/workflows/cli_release.yaml
- .github/workflows/operator_release.yaml
- .github/workflows/vizier_release.yaml
- ci/artifact_mirrors.yaml
- ci/artifact_utils.sh
- ci/cli_build_release.sh
- ci/cli_upload_signed.sh
- ci/operator_build_release.sh
- ci/vizier_build_release.sh
Summary: Keep track of each upload to a mirror of artifacts. Create a manifest_updates.json based on the uploads, and then update the github pages manifest based on these updates.
Test Plan: Tested the vizier and operator releases. The CLI release is blocked on problems with Apple, will test that once unblocked.
```release-note
The artifact manifest is now hosted on github pages instead of GCS. This shouldn't be a noticable change for users who aren't doing anything custom with the artifact manifest.
```
> [artifact manifest] Generate manifest updates from mirror uploads.

- tools/docker/nats_image/Dockerfile
Summary: Forgot to pin the builder image.
Test Plan: Rebuilt the image without pushing it. It still works.
> Pin builder for NATS image

- src/carnot/planner/objects/pixie_module.h
Summary: Add short description for format_duration pxl function documentation
This is to pull in an update that was made in this commit (https://github.com/pixie-io/docs.px.dev/pull/267/commits/0fd2b8b32e46e608469a36a08dcca36d505833e2).
Test Plan: Regenerated the docs and verified that there is only whitespace changes between github.com/pixie-io/docs.px.dev and the files generated from this repo
```
cd bazel-bin; ./src/carnot/docstring/docstring_/docstring
mv output.json ~/code/docs.px.dev/external/pxl_documentation.json
ddelnano@vigenere:~/code/docs.px.dev (main) $ git diff
diff --git a/external/pxl_documentation.json b/external/pxl_documentation.json
index dea613c..76f763b 100644
--- a/external/pxl_documentation.json
+++ …
```
> Add short description for format_duration pxl function documentation

- src/operator/controllers/vizier_controller.go
Summary: We were hearing reports where some user's clusters were switching to an etcd-based deploy after having already been deployed with the persistent-metadata version for a while. We should gate this check only for when we're deploying Vizier for the first time.
Test Plan: Skaffold deploy operator
> Operator should only switch users to etcd on initial deploy

- src/utils/artifacts/versions_gen/BUILD.bazel
- src/utils/artifacts/versions_gen/main.go
Summary: Fixes three bugs causing issues in the manifest generation.
- Fixes a bug where the tag's hash was used instead of the commit's hash
- Fixes another bug where dangling annotated tags would still show up in the manifest. For example, if I have an annotated tag `release/vizier/v0.0.0` and I run `git tag -d release/vizier/v0.0.0` and then re-run the release tag script `./scripts/create_release_tag.sh vizier`, my git state will have two annotated tag objects, but the tag reference will only point to one of them, and the other will just be an object not pointed to by any reference. Becuase we were using `TagObjects` in go-git, both of these tag objects would be returned leading to duplicate entries in the generated versions file. This PR fixes this issue by iterating tag references …
> [versions_gen] Fix 3 separate bugs in versions_gen.

- .github/workflows/mirror_releases.yaml
- .github/workflows/release_update_docs_px_dev.yaml
- .github/workflows/release_update_readme.yaml
Summary: Update mirror_release to only have `package: write` on the job
Remove some dupe `content: read` perms.
Test Plan: All the updated actions should continue to work.
> Scope down github token permissions

- bazel/cc_toolchains/sysroots/sysroots.bzl
- bazel/linux_headers.bzl
- bazel/pl_qemu_kernels.bzl
- bazel/repositories.bzl
- bazel/repository_locations.bzl
- scripts/create_release_for_dev_artifact.sh
- tools/chef/cookbooks/px_dev_extras/attributes/linux_debs.rb
- tools/docker/Makefile
Summary: We need to store our development artifacts somewhere other than gcs. This PR creates releases on the `pixie-io/dev-artifacts` repo, storing the artifacts in these releases. This prevents having random releases on the main repo, but still gives us a stable location for the dev artifacts.
Test Plan: Ran `bazel clean --expunge && bazel build //...`. Also relying existing tests.
> [dev artifacts] Create releases for development artifacts.

- src/stirling/testing/demo_apps/go_grpc_tls_pl/README.md
- src/stirling/testing/demo_apps/go_grpc_tls_pl/k8s/client_deployment.yaml
- src/stirling/testing/demo_apps/go_grpc_tls_pl/k8s/server_deployment.yaml
- src/stirling/testing/demo_apps/go_grpc_tls_pl/k8s/server_service.yaml
- src/stirling/testing/demo_apps/go_http/README.md
- src/stirling/testing/demo_apps/go_http/go_http_client/BUILD.bazel
- src/stirling/testing/demo_apps/go_http/go_http_server/BUILD.bazel
- src/stirling/testing/demo_apps/go_http/k8s/client_deployment.yaml
- src/stirling/testing/demo_apps/go_http/k8s/kustomization.yaml
- src/stirling/testing/demo_apps/go_http/k8s/server_deployment.yaml
- src/stirling/testing/demo_apps/go_http/k8s/server_service.yaml
- src/stirling/testing/demo_apps/go_http/skaffold.yaml
Summary: This updates the `go_http` demo to use skaffold to testing.
This makes it independent of the container registry and will now use
the default repo configured for skaffold to run the demo.
Also updates the `go_grpc_tls_pl` app to cleanup the kustomization,
update the readme and cleanup the image path.
Test Plan: Ran the deploy instructions in the README.md and verified
that they work.
> Setup/fix skaffold instructions for stirling demo_apps

- src/pixie_cli/install.sh
Summary: This script used to point to GCS for downloading artifacts for the CLI. This updates the script to instead use the artifacts from our GH releases.
Since we no longer tag/store the CLI under latest, this pulls from our README to get the latest version.
Also removed `px auth login`, since this can be confusing for users who have not yet input their `PX_CLOUD_ADDR`.
Test Plan: Run install.sh on Linux + Mac, to ensure we properly select the right artifact.
> Update install.sh to point to GH for CLI release artifacts

- src/ui/src/containers/admin/cluster-details/cluster-details.tsx
Summary: A wrong variable reference was causing "unknown cluster" to be selected instead of what the user clicked.
Test Plan: Visit `/admin/clusters`. Click one. In the dialog that comes up, use the dropdown in the top left to choose another.
Now, it should reload the dialog with info for the new cluster correctly.
> Fix dropdown selection in admin cluster detail view

- .github/workflows/mirror_deps.yaml
- bazel/container_images.bzl
- scripts/regclient/deps.lua
- scripts/regclient/regbot_deps.yaml
- scripts/regclient/utils.lua
- src/stirling/source_connectors/socket_tracer/testing/containers/mysql/README.md
- src/stirling/source_connectors/socket_tracer/testing/containers/mysql/update_ghcr.sh
- src/stirling/testing/demo_apps/py_grpc/README.md
- src/stirling/testing/demo_apps/py_grpc/update_ghcr.sh
- tools/docker/Makefile
Summary: Use regbot to sync container deps from various registries to
all our mirrors.
Use ghcr as the primary mirror to build.
Test Plan: `bazel build //...` and `bazel test //...`
Ran the regbot sync via a branch push trigger.
> Use ghcr.io for container dependencies

- src/stirling/source_connectors/socket_tracer/openssl_trace_bpf_test.cc
Summary: Remove debugging log message from `openssl_trace_bpf_test`
This seems to be left over from some previous build flakiness investigation.
Test Plan: Existing tests
> Remove debugging log message from `openssl_trace_bpf_test`

- .github/workflows/update_script_bundle.yaml
Summary: Adds a manually triggered action to update the script bundle stored in github pages.
Test Plan: Tested on my fork. Saw that it adds the bundle to gh-pages as expected. Also tested that a rerun of the workflow with no changes won't attempt an empty commit.
> [script bundle] Add action to update script bundle in gh-pages

- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
- src/stirling/source_connectors/socket_tracer/uprobe_manager.cc
- src/stirling/source_connectors/socket_tracer/uprobe_manager.h
Summary: Add stirling cli flag to opt into disabling Go TLS tracing
I'm investigating an issue where a Golang app is crashing with a segfault. The Pixie user is claiming that this crash doesn't occur with a PEM running v0.13.2 but does when running v0.13.7. The segfault is happening when their go application is calling `crypto/tls.(*Conn).Write`, so I wanted to add a mechanism for disabling Go TLS tracing to verify if that stabilizes their application.
Relevant Issues: Issue not created yet (waiting to confirm more details)
Test Plan: Existing test coverage passes and setting this flag to true within `go_tls_trace_bpf_test` results in test failures
> Add stirling cli flag to opt into disabling Go TLS tracing

- src/ui/package.json
- src/ui/yarn.lock
Summary: `semver` is a transitive dep for many packages that cannot
be upgraded or don't have newer version, so force a resolution to a
newer version.
Also remove unncessary resolution for multicast-dns.
Relevant Issues: CVE-2022-25883
Test Plan: Existing unit tests and smoke tests should provide coverage
> Pin semver to newer version

- k8s/cloud/base/script_bundles_config.yaml
- k8s/cloud/dev/script_bundles_config.yaml
- k8s/cloud/prod/script_bundles_config.yaml
- k8s/cloud/public/base/script_bundles_config.yaml
- k8s/cloud/staging/script_bundles_config.yaml
- k8s/cloud/testing/script_bundles_config.yaml
- src/cloud/api/api_server.go
- src/e2e_test/vizier/exectime/cmd/benchmark.go
- src/pixie_cli/pkg/cmd/script_utils.go
- src/pxl_scripts/Makefile
Summary: Switches CLI and cloud to use the github pages URL for the script bundle.
Test Plan: Tested all the effected components.
- Tested the exectime benchmark with the new bundle.
- Tested that `bazel run //src/pixie_cli:px -- run px/http_data` fetchs the script bundle and runs the script properly.
- Skaffolded testing cloud with the new URL, tested that scripts are still accessible in the UI, also checked that the bundle was pulled from the expected URL. Tried the command palette and it autocompleted scripts as expected.
> [script bundle] Use gh pages url for script bundle

- bazel/container_images.bzl
- scripts/regclient/deps.lua
- src/stirling/source_connectors/socket_tracer/conn_stats_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/testing/containers/BUILD.bazel
Summary: This switches our nginx OpenSSL 1.1.1 container to use a
alpine and musl based image.
This adds some coverage by now testing a libssl that is musl based
on a system that is glibc based and doesn't have musl installed (this
setup would fail with the old SSL tracing impl).
This also reduces the size of this particular container image giving
us minor boosts in test speed.
Test Plan: Ran all tests (bpf and regular), they all pass.
> Update openssl1_1_1 test to use a smaller alpine based container

- src/vizier/services/cloud_connector/bridge/server.go
- src/vizier/services/cloud_connector/bridge/vzinfo.go
Summary: This allows us to make changes to the image path for the updater
more easily.
Test Plan: Will test with a RC build.
> Update non operator upgrade to be a bit more robust to image paths

- src/ui/src/containers/admin/cluster-details/cluster-details-test.tsx
Summary: If this works, it will prevent the test from flaking on certain very fast Linux hosts.
Test Plan: `yarn coverage --no-cache`. May have to try many times.
> Make test less flaky

- bazel/external/boringssl.patch
- bazel/repositories.bzl
- src/cloud/config_manager/controllers/vizier_feature_flags.go
- src/stirling/source_connectors/socket_tracer/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/bcc_bpf_intf/common.h
- src/stirling/source_connectors/socket_tracer/boringssl_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/openssl_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
- src/stirling/source_connectors/socket_tracer/testing/container_images/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/testing/container_images/bssl_container.h
- src/stirling/source_connectors/socket_tracer/testing/containers/bssl/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/uprobe_manager.cc
- src/stirling/source_connectors/socket_tracer/uprobe_manager.h
Summary: Trace statically linked OpenSSL compatible TLS libraries
This adds a feature toggle for enabling TLS tracing applications statically linked with an OpenSSL compatible library. The plan is to enable this for internal clusters for 1 week before enabling it for all users (and making it the default).
We originally intended to add these probes for BoringSSL applications, however, detecting BoringSSL is more difficult than anticipated. One of the reliable indicators, checking for BoringSSL's [magic tag](https://github.com/google/boringssl/commit/89386ac89bef26888b8d866ebb98b696d82dfde8), is only available if an application is using a BoringSSL from Oct 2021 or later and from checking the following dependencies (different envoy distributions, Clickhouse, the Mono runtime, …
> Trace statically linked OpenSSL compatible TLS libraries

- ci/collect_coverage.sh
- src/ui/jest.config.js
Summary: The file sizes and offsets reported for the UI coverage
in codecov were incorrect, this fixes them.
Test Plan: Ran the coverage build locally and looked at the generated
lcov output.
> Fix UI coverage reporting on codecov

- src/cloud/config_manager/controllers/vizier_feature_flags.go
Summary: Fix misspelling of `PX_TRACE_STATIC_TLS_BINARIES` PEM flag
Test Plan: grep'ed to make sure the flag is consistent with stirling's flag
```
ddelnano@vigenere:~/code/pixie (ddelnano/attempt-to-reproduce-amqproxy-issue) $ git grep PX_TRACE_STATIC_TLS_BINARIES
src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc:    stirling_trace_static_tls_binaries, gflags::BoolFromEnv("PX_TRACE_STATIC_TLS_BINARIES", false),
```
> Fix misspelling of `PX_TRACE_STATIC_TLS_BINARIES` PEM flag

- src/ui/jest.config.js
- src/ui/src/pages/setup/__snapshots__/setup-test.tsx.snap
- src/ui/src/pages/setup/setup-test.tsx
- src/ui/src/pages/setup/setup.tsx
- src/ui/src/testing/mocks/org-context-mock.tsx
- src/ui/src/testing/mocks/sidebar-context-mock.tsx
- src/ui/src/testing/mocks/user-context-mock.tsx
- src/ui/src/testing/style-mock.js
- src/ui/src/utils/env.tsx
Summary: This takes coverage for `pages/setup.tsx` from 0% to 100% (though there are some uncovered branches).
Also adds marginal coverage to the sidebar, footer, topbar as a sideeffect from the snapshot test.
Type of change: /kind test
Test Plan: Ran the test with yarn.
> Add tests for the Org Setup page

- .bazelrc
- .gitignore
- ci/collect_coverage.sh
Summary: gcov doesn't collect branch coverage by default and lcov
drops branch coverage from the files if it exists.
This change ensures that we maintain and track branch coverage.
Test Plan: Ran the coverage build and then the coverage cleanup
script. Ensured that it now maintains branch coverage.
> Collect and maintain branch coverage

- src/common/testing/test_utils/container_runner.cc
Summary: This fixes a warning from `-Wsign-compare`
Test Plan: bazel build should no longer warn about this comparison.
> Address compiler warning

- k8s/slackin/README.md
- k8s/slackin/deployment.yaml
- k8s/slackin/ingress.yaml
- k8s/slackin/ingress_no_tls.yaml
- k8s/slackin/service.yaml
Summary: Updates the slackin instructions to use the new image registry.
Also adds details to configure a cert-manager and ingress.
Test Plan: Deployed it on the equinix cluster
> Update instructions for slackin

- k8s/vizier/bootstrap/updater_role.yaml
Summary: The role refactors in ff26221 and then later 87b7751 caused us to drop some ClusterRoles that the updater relied on to upgrade viziers that don't have an operator. I believe the initial breakage was caused by ff26221 since it no longer included the necessary clusterrole, however it referenced an old clusterrole which meant that upgrades worked on clusters that had the old role. 87b7751 then removed the binding to the old seemingly non-existent clusterrole while then broke upgrades further. This attempts to add back the necessary permissions to unbreak such deploys.
Note that even with this change, I believe anyone running a non-operator deploy of vizier that was first deployed after v0.12.6 won't be able to auto-upgrade to any newer versions unless they manually patch the roles …
> Update updater roles necessary for non-operator based viziers

- .github/workflows/cli_release.yaml
- .github/workflows/operator_release.yaml
- .github/workflows/vizier_release.yaml
Summary: This should fix non-prerelease builds.
Test Plan: Ran the command locally.
> Fixup github release actions

- src/ui/src/containers/admin/api-keys.tsx
- src/ui/src/containers/admin/deployment-keys.tsx
- src/ui/src/containers/admin/key-list.tsx
- src/ui/src/containers/admin/keys-overview.tsx
- src/ui/src/containers/admin/org-settings.tsx
- src/ui/src/containers/admin/org-users.tsx
- src/ui/src/containers/admin/user-settings.tsx
Summary: TSIA. The Cluster List tab already had these styles, just making the rest match.
Test Plan: Visit the various `/admin` tabs. Now, they should all center their contents with the same max width as each other.
> Consistent widths and header styles for admin tabs

- src/vizier/services/metadata/controllers/k8smeta/BUILD.bazel
- src/vizier/services/metadata/controllers/k8smeta/k8s_metadata_controller.go
- src/vizier/services/metadata/controllers/k8smeta/k8s_metadata_controller_test.go
- src/vizier/services/metadata/controllers/k8smeta/k8s_metadata_utils.go
Summary: Add test for k8s_metadata_controller. This should exercise most of the go struct to metadatapb conversion code also.
Test Plan: New test passes.
> [k8smeta] Add test for k8s metadata controller

- k8s/cloud/base/artifact_config.yaml
Summary: The `PL_ARTIFACT_BUCKET` config was mistakenly removed in a previous change. This causes issues for users deploying self-hosted cloud.
Test Plan: Followed the self-hosted cloud install guide successfully.
> [artifact tracker] Add back artifact bucket config

- src/common/base/byte_utils.h
- src/common/base/byte_utils_test.cc
Summary: Make `LEndianBytesToInt` and `BEndianBytesToInt` compatible with `u8string_view`
In order to parse Go's buildinfo header, we need to convert bytes contained within a [u8string_view](https://github.com/pixie-io/pixie/blob/c092058a5172396ea9bead1e209c2ed4e2336943/src/common/base/byte_utils.h#L30-L31) (return values from [ElfReader](https://github.com/pixie-io/pixie/blob/c092058a5172396ea9bead1e209c2ed4e2336943/src/stirling/obj_tools/elf_reader.cc#L608)). This PR adds template specializations to the existing `LEndianBytesToInt` and `BEndianBytesToInt` functions so they are compatible with the `u8string_view` data type. This will allow the code that will eventually parse a Go buildinfo header to be cleaner by preventing an explicit conversion via `CreateStringView` as seen in [this …
> Make `LEndianBytesToInt` and `BEndianBytesToInt` compatible with `u8string_view`

- src/ui/jest.config.js
Summary: `src/ui/src/types/generated` is, well, generated code. Coverage reporting should not be counting the 6,000+ lines of code in there.
Test Plan: `yarn coverage`. The generated types should no longer count against the total.
> Skip coverage of generated UI code

- k8s/cloud/overlays/exposed_services_gclb/cloud_ingress.yaml
- k8s/cloud/prod/cloud_ingress_managed_cert_noslackin.yaml
- k8s/cloud/prod/kustomization.yaml
- k8s/cloud/staging/cloud_ingress_managed_cert_noslackin.yaml
- k8s/cloud/staging/kustomization.yaml
- k8s/cloud/testing/cloud_ingress_managed_cert_noslackin.yaml
- k8s/cloud/testing/kustomization.yaml
Summary: In order to prevent downtime while google reprovisions certificates, we need to stage out the removal of the slackin domain from the cloud managed certs. The goal being that there's always one valid cert that doesn't need to be reprovisioned for every new release. To achieve this, we stage it out into 3 stages:
1. Add a second cert without `slackin.*` domain, attach this cert to the ingress in addition to our original cert.
2. After releasing stage 1, remove `slackin.*` from the main cert.
3. Finally, we can remove the additional cert we added.
Test Plan: Tested each stage on `testing`. After each deploy testing still had a valid cert even if one of the two was reprovisioning.
> [cloud ingress] Remove slackin.* domains from certs in a safe, staged way (stage 1).

- src/vizier/services/metadata/controllers/k8smeta/k8s_metadata_controller.go
- src/vizier/services/metadata/controllers/k8smeta/k8s_metadata_utils.go
Summary: In clusters with lots of pods or nodes, there were some instances of metadata failing to start up.
It turns out that we were blocking on the `list`, which can take a long time depending on API latency/how many pods/nodes there are. Instead, we should wrap this in a goroutine, but make sure we wait for the pod/node list before starting the next watcher.
Relevant Issues: #1484
Test Plan: Skaffold, existing unit tests
> Don't block metadata startup on pod/node list

- k8s/operator/deployment/base/rbac.yaml
- src/operator/controllers/BUILD.bazel
- src/operator/controllers/vizier_controller.go
Summary: Previously the operator checked for a specific `ebs-csi-controller` in the `kube-system` namespace on EKS clusters to determine whether PVCs are supported. This was a bit fragile and led to issues like #1577. Instead, this PR changes the operator to check that the provisioner of the default storage class has a corresponding CSIDriver. This avoids the need to look for a specific deployment, and should allow people to use non-etcd pixie with custom PVC controller setups. For now to avoid to much change, we only do this check for the EKS clusters we used to check for the deployment, but in theory we could do this check for all clusters.
Relevant Issues: Fixes #1577
Test Plan: Tested that the new operator deployed to an EKS cluster with the default EKS ebs …
> [operator] Check for CSIDriver matching StorageClass provisioner

- src/carnot/exec/BUILD.bazel
- src/carnot/exec/otel_export_sink_node.cc
- src/carnot/exec/otel_export_sink_node_test.cc
Summary: When doing an otel export, Pixie sends all string data as a string value. This does not work for data with non-utf8 characters and results in many errors. Instead we should detect if non-utf8 characters are present and send bytes data instead.
Relevant Issues: #1594
Test Plan: Added unit test, skaffolded Vizier
```release-note
Fix bug where we were sending data with non-UTF-8 characters as strings during OTel export.
```
> OTel export should send non-utf8 data as bytes

- src/vizier/services/metadata/BUILD.bazel
- src/vizier/services/metadata/controllers/k8smeta/k8s_metadata_controller.go
- src/vizier/services/metadata/controllers/k8smeta/k8s_metadata_controller_test.go
- src/vizier/services/metadata/controllers/k8smeta/k8s_metadata_utils.go
- src/vizier/services/metadata/metadata_server.go
Summary: Enable metadata service to track the events from a subset of namespaces when desired, instead of tracking the events from the entire cluster.
Relevant Issues: #1364
Test Plan: Added unit tests for the new behaviour. @JamesMBartlett tested by skaffolding a dev vizier version to a cluster both with and without `metadata_namespaces` selected, and both behaved as expected.
> Enable metadata service to track the events from a subset of namespaces

- src/shared/metadata/metadata_state.cc
- src/shared/metadata/metadata_state_test.cc
Summary: The existing cleanup of resources does not include these kinds. When kelvin encounters them in a cluster, a fatal error is raised and a traceback printed as kelvin crashes (in debug builds). In non-debug builds, the metadata service will just continue to collect these expired resources; never removing them.
This patch adds cleanup of these resources to prevent crashing (in debug builds) and to reclaim resources and do housekeeping in non-debug builds.
Relevant Issues: #1620
Test Plan: Tests in the metadata_state_test's CleanupExpiredMetadata were enhanced to include tests for these two kinds
> fix: add cleanup of expirred metadata for ReplicaSets and Deployments

- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
Summary: Opt statically linked OpenSSL/BoringSSL applications into TLS tracing by default
Test Plan: Feature flag was used for Pixie owned clusters.
> Opt statically linked OpenSSL/BoringSSL applications into TLS tracing by default

- src/vizier/services/metadata/metadata_server.go
Summary: #1368 added the ability to limit the metadata service to specific namespaces. By default, if no namespaces are mentioned, the flag is supposed to choose all namespaces.
However, if the environment variable is not specified, it is actually parsed as an empty list and the default is not properly chosen. Instead, we can assume no users actually want to watch 0 namespaces, and set it to all namespaces when that occurs.
Test Plan: Skaffold deploy metadata service
> Fix default metadata namespaces

- src/vizier/services/metadata/controllers/k8smeta/BUILD.bazel
- src/vizier/services/metadata/controllers/k8smeta/k8s_metadata_controller.go
- src/vizier/services/metadata/controllers/k8smeta/k8s_metadata_utils.go
Summary: This simplfies informer code to use common
sharedIndexFactories. One set for namespaced resources and
another factory for non-namespaced resources.
We also use the same factories to do the initial list
and population of caches instead of using the bare clientset.
Test Plan: Added logs to ensure that the order dependent stuff
still was init in order.
> Simplify informer code to use common SharedIndexFactories

- src/ui/yarn.lock
Summary: Upgrade `@cypress/request` and `tough-cookie`
Relevant Issues: CVE-2023-26136
Test Plan: These are devDeps for cypress and shouldn't affect any
build or test.
> [chore] Upgrade some indirect npm deps

- src/ui/.eslintrc.json
- src/ui/cypress.config.mjs
- src/ui/cypress.json
- src/ui/cypress/README.md
- src/ui/cypress/integration/admin/api-and-deployment-keys.spec.ts
- src/ui/cypress/integration/live/keyboard-shortcuts.spec.ts
- src/ui/cypress/integration/live/navbars.spec.ts
- src/ui/cypress/integration/live/share-dialog.spec.ts
- src/ui/cypress/integration/live/sidebar-scripts.spec.ts
- src/ui/cypress/integration/unauthenticated/credits.spec.ts
- src/ui/cypress/support/utils/grpc.ts
- src/ui/cypress/tsconfig.json
- src/ui/package.json
- src/ui/yarn.lock
Summary: Update Cypress from 9.x to 12.x, and perform all relevant migrations.
Changes are the results of [10.0 migration](https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-100), [11.0 migration](https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-110), and [12.0 migration](https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-120) guides.
The reason for using `cypress.config.mjs` instead of `cypress.config.ts` is that the latter is not working with Yarn 3 yet ([1](https://github.com/cypress-io/cypress/issues/24209), [2](https://github.com/cypress-io/cypress/issues/22747), [3](https://github.com/cypress-io/cypress/issues/25958)). If that changes, we can revisit.
Notably, one of the larger changes is that test …
> Update Cypress to v12

- src/common/testing/test_utils/container_runner.h
- src/stirling/obj_tools/BUILD.bazel
- src/stirling/obj_tools/address_converter.cc
- src/stirling/obj_tools/address_converter_test.cc
- src/stirling/obj_tools/elf_reader.h
- src/stirling/obj_tools/testdata/containers/BUILD.bazel
- src/stirling/obj_tools/testdata/containers/vaddr_convert_self_func.cc
- src/stirling/obj_tools/testdata/containers/vaddr_convert_self_func_container.h
Summary: Fix virtual to binary addr conversion for processes that have an uncommon virtual memory mapping
Our previous virtual to binary address conversion logic assumed that the first offset within `/proc/$PID/maps` was the correct offset to apply for PIE binaries. There are certain cases, such as when an unlimited stack ulimit is applied, where this assumption doesn't hold true (see the linked issue before for more details). This change adjusts our conversion logic to take into account the correct `/proc/$PID/maps` entry so address conversion works in all known cases.
Relevant Issues: #1630
> Fix virtual to binary addr conversion for processes that have an uncommon virtual memory mapping

- src/datagen/pii/privy/requirements.bazel.txt
Summary: Fixes the privy build which was missing a dependency
Relevant Issues: Fixes #1642
Test Plan: bazel build and tests inside privy work. Datagen works.
> Add exceptiongroup to Privy requirements

- src/stirling/source_connectors/socket_tracer/uprobe_manager.cc
Summary: Add debug log prior to Go TLS uprobe attachment
The relevant issues listed below have needed this logging. When #1111 occurred, a similar [log message](https://github.com/pixie-io/pixie/issues/1111#issuecomment-1494965870) was added adhoc but wasn't merged upstream. Now that #1646 needs to be debugged in a similar fashion, it would be helpful to have this log message available when verbose logging is enabled.
Relevant Issues: #1111 and #1646
Test Plan: Verified the log message is available and identifies the correct binaries
```
$ ./scripts/sudo_bazel_run.sh  src/stirling/source_connectors/socket_tracer:go_tls_trace_bpf_test --test_arg='--vmodule=uprobe_manager=1' 2>&1 | tee output.txt
$ grep 'Attempting to attach Go TLS uprobes to binary' output.txt
[ …
```
> Add debug log prior to Go TLS uprobe attachment

- k8s/operator/helm/templates/04_vizier.yaml
- k8s/operator/helm/values.yaml
Summary: Adds support for tolerations to enable users to deploy PEMs to nodes that have taints through helm.
Relevant Issues: #598
Test Plan: ran `helm install` using the [previous operator helm chart ](https://github.com/pixie-io/pixie/releases/download/release%2Foperator%2Fv0.1.4/pixie-operator-chart-0.1.4.tgz) with these changes and verified that tolerations appear in the CRD.
> Add support for tolerations in helm

- src/stirling/benchmarks/bpf_map_ops_benchmark.cc
- src/stirling/benchmarks/symbolization_benchmark.cc
- src/stirling/bpf_tools/bcc_wrapper.h
- src/stirling/bpf_tools/bcc_wrapper_bpf_test.cc
- src/stirling/bpf_tools/task_struct_resolver.cc
- src/stirling/bpf_tools/uprobe_extra_trigger_bpf_test.cc
- src/stirling/e2e_tests/bpf_map_leak_bpf_test.cc
- src/stirling/obj_tools/elf_reader_symbolizer_bpf_test.cc
- src/stirling/source_connectors/perf_profiler/bcc_bpf_intf/stack_event.h
- src/stirling/source_connectors/perf_profiler/perf_profile_connector.cc
- src/stirling/source_connectors/perf_profiler/perf_profile_connector.h
- src/stirling/source_connectors/perf_profiler/stringifier.cc
- src/stirling/source_connectors/perf_profiler/stringifier.h
- src/stirling/source_connectors/perf_profiler/stringifier_bpf_test.cc
- src/stirling/source_connectors/pid_runtime/pid_runtime_connector.cc
- src/stirling/source_connectors/pid_runtime/pid_runtime_connector.h
- src/stirling/source_connectors/proc_exit/proc_exit_connector.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_bpf_tables.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_bpf_tables.h
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.h
- src/stirling/source_connectors/socket_tracer/uprobe_manager.cc
- src/stirling/source_connectors/socket_tracer/uprobe_manager.h
Summary: We add wrappers for BPF maps and arrays to our BCC wrapper class. These wrappers anticipate our upcoming "record & replay" feature. In specific, they will be used to shim in recording logic and return replayed values, i.e. when either record or replay ("RR") is in use. When "RR" is not in use, they pass through to the underlying BPF map or array.
Relevant Issues: https://github.com/pixie-io/pixie/issues/1163
Test Plan: Existing test coverage exercises all of these.
> `stirling/bpf_tools/bcc_wrapper.h`: Add wrapped BPF maps & arrays.

- src/stirling/source_connectors/socket_tracer/uprobe_manager.cc
Summary: Ensure `kStaticallyLinkedSource` is attributed when static TLS tracing probes are added
When developing #1652, we noticed that there are situations where our prometheus metrics are annotated with `kStaticallyLinkedSource` instead of the correct tls source. This is due to the following [conditional logic](https://github.com/pixie-io/pixie/blob/44a8338a60e74564d94d474a7ed723717d2ebaaf/src/stirling/source_connectors/socket_tracer/uprobe_manager.cc#L646) using a mutable variable which was returning true even when uprobes were already attached. When tracing a dynamically linked process, the uprobe count will be recorded to a non zero value when the dynamic probes are [attached](https://github.com/pixie-io/pixie/blob/44a8338a60e74564d94d474a7ed723717d2ebaaf/src/stirling/source_connector …
> Ensure `kStaticallyLinkedSource` is attributed when static TLS tracing probes are added

- src/stirling/bpf_tools/BUILD.bazel
- src/stirling/bpf_tools/bcc_wrapper.cc
- src/stirling/bpf_tools/bcc_wrapper.h
- src/stirling/bpf_tools/probe_specs/probe_specs.h
- src/stirling/source_connectors/dynamic_tracer/dynamic_trace_connector.cc
- src/stirling/source_connectors/perf_profiler/perf_profile_connector.cc
- src/stirling/source_connectors/proc_exit/proc_exit_connector.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
- src/stirling/source_connectors/tcp_stats/tcp_stats_connector.cc
Summary: To support record & replay, we move the callback cookie into the perf buffer spec. Previously, we plumbed it through as a separate argument. Moving the callback cookie into the perf buffer spec. will allow us to insert a different callback and save the original callback, i.e. to interpose a recorder for recording of perf buffer events.
Relevant Issues: https://github.com/pixie-io/pixie/issues/1163
Test Plan: Fully covered by existing tests.
> [record & replay] Move callback cookie into perf buffer spec.

- .github/workflows/trivy_images.yaml
Summary: The runner seems to run out of disk when loading images, so
use a larger runner.
Test Plan: Check the action on this PR.
> Use larger workers for trivy_images workflow

- src/cloud/api/controllers/BUILD.bazel
- src/cloud/api/controllers/vizier_cluster_grpc.go
- src/cloud/api/controllers/vizier_cluster_test.go
Summary: Display a punycode version of vizier names to guard against homoglyphs (e.g. `clυster` - which looks similar to `cluster` - would display as `xn--clster-q1e`).
Relevant Issues: Fixes #1653
Test Plan: unittest in [vizier_cluster_test.go](https://github.com/pixie-io/pixie/blob/4219a60d9fb6f5735f866059c701c9c763659e5e/src/cloud/api/controllers/vizier_cluster_test.go#L297)
> Detect homoglyphs by rendering punycode version of Vizier names

- src/stirling/bpf_tools/bcc_wrapper.cc
- src/stirling/bpf_tools/bcc_wrapper.h
Summary: In preparation for introducing record & replay, we create a virtual base classes for wrapped BCC maps & arrays. In a future PR, we will introduce two new implementations, one for recording and one for replaying.
Relevant Issues: https://github.com/pixie-io/pixie/issues/1163
Test Plan: fully covered by existing tests.
> [record & replay] Create virtual base classes for wrapped maps & arrays. 

- SECURITY.md
- src/vizier/services/agent/shared/manager/k8s_update.cc
Summary: As a part of Pixie's security assessment, we would like to add details to the security process. This follows the standard templates/guidelines established by CNCF/TAG security, and will continue to evolve overtime as we finetune the process.
Type of change: /kind docs
Test Plan: N/A, this is a doc change.
> Add details around security/vuln disclosure process

- src/common/minitar/minitar.cc
- src/common/minitar/minitar.h
- src/stirling/utils/linux_headers.cc
Summary: Pixie's installation process requires downloading a Linux header bundle and applying patches. Issue #1056 identified that a failed installation process could lead to an inconsistent state, resulting in the error:
```bash
Failed to install packaged Linux headers to /lib/modules/5.15.0-58-generic, error: Internal: Refusing to clobber existing directory: /usr/src/linux-headers-5.15.90-pl.
```
The problem was that the installation process did not clean up after a failed attempt.
This PR modifies the extraction process for prepackaged Linux headers by introducing a staging directory. Extraction is now performed in this staging directory first, which helps ensure that the check for existing directories does not raise an error from a previous failed run. After successfully extracting …
> Fix inconsistent state after failed prepackaged header installation

- src/e2e_test/perf_tool/cmd/BUILD.bazel
- src/e2e_test/perf_tool/cmd/datastudio.go
- src/e2e_test/perf_tool/datastudio/BUILD.bazel
- src/e2e_test/perf_tool/datastudio/datastudio.go
- src/e2e_test/perf_tool/datastudio/templates/charts/experiment/bytes.json
- src/e2e_test/perf_tool/datastudio/templates/charts/experiment/percent.json
- src/e2e_test/perf_tool/datastudio/templates/charts/suite/bytes.json
- src/e2e_test/perf_tool/datastudio/templates/charts/suite/percent.json
- src/e2e_test/perf_tool/datastudio/templates/queries/all_suites_workloads_parameters.sql
- src/e2e_test/perf_tool/datastudio/templates/queries/cpu_usage_preprocessing.sql
- src/e2e_test/perf_tool/datastudio/templates/queries/experiment_view.sql
- src/e2e_test/perf_tool/datastudio/templates/queries/suite_view.sql
- src/e2e_test/perf_tool/datastudio/templates/queries/suite_view_app_overhead.sql
Summary: Adds the templates used to create the datastudio visualizations for the perf_tool.
Test Plan: N/A (no effect on relevant code, just checked in to make it easier to change the datastudio visualizations in the future).
> [perf_tool] Add templates for datastudio charts and queries.

- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
Summary: Restores ability to disable tracing of specific protocols via PEM flags (i.e. environment variable injection). Also changes the flag name listed in the [docs](https://docs.px.dev/reference/admin/deploy-options#set-a-pem-flag) for backwards compatibility, as a previously defined PEM flag could cause a type error.
Disabling specific protocols from tracing is requested by end users (e.g. for optimizing memory usage) and often useful when debugging (or side stepping) PEM bugs.
Related issues: Fixes #1614
Related documentation change: https://github.com/pixie-io/docs.px.dev/pull/274
Test Plan: Verified that tracing is still on by default for each protocol and that tracing still runs as expected via the `socket_tracer` tests.
A further test is required to …
> Restore ability to disable tracing for protocols via PEM flags

- src/operator/controllers/BUILD.bazel
- src/operator/controllers/vizier_controller.go
Summary: This PR lets the operator get the VizierID from the cluster's secrets and then sends it to the config manager service for it to ultimately set feature flags.
Relevant Issues: Fixes #1632
Test Plan: Skaffold the cloud changes on the testing cluster and then skaffold the operator changes on a dev cluster. Manually trigger an update on the operator side to send the VizierID to the config manager service. Check the config manager service's logs to see that the new logic is being executed as expected to handle the VizierID.
> Let the Operator get the VizierID and send to Config Manager Service

- src/cloud/config_manager/controllers/vizier_feature_flags.go
Summary: Update static tls (BoringSSL) tracing feature flag default to true and announce BoringSSL support
Test Plan: This tls tracing has been enabled since v0.14.3's release last month (#1625) and the metrics for internal clusters have been validated
```release-notes
Enhance TLS tracing to support statically linked OpenSSL and BoringSSL (OpenSSL API compatible libraries).
```
> Update static tls (BoringSSL) tracing feature flag default to true and announce BoringSSL support

- k8s/vizier/base/query_broker_deployment.yaml
- src/carnot/planner/compiler/optimizer/BUILD.bazel
- src/carnot/planner/compiler/optimizer/optimizer.h
- src/carnot/planner/compiler/optimizer/prune_unused_contains_rule.cc
- src/carnot/planner/compiler/optimizer/prune_unused_contains_rule.h
- src/carnot/planner/compiler/optimizer/prune_unused_contains_rule_test.cc
- src/carnot/planner/logical_planner_test.cc
Summary: Add compiler optimization to remove `px.contains` calls with empty strings
The majority of our pxl scripts have parameters that default to empty strings. This results in `px.contains` function calls that will always return the original data set (an empty string `""` will always be found in any input string). An example of this can be seen in the following screenshot (the filter arguments highlighted below):
Relevant Issues: Fixes #618
Test Plan: Used analyze and explain query options to test the following conditions:
- Verified what the `http_data` pxl script looks like when there are no arguments supplied without any optimizations -- [graphviz_with_empty_contains](https://github.com/pixie-io/pixie/assets/5855593/3a07d707-5440-4ed6-a7f9-9bf4fd8d09a2) …
> Add compiler optimization to remove `px.contains` calls with empty strings

- src/stirling/source_connectors/socket_tracer/netty_tls_trace_bpf_test.cc
Summary: To prevent older kernels from complaining about eBPF instruction count, mux protocol tracing is only enabled for "newer" kernels. In our test case, we want to enable mux tracing. We fix test `netty_tls_trace_bpf_test.cc` by enabling mux protocol tracing using the test `SetUp` method (and we simultaneously disable a few other protocols to save on eBPF instruction count). Previously, we used an init function, but that was rendered ineffective after we switched our flags from command line args. to env. args.
Test Plan: Existing tests.
> [stirling] Fix `netty_tls_trace_bpf_test.cc` mux protocol tracing option.

- src/carnot/planner/distributed/coordinator/coordinator.cc
Summary: Enabling partial aggregates appears to break flamegraphs in the UI. Below, we show a screen capture with partial aggregates enabled, and disabled. In this PR, we temporarily disable partial aggregates, i.e. until the underlying issue that breaks flamegraphs is resolved.
**Partial aggregates enabled (flamegraphs broken):**
**Partial aggregates disabled (this PR):**
Test Plan: Existing tests one off deploy testing.
> Temporarily disable partial aggregates.

- src/carnot/planner/compiler/test_utils.h
- src/carnot/planner/ir/ast_utils.h
- src/carnot/planner/ir/ast_utils_test.cc
- src/carnot/planner/ir/ir_node.h
- src/carnot/planner/parser/parser.cc
- src/experimental/standalone_pem/vizier_server.h
Summary: Ensure AST and parser errors are recorded within Status objects for more detailed error output
When working with the standalone PEM, there are often pxl constructs that aren't supported. Running a script that contains these elements results in compilation failures that contain empty Status messages (as seen below). The lack of compilation error details makes debugging very difficult.
```
$ PX_HOST_ID=testing bazel run  -c dbg  src/api/go/pxapi/examples/standalone_pem_example:standalone_pem_example
Got error : rpc error: code = InvalidArgument desc = Failed to compile script, while streaming
Execution Time: 0s
Bytes received: 0
I20230906 15:28:52.238765 4180046 vizier_server.h:63] Executing Script
I20230906 15:28:52.239073 4180046 vizier_server.h:124] Compiling and running query …
```
> Ensure AST and paser errors are recorded within Status objects for more detailed error output

- src/stirling/obj_tools/go_syms.cc
- src/stirling/source_connectors/socket_tracer/protocols/amqp/amqp_code_generator/amqp_code_gen.py
- src/stirling/source_connectors/socket_tracer/protocols/amqp/amqp_code_generator/amqp_code_gen_test.py
- src/stirling/source_connectors/socket_tracer/protocols/amqp/amqp_code_generator/gen_templates/decode.cc.jinja_template
- src/stirling/source_connectors/socket_tracer/protocols/amqp/decode.cc
- src/stirling/source_connectors/socket_tracer/protocols/amqp/parse.cc
- src/stirling/source_connectors/socket_tracer/protocols/cql/frame_body_decoder.cc
- src/stirling/source_connectors/socket_tracer/protocols/dns/parse.cc
- src/stirling/source_connectors/socket_tracer/protocols/http2/grpc.cc
- src/stirling/source_connectors/socket_tracer/protocols/kafka/decoder/packet_decoder.cc
- src/stirling/source_connectors/socket_tracer/protocols/kafka/parse.cc
- src/stirling/source_connectors/socket_tracer/protocols/mux/parse.cc
- src/stirling/source_connectors/socket_tracer/protocols/pgsql/parse.cc
- src/stirling/utils/binary_decoder.h
- src/stirling/utils/binary_decoder_test.cc
Summary: This PR adds a function to the BinaryDecoder class to extract little endian encoded integers from the buffer and renames the existing `ExtractInt` function to `ExtractBEInt` to make naming reflect the type of integer. There are several protocol parsing implementations, MongoDB included, which are little endian encoded but have been directly using its relevant functions within utils namespace. Adding this to BinaryDecoder would make it consistent with the existing extract integer functions that deals with big endian encoded integers.
Ran `git grep ExtractInt | cut -d : -f1 | uniq | xargs -I{} sed -i 's/ExtractInt(/ExtractBEInt(/g' {}` and `git grep ExtractInt | cut -d : -f1 | uniq | xargs -I{} sed -i 's/ExtractInt</ExtractBEInt</g' {}` to make the naming changes and reran AMQP's …
> Add support to extract LE Ints in BinaryDecoder & rename the existing ExtractInt function to ExtractBEInt

- ci/vizier_build_release.sh
Summary: Prevent vizier yaml uploads during pre-release builds
A Pixie user that was trying to use a custom registry was attempting to install a pre-release found from the URL mentioned in our docs (`curl https://storage.googleapis.com/pixie-dev-public/vizier/latest/vizier_yamls.tar`).
This led me to realize that there is a bug that causes our vizier "latest" yamls to be updated on every vizier release instead of filtering out pre release builds.
Test Plan: Compared the various build release scripts and noticed that `$release_tag` is used for these checks
After this is merged, we should attempt a pre-release build and verify that `https://storage.googleapis.com/pixie-dev-public/vizier/latest/vizier_yamls.tar` isn't updated.
> Prevent vizier yaml uploads during pre-release builds

- src/stirling/source_connectors/socket_tracer/protocols/amqp/amqp_code_generator/README.md
Summary: The steps to run AMQP's code generation involve running the python files with `bazel` and not `python3`. I experienced the confusion in the readme when I was following the steps to produce AMQP's protocol parsing code when testing out the `ExtractBEInt` functionality in #1698.
Related issues: N/A
Test Plan: N/A
> Update AMQP's code generation README

- bazel/external/mongo_c_driver.BUILD
- bazel/repositories.bzl
- bazel/repository_locations.bzl
Summary: This PR adds the external Bazel repo for the mongo-c-driver. This driver is used to help parse BSON documents from a MongoDB frame to type JSON strings.
Related issues: #640
Test Plan: `bazel build @com_github_mongodb_mongo_c_driver//...`
> [MongoDB Parsing 1/3] Add bazel repo for the Mongo C Driver

- src/stirling/bpf_tools/bcc_wrapper.cc
- src/stirling/bpf_tools/bcc_wrapper.h
- src/stirling/bpf_tools/probe_specs/probe_specs.h
- src/stirling/source_connectors/perf_profiler/bcc_bpf_intf/stack_event.h
- src/stirling/source_connectors/perf_profiler/perf_profile_connector.cc
Summary: We implement a few cosmetic changes to BCC wrapper that support the record & replay effort:
1. We add method `CommonPerfBufferSetup` which will be shared between the recording & normal BCC wrapper impls.
2. We rename the vector of perf buffer specs to `perf_buffer_specs_` i.e. because its inherent name is confusing.
3. We return a status from `PollPerfBuffer` which will be useful for the replaying BCC wrapper.
4. We return BCC as a pointer from BCC wrapper to enable the eventual replaying BCC wrapper.
5. In the perf profiler, we change the data type for the perf buffer names to `std::string` to avoid creating new strings every time they are used.
In response to code review comments, we will rebase #1693 onto this PR, and continue to split that PR into pieces and merge it …
> [record & replay] Tidy up `BCCWrapper` & perf profiler before adding the `rr` sub-tree.

- src/stirling/source_connectors/socket_tracer/protocols/mongodb/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/protocols/mongodb/types.h
Summary: This PR adds the header file the parsing logic uses (currently in #1704 ) to get the MongoDB wire protocol's frame specifications. The header file currently contains the frame spec for a standard message header, the spec of a payload of type `OP_MSG` and contains the basic structure for a `Record`.
Test Plan: Tested the integration of this and the parsing logic through unit tests.
> [MongoDB Parsing 2/3] Add the types header file for MongoDB Frames

- src/vizier/services/query_broker/script_runner/script_runner.go
Summary: If no execScriptClient is returned due to there being an err, the codebase still attempts to use the client to call execScriptClient.Recv() shortly thereafter. This can result in a runtime panic, which appears to be able to bubble up and crash the QB. This patch returns early if there is a detected error such that the QB will continue processing.
Type of change: /kind fix
Test Plan: Reuse existing unit tests
> fix: add return on err to prevent nil pointer deref panic in goroutine

- src/carnot/funcs/builtins/collections.h
- src/carnot/funcs/builtins/collections_test.cc
- src/carnot/planner/distributed/coordinator/coordinator.cc
- src/carnot/planner/distributed/splitter/partial_op_mgr/partial_op_mgr.h
Summary: The implementation of the "any" UDA was broken for partial aggregates. In this PR, we fix that and re-enable partial aggregates.
Test Plan: We add two new test cases: `MergeAnyUDA` and `SerDesAnyUDA`.
> Fix and re-enable partial aggregates.

- src/stirling/bpf_tools/BUILD.bazel
- src/stirling/bpf_tools/bcc_wrapper.cc
- src/stirling/bpf_tools/bcc_wrapper.h
- src/stirling/bpf_tools/probe_specs/probe_specs.h
- src/stirling/bpf_tools/rr/BUILD.bazel
- src/stirling/bpf_tools/rr/rr.cc
- src/stirling/bpf_tools/rr/rr.h
- src/stirling/bpf_tools/rr/rr.proto
- src/stirling/bpf_tools/rr/rr_bpf_test.cc
- src/stirling/bpf_tools/rr/testing/bpf/BUILD.bazel
- src/stirling/bpf_tools/rr/testing/bpf/rr_test.c
Summary: We add the `rr` sub-tree to implement BPF record & replay. In this PR, we include _only_ perf buffer record and replay. BPF maps & arrays will be included in a subsequent PR.
Test Plan: We add a new test case: `rr_bpf_test`.
> Add rr sub-tree, impl. perf buffer record & replay.

- src/carnot/funcs/metadata/metadata_ops.cc
- src/carnot/funcs/metadata/metadata_ops.h
- src/carnot/funcs/metadata/metadata_ops_test.cc
- src/shared/k8s/metadatapb/test_proto.h
Summary: Adds a UDF for returning the Kubernetes ID (uid in the resource) of a Namespace given that Namespaces Name
Type of change: /kind feat
Test Plan: Added CRUD tests for namespace creation, update and deletion similar to other tests in the metadata_ops_test file.
> feat: add udf for returning a namespace ID from a namespace name

- src/carnot/planner/logical_planner_test.cc
- src/carnot/planner/objects/qlobject.h
- src/carnot/planner/probes/probes.cc
- src/carnot/planner/probes/probes.h
- src/carnot/planner/probes/probes_test.cc
- src/carnot/planner/probes/tracing_module.cc
- src/carnot/planner/probes/tracing_module.h
Summary: Adds new `TraceProgram` object to `pxtrace` which accepts a BPFtrace program and selectors to specify deployment restrictions as key value arguments. Also modifies the `probe_fn` argument to `pxtrace.UpsertTracepoint` to accept a single `TraceProgram` object or a list of them, extracting selectors and populating `TracepointDeployment` as required, so that the query broker can register tracepoints with agents that match those selectors.
Example usage
```
import pxtrace
import px
before_518_trace_program = pxtrace.TraceProgram(
program="""$0""",
max_kernel='5.18',
)
after_519_trace_program = pxtrace.TraceProgram(
program="""$1""",
min_kernel='5.19',
)
table_name = 'tcp_drop_table'
pxtrace.UpsertTracepoint('tcp_drop_tracer',
table_name,
[before_518_trace_program, …
```
> [Kernel scoping 4/5] Add TraceProgram object

- src/carnot/planner/probes/tracing_module.cc
- src/carnot/planner/probes/tracing_module.h
Summary: Updates documentation for the `pxtrace.TraceProgram` object which enables deploying bpftrace programs to specific hosts via selectors.
Relevant Issues: https://github.com/pixie-io/docs.px.dev/pull/277
Test Plan: Existing targets.
> Update TraceProgram docstring

- src/shared/metadata/cgroup_path_resolver.cc
- src/shared/metadata/cgroup_path_resolver.h
- src/stirling/core/canonical_types.h
- src/stirling/source_connectors/socket_tracer/amqp_table.h
- src/stirling/source_connectors/socket_tracer/bcc_bpf/socket_trace.c
- src/stirling/source_connectors/socket_tracer/bcc_bpf_intf/common.h
- src/stirling/source_connectors/socket_tracer/cass_table.h
- src/stirling/source_connectors/socket_tracer/conn_stats.cc
- src/stirling/source_connectors/socket_tracer/conn_stats.h
- src/stirling/source_connectors/socket_tracer/conn_stats_table.h
- src/stirling/source_connectors/socket_tracer/conn_stats_test.cc
- src/stirling/source_connectors/socket_tracer/conn_tracker_http2_test.cc
- src/stirling/source_connectors/socket_tracer/conn_tracker_test.cc
- src/stirling/source_connectors/socket_tracer/conn_trackers_manager_test.cc
- src/stirling/source_connectors/socket_tracer/dns_table.h
- src/stirling/source_connectors/socket_tracer/http2_messages_table.h
- src/stirling/source_connectors/socket_tracer/http_table.h
- src/stirling/source_connectors/socket_tracer/kafka_table.h
- src/stirling/source_connectors/socket_tracer/mux_table.h
- src/stirling/source_connectors/socket_tracer/mysql_table.h
- src/stirling/source_connectors/socket_tracer/nats_table.h
- src/stirling/source_connectors/socket_tracer/pgsql_table.h
- src/stirling/source_connectors/socket_tracer/proto/sock_event.proto
- src/stirling/source_connectors/socket_tracer/redis_table.h
- src/stirling/source_connectors/socket_tracer/socket_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
- src/stirling/source_connectors/socket_tracer/testing/client_server_system.h
Summary: Added Capturing of Cgroup ids to the ebpf probes in the socket tracer. This includes modifications to data structures for communicating that information to userspace and other data tables. It also includes some minimal testing for ensuring that cgroup ids are captured correctly. The reason for this change is given in the design document for the solution to this [issue](https://github.com/pixie-io/pixie/issues/1638): in short it is the first step in using cgids rather than pids to associate a particular piece of communication data with the correct pod.
Test Plan: Added Cgroup id capture checks to existing `socket_tracer` tests.
Type of change: /kind Feature expansion
Signed-off-as: AdityaAtulTewari [adityaatewari@gmail.com](mailto:adityaatewari@gmail.com)
> Added cgid capture to stirling with testing

- src/pxl_scripts/README.md
Summary: Update pxl scripts README to remove deleted scripts
Relevant Issues: #1582
Test Plan: Ran `./src/pxl_scripts/update_readme.py` and verified the removed scripts were deleted from the README
> Update pxl scripts README to remove deleted scripts

- src/stirling/e2e_tests/stirling_wrapper_size_test.cc
Summary: Raises the stirling size limit for `dbg` builds by 5 MiB (to 300mb) to accommodate upcoming changes and additions, including mongodb parsing/stitching and `StitchFrames` interface changes (#1716).
Test Plan: Existing targets
> Increase kFileSizeLimit for dbg builds in stirling wrapper size test

- src/shared/metadata/cgroup_path_resolver.cc
- src/shared/metadata/cgroup_path_resolver.h
- src/stirling/core/canonical_types.h
- src/stirling/source_connectors/socket_tracer/amqp_table.h
- src/stirling/source_connectors/socket_tracer/bcc_bpf/socket_trace.c
- src/stirling/source_connectors/socket_tracer/bcc_bpf_intf/common.h
- src/stirling/source_connectors/socket_tracer/cass_table.h
- src/stirling/source_connectors/socket_tracer/conn_stats.cc
- src/stirling/source_connectors/socket_tracer/conn_stats.h
- src/stirling/source_connectors/socket_tracer/conn_stats_table.h
- src/stirling/source_connectors/socket_tracer/conn_stats_test.cc
- src/stirling/source_connectors/socket_tracer/conn_tracker_http2_test.cc
- src/stirling/source_connectors/socket_tracer/conn_tracker_test.cc
- src/stirling/source_connectors/socket_tracer/conn_trackers_manager_test.cc
- src/stirling/source_connectors/socket_tracer/dns_table.h
- src/stirling/source_connectors/socket_tracer/http2_messages_table.h
- src/stirling/source_connectors/socket_tracer/http_table.h
- src/stirling/source_connectors/socket_tracer/kafka_table.h
- src/stirling/source_connectors/socket_tracer/mux_table.h
- src/stirling/source_connectors/socket_tracer/mysql_table.h
- src/stirling/source_connectors/socket_tracer/nats_table.h
- src/stirling/source_connectors/socket_tracer/pgsql_table.h
- src/stirling/source_connectors/socket_tracer/proto/sock_event.proto
- src/stirling/source_connectors/socket_tracer/redis_table.h
- src/stirling/source_connectors/socket_tracer/socket_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
- src/stirling/source_connectors/socket_tracer/testing/client_server_system.h
Summary: Revert cgid capture
This change reverts capturing Cgroup ids from https://github.com/pixie-io/pixie/commit/2a2349f4853c90848437441ceed4bad634505767. Many of the 4.14 kernel tests have [BPF compilation errors](https://app.buildbuddy.io/invocation/075de8d0-d161-4ff6-8b74-123c6da66778#): `HINT: bpf_get_current_cgroup_id missing (added in Linux 4.18)`. Perplexingly, GitHub seems to show these tests as [passing despite the failures](https://github.com/pixie-io/pixie/actions/runs/6366478258/job/17320729511).
Relevant Issues: #1638 #1739
Test Plan: Running CI
> Revert "Added cgid capture to stirling with testing (#1681)"

- src/stirling/source_connectors/socket_tracer/conn_tracker.h
- src/stirling/source_connectors/socket_tracer/protocols/common/interface.h
- src/stirling/source_connectors/socket_tracer/protocols/cql/parse.cc
- src/stirling/source_connectors/socket_tracer/protocols/cql/parse.h
- src/stirling/source_connectors/socket_tracer/protocols/cql/stitcher.h
- src/stirling/source_connectors/socket_tracer/protocols/cql/types.h
Summary: This is the first of four PRs aimed at fixing an issue with the CQL stitcher discussed in #1375. It introduces an additional interface for `StitchFrames` for protocols with streams:
```cpp
// interface for protocols with streams
StitchFrames(absl::flat_hash_map<stream_id_t, std::deque<Frame>>* req_messages, absl::flat_hash_map<stream_id_t, std::deque<Frame>>* res_messages)
```
The old interface is retained for other protocols by default. To use the new map interface, protocols must have the `StreamSupport` enum set to `UseStream` in their `ProtocolTraits`.
```cpp
// interface for protocols without a notion of streams i.e. which don't use streams for frame stitching
StitchFrames(std::deque<Frame>* req_messages, std::deque<Frame>* res_messages)
```
This change should be a no op, as …
> [Fix CQL Stitcher 1/4] Change StitchFrames API for protocols with streams only

- src/stirling/source_connectors/socket_tracer/conn_tracker.h
- src/stirling/source_connectors/socket_tracer/protocols/common/test_utils.h
- src/stirling/source_connectors/socket_tracer/protocols/cql/stitcher.cc
- src/stirling/source_connectors/socket_tracer/protocols/cql/stitcher.h
- src/stirling/source_connectors/socket_tracer/protocols/cql/stitcher_test.cc
- src/stirling/source_connectors/socket_tracer/protocols/cql/types.h
Summary: Fixes the head of line blocking issue discussed in #1375  by using a map of stream_ids to deque of frames, which we populate in the `conn_tracker`. CQL stitcher tests are updated to reflect the bug fix and new interface.
Related issues: #1375
Test Plan: Tested all existing targets and updated the unittests for the CQL stitcher. `Note`: this PR relies on changes introduced in #1689.
> [Fix CQL Stitcher 2/4] Update StitchFrames to use new interface

- src/datagen/pii/privy/requirements.bazel.txt
Summary: Bumps urllib dependency for PII generation library Privy.
Relevant Issues: Closes https://github.com/pixie-io/pixie/pull/1745
Test Plan: bazel build and tests inside privy work. Datagen works.
> Bump urllib to 1.26.18, closing #1745

- scripts/regclient/deps.lua
Summary: This PR adds the Mongo docker [image](https://hub.docker.com/layers/library/mongo/7.0.0/images/sha256-19b2e5c91f92c7b18113a1501c5a5fe52b71a6c6d2a5232eeebb4f2abacae04a?context=explore) to the image dependencies so that it can be mirrored to the various container registries for later use, specifically for the upcoming BPF test.
Test Plan: Used this image through docker.io with the upcoming Mongo BPF test
> Add the Mongo image and mirror it across registries

- src/experimental/standalone_pem/sink_server.h
Summary: We update the code to populate the execution stats data using `mutable` so that the data is written into message that will be sent on the wire. Previously, our code created a copy of the execution stats and updated that. The copy left the upstream message empty and consequently nothing was sent on the wire.
Type of change: /kind bug fix.
Test Plan: We discovered this bug when testing with the px go api. Standalone pem would work when using streaming, but the client api program would fail for batched. The cause of the failure was an unidentified message data type, i.e. a completely empty execution stats data field. We successfully re-tested the batched query with a standalone pem and the go px api.
> [standalone pem] Fix execution stats.

- src/stirling/source_connectors/socket_tracer/protocols/common/data_stream_buffer.h
- src/stirling/source_connectors/socket_tracer/protocols/common/data_stream_buffer_test.cc
Summary: Ensures that timestamps in the event parser are monotonically increasing.
The current stitching logic for CQL relies on the assumption that frame deques are chronologically sorted based on their timestamps. Timestamps from eBPF, however, may not always be monotonic due to CPU variances, with potential discrepancies of [up to 880 usec](https://lore.kernel.org/bpf/CAJD7tkYOs4LKa=j+xNRMRiK=ors7_uCBtAjp6axRNQo0NHQqWA@mail.gmail.com/). This change catches potential anomalies due to non-monotonic timestamps by ensuring that the next frame's timestamp will always be greater than the previous one.
The DataStreamBuffer itself relies on byte positions, not timestamps, for its internal ordering so it won't be affected by this timestamp issue directly. Although DataTables are sorted before …
> Enforce monotonicity for timestamps in event parser

- src/stirling/source_connectors/socket_tracer/openssl_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/uprobe_manager.cc
Summary: Fixes a bug that prevented SSL tracing on dynamically loaded SSL libraries. When probing open ssl libs found from a pod's mapped libraries, we erroneously prefixed library paths with `/proc/<pid>/root` twice, i.e. such that a target library might look like this:
```
/proc/<pid>/root/proc/<pid>/root/<path>/some-lib.so
```
Normal target processes run in their own pid namespace. This meant that the *second* instance of `<pid>` in the path above would not exist in the target process namespace. Hence probing dynamic libraries using this path failed.
We also update the open-ssl test case to not use host pid namespace, i.e. such that those tests expose this bug. Previously, this bug was masked in those test cases because the test container processes ran with host pid namespace.
Related …
> Fix duplicate `/proc/<pid>/root` prefix bug that formed wrong path to `libssl.so` files.

- src/stirling/source_connectors/socket_tracer/protocols/mongodb/parse.cc
- src/stirling/source_connectors/socket_tracer/protocols/mongodb/parse.h
- src/stirling/source_connectors/socket_tracer/protocols/mongodb/parse_test.cc
- src/stirling/source_connectors/socket_tracer/protocols/mongodb/types.h
Summary: This PR adds functionality to track the order of transactions as they are parsed. It adds the streamID of each request to the state vector at parsing time which will then be used to iterate over at stitching time. Adding this will mainly help the stitching process when trying to stitch a request with N `moreToCome` responses.
**Motivation behind this change:**
The stitching implementation relies on the new interface using `absl::flat_hash_map` to store the `streamID` and a deque of request/response frames. We then use a response led matching algorithm where we loop through the response map and stitch the first response frame in a deque with its corresponding request frame. A response pairs with a request when both frames share the same `streamID`, the response frame's `streamID` …
> Use State to track the order of MongoDB transactions

- src/api/go/pxapi/BUILD.bazel
- src/api/go/pxapi/client.go
- src/api/go/pxapi/examples/basic_example/example.go
- src/api/go/pxapi/opts.go
- src/api/go/pxapi/opts_test.go
Summary: Update pxapi Go client to enforce an opt in mechanism when TLS is disabled
Disabling TLS is often useful for test environments, but is not expected to be relied on in any non test environments. The doc string of NewClient was updated, so that this new behavior will explained in the pxapi's [Godoc documentation](https://pkg.go.dev/px.dev/pxapi#NewClient).
Test Plan: The following scenarios were tested to ensure the opt in mechanism is functional
1. Verified that the default behavior does not disable TLS
<details> <summary>output</summary>
```
$ grep cloud /etc/hosts
34.102.151.106 cloud.cluster.local
$ git diff
diff --git a/src/api/go/pxapi/examples/basic_example/example.go b/src/api/go/pxapi/examples/basic_example/example.go
index …
```
> Update pxapi Go client to enforce an opt in mechanism when TLS is disabled

- src/stirling/source_connectors/socket_tracer/protocols/mongodb/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/protocols/mongodb/stitcher.cc
- src/stirling/source_connectors/socket_tracer/protocols/mongodb/stitcher.h
- src/stirling/source_connectors/socket_tracer/protocols/mongodb/stitcher_test.cc
- src/stirling/source_connectors/socket_tracer/protocols/mongodb/types.h
Summary: This PR adds functionality to stitch MongoDB frames together. It relies on state to iterate over the order of streamIDs parsed and uses a response led matching approach.
Test Plan: Added tests
> Add support to stitch MongoDB frames

- src/e2e_test/perf_tool/pkg/deploy/workload.go
- src/e2e_test/perf_tool/pkg/suites/experiments.go
- src/e2e_test/perf_tool/pkg/suites/suites.go
- src/e2e_test/perf_tool/pkg/suites/workloads.go
Summary: Adds perf experiment for `px-k8ssandra` to new `k8ssandraExperimentSuite`
The perf tool does not currently install the [cert-manager](https://cert-manager.io/docs/installation/helm/) automatically, which is required for px-k8ssandra, so we have to spin up a cluster, install the cert-manager and run the perf tool with `--use-local-cluster`. For this reason, this PR creates a new `k8ssandraExperimentSuite` to avoid polluting nightly.
```sh
bazel run //src/e2e_test/perf_tool -- run --suite=k8ssandra --experiment_name=px-k8ssandra --commit_sha=$(git rev-parse HEAD) --api_key=$API_KEY --cloud_addr=$PL_CLOUD_ADDR --use_local_cluster
```
Another issue is that the perf tool currently does not properly clean up the demo; instead of running `px demo delete`, it just tries to delete the …
> Add experiment for `px-k8ssandra` to perf tool

- src/stirling/source_connectors/socket_tracer/data_stream.cc
- src/stirling/source_connectors/socket_tracer/protocols/common/event_parser.h
- src/stirling/source_connectors/socket_tracer/protocols/common/event_parser_test.cc
- src/stirling/source_connectors/socket_tracer/protocols/cql/parse_test.cc
- src/stirling/source_connectors/socket_tracer/protocols/dns/parse_test.cc
- src/stirling/source_connectors/socket_tracer/protocols/http/parse_test.cc
- src/stirling/source_connectors/socket_tracer/protocols/kafka/parse_test.cc
- src/stirling/source_connectors/socket_tracer/protocols/mysql/parse_test.cc
Summary: Populates a map of streamIDs to deque of frames in `ParseFramesLoop` instead of `ParseFrames`. This should provide a small efficiency boost, as we won't have to loop over the frames twice. This PR relies on #1761 due to the way timestamps are updated using `ParseResult`.
Related issues: https://github.com/pixie-io/pixie/issues/1375
Test Plan: Updated parsing tests to use new interface
> [Fix CQL Sticher 4/4] Move StreamID assignment to ParseFramesLoop

- src/stirling/source_connectors/socket_tracer/data_stream.cc
- src/stirling/source_connectors/socket_tracer/mongodb_table.h
- src/stirling/source_connectors/socket_tracer/protocols/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/protocols/mongodb/parse.cc
- src/stirling/source_connectors/socket_tracer/protocols/mongodb/parse.h
- src/stirling/source_connectors/socket_tracer/protocols/stitchers.h
- src/stirling/source_connectors/socket_tracer/protocols/types.h
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.h
- src/stirling/source_connectors/socket_tracer/socket_trace_tables.h
Summary: This PR integrates the mongo protocol tracing functionality with the socket tracer pipeline. The trace mode is currently set to off and can be toggled later.
Test Plan: Tested these changes with the upcoming BPF test.
> Integrate mongo into the socket tracer pipeline

- .github/workflows/build_and_test.yaml
Summary: Our build and test avoidance sometimes runs no tests. This
is fine and we shouldn't fail the XML reporter in this scenario.
Test Plan: Check the test reporter on a PR that triggers no tests.
> Don't fail GH action on empty XML test results

- .github/workflows/build_and_test.yaml
Summary: The XML testlogs aren't always cleaned between runs.
This ensures that we don't fail due to stale test output.
Test Plan: Check github actions runs on this PR.
> Clear stale test output xml

- src/stirling/source_connectors/socket_tracer/protocols/mongodb/decode.cc
- src/stirling/source_connectors/socket_tracer/protocols/mongodb/stitcher.cc
- src/stirling/source_connectors/socket_tracer/protocols/mongodb/stitcher_test.cc
- src/stirling/source_connectors/socket_tracer/protocols/mongodb/types.h
Summary: When end to end testing MongoDB tracing, the parser encountered `OP_MSG` handshaking frames and was not able to parse them. This was due to the old parser searching for a CRUD command in the `OP_MSG` frame's top level key in the payload and `OP_MSG` handshaking frames not containing a key the old parser could interpret.
This PR adds support to parse top level handshaking keys and discards those frames at stitching time. It also correctly prefixes `const` variables in the `types.h` file.
The motivation to parse these frames instead of immediately ignoring them at parsing time is to account for the different possibilities of responses for a handshaking request. A handshaking request could lead to a `more_to_come` response where each frame in the `more_to_come` response may not be …
> Add support to ignore MongoDB handshaking frames

- CONTRIBUTING.md
Summary: Add the terminal pin-entry instructions to the contributor documentation
Test Plan: N/A
> Add the terminal pin-entry instructions to the contributor documentation

- src/pxl_scripts/px/mongodb_data/manifest.yaml
- src/pxl_scripts/px/mongodb_data/mongodb_data.pxl
- src/pxl_scripts/px/mongodb_data/vis.json
Summary: This PR adds the pxl script to visualize the MongoDB data table on the UI.
This is how the table looks like
Test Plan: Ran the pxl script with `vis.json` in the scratch pad section of the UI
> Add the pxl script to visualize MongoDB data

- src/stirling/bpf_tools/bcc_wrapper.cc
- src/stirling/bpf_tools/bcc_wrapper.h
- src/stirling/bpf_tools/rr/rr.cc
- src/stirling/bpf_tools/rr/rr.h
- src/stirling/bpf_tools/rr/rr_bpf_test.cc
- src/stirling/e2e_tests/stirling_wrapper_size_test.cc
Summary: We add the record & replay capability for per-cpu array tables and for stack tables.
Test Plan: We extend the test case: `rr_bpf_test`.
> [record & replay] Add `rr` for per-cpu array table and for stack table.

- src/stirling/source_connectors/socket_tracer/bcc_bpf/socket_trace.c
- src/stirling/source_connectors/socket_tracer/bcc_bpf_intf/socket_trace.h
- src/stirling/source_connectors/socket_tracer/socket_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
Summary: Dynamically increase the loop limit for newer kernels with higher instruction limits (1 million for kernels > 5.1) by 21x to reduce data loss and raise ingest. More details in #1755.
One open question is whether we want to add vizier flag to toggle this behavior in case there are unforseen performance bottlenecks for certain clusters.
Test Plan: Existing targets + perf/demo tests outlined in #1755.
> Raise loop and chunk limit for newer kernels

- .github/workflows/pr_description_linter.yaml
Summary: TSIA
Test Plan: This will prevent the GH actions from showing a failed run on
dependabot PRs.
> Ignore PR description linter when PR is created by dependabot

- src/carnot/goplanner/schema_test.go
- src/stirling/source_connectors/socket_tracer/amqp_table.h
- src/stirling/source_connectors/socket_tracer/canonical_types.h
- src/stirling/source_connectors/socket_tracer/cass_table.h
- src/stirling/source_connectors/socket_tracer/conn_tracker.h
- src/stirling/source_connectors/socket_tracer/dns_table.h
- src/stirling/source_connectors/socket_tracer/http_table.h
- src/stirling/source_connectors/socket_tracer/kafka_table.h
- src/stirling/source_connectors/socket_tracer/mongodb_table.h
- src/stirling/source_connectors/socket_tracer/mux_table.h
- src/stirling/source_connectors/socket_tracer/mysql_table.h
- src/stirling/source_connectors/socket_tracer/nats_table.h
- src/stirling/source_connectors/socket_tracer/pgsql_table.h
- src/stirling/source_connectors/socket_tracer/redis_table.h
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
Summary: Adds data columns for local IP address and port to the socket tracer, which are populated by #1808 and #1809. This will support standalone pem entity relationships.
Test Plan: Existing targets
> [Add Local Addr & Port 2/3] Add columns to socket tracer

- src/stirling/source_connectors/socket_tracer/http_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/openssl_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/testing/protocol_checkers.h
Summary: Add simple test for capturing local IP. This is in addition to E2E testing with demo apps done previously.
Test Plan: Adapted http and openssl bpf tests. Note that the remote and local address are the same because the client and server are running on the same host and communicating via loopback.
> [Add Local Addr & Port 3/3] Add simple test for capturing local IP

- src/stirling/utils/linux_headers.cc
Summary: This PR removes a condition which checks to see if a host path exists in the filesystem of a process when trying to resolve symlinks.
The function `fs::Exists()` returned false for a broken symlink when the expectation was to return true because the path existed although it was a broken symlink. This function would later on fix the broken symlink path by reading its target host and converting the broken path into the actual path. This makes the code removal safe as the next check: `is_symlink` will return an error code if there is no file.
Test Plan: Existing tests pass and deployed the PEM with the updated fix and saw that the Linux header files were found.
> Fix bug that threw an error while searching for linux headers through a symlink

- src/stirling/source_connectors/socket_tracer/BUILD.bazel
- src/stirling/source_connectors/tcp_stats/tcp_stats_connector.cc
Summary: Kernel version 6.5 removed `tcp_sendpage`. In this PR, we make sendpage probes optional. We will get instrumentation coverage via `tcp_sendmsg` in case these probes don't get attached.
Test Plan: Retested tcp stats connector on a machine with Kernel v6.5.
> [stirling/tcp-stats] Fix Kernel >= 6.5 which for tcp_sendpage.

- demos/BUILD.bazel
- demos/README.md
- demos/manifest.json
- demos/mongodb/mongodb.yaml
Summary: This PR adds a demo app to test the mongo protocol tracing feature.
Related issues: Closes https://github.com/pixie-io/pixie/issues/640
Test Plan: Uploaded the `px-mongo` demo artifact to the GCS dev bucket. Tested the CLI and then deployed the demo to my cluster. Skaffolded Pixie with the latest mongo tracing changes and used the scratch pad to execute the mongo pxl script to verify data is being collected from the demo.
```
Adds the `px-mongo` demo to the CLI
```
> Add the px-mongo demo to the CLI

- src/stirling/source_connectors/socket_tracer/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/http_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/protocols/http/stitcher.cc
- src/stirling/source_connectors/socket_tracer/protocols/http/stitcher.h
- src/stirling/source_connectors/socket_tracer/protocols/http/stitcher_test.cc
- src/stirling/source_connectors/socket_tracer/protocols/http/utils.cc
- src/stirling/source_connectors/socket_tracer/protocols/http/utils.h
- src/stirling/source_connectors/socket_tracer/protocols/http/utils_test.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
Summary: Decode http request bodies that contain x-www-form-urlencoded data
This change enhances the request body in a `http_events` protocol trace for services that accept HTML form submissions.
Test Plan: New unit tests and trace bpf test verify decoding works
Changelog Message: Decode `x-www-form-urlencoded` payloads within HTTP requests
> Decode http request bodies that contain x-www-form-urlencoded data

- src/stirling/source_connectors/socket_tracer/amqp_table.h
- src/stirling/source_connectors/socket_tracer/canonical_types.h
- src/stirling/source_connectors/socket_tracer/cass_table.h
- src/stirling/source_connectors/socket_tracer/dns_table.h
- src/stirling/source_connectors/socket_tracer/http_table.h
- src/stirling/source_connectors/socket_tracer/kafka_table.h
- src/stirling/source_connectors/socket_tracer/mongodb_table.h
- src/stirling/source_connectors/socket_tracer/mux_table.h
- src/stirling/source_connectors/socket_tracer/mux_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/mysql_table.h
- src/stirling/source_connectors/socket_tracer/nats_table.h
- src/stirling/source_connectors/socket_tracer/netty_tls_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/openssl_trace_bpf_test.cc
- src/stirling/source_connectors/socket_tracer/pgsql_table.h
- src/stirling/source_connectors/socket_tracer/redis_table.h
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
- src/stirling/source_connectors/socket_tracer/testing/protocol_checkers.h
Summary: Add encrypted field to all protocol data tables
The goal of this column is to ease the ability of identifying connections that are plaintext that are ingressing from or egressing to the Internet.
Relevant Issues: #1865
Test Plan: Additional test logic verifies new behavior
Changelog Message: Add `encrypted` boolean field to all protocol/L7 data tables
> Add encrypted field to all protocol data tables

- src/stirling/source_connectors/socket_tracer/protocols/mongodb/stitcher.cc
Summary: This PR modifies mongo's stitcher logic to clear streamID’s from request/response maps once all frames of a streamID have been consumed. We observed high CPU use allocated to `FramesSize()` & `EraseExpiredFrames()`, this was due to the size of the maps increasing with new streamIDs and having to continuously loop over those growing maps to cleanup. Clearing the streamID's from the maps after stitching significantly reduces the CPU allocated to the cleanup logic for mongo, the exact details for mongo's streamID reuse needs to be determined to further adapt the stitcher logic.
Test Plan: Existing tests still pass, ran the px-mongo demo and observed lower CPU allocated to mongo in the PEM through flamegraph.
> [Mongo] Clear the streamID from the request/response maps after stitching

- WORKSPACE
- bazel/repository_locations.bzl
Summary: Ensure a hermetic python install is used for `pip_parse` and upgrade `rules_python`
This is prerequisite work for migrating our docker dev image  to Ubuntu 24.04 (#1885). In that PR, I've been running builds from within the containers built via packer to verify the upgrade is successful. This change is required to address the following issues:
* The `pip_parse` for `ubuntu_package_deps` comes before the hermetic python definition. This results in a `ModuleNotFoundError` error without the `rules_python` upgrade (since python 3.12, shipped with 24.04, [removed disutils](https://peps.python.org/pep-0632/)).
* The remaining `pip_parse` calls fail when run within a 24.04 container since it causes python to upgrade to 3.12.
Note: `rules_python` 0.26.0 is the latest version we can …
> Ensure a hermetic python install is used for `pip_parse` and upgrade `rules_python`

- src/stirling/source_connectors/tcp_stats/tcp_stats.cc
- src/stirling/source_connectors/tcp_stats/tcp_stats.h
- src/stirling/source_connectors/tcp_stats/tcp_stats_connector.cc
Summary: Makes a couple of optimizations to the TCP stats connector. In particular, we pass by reference instead of copy in `TCPStats::UpdateStats` and simplify the cleanup logic in `TransferDataImpl`.
Test Plan: Bpf test works. Ran heap profiler and observed fewer allocations.
One remaining mystery is a single 384Mb allocation that seems to always arise in the heap profile for `AcceptTcpEvent`. Even commenting out the body of the function does not change this. Originally thought this might be related to the `BPF_HASH(sock_store, uint32_t, struct sock*, 10240);`, but changing its size had no affect on the allocation.
> Optimize TCP Stats Connector

- src/common/signal/signal_action.h
Summary: This PR modifies the logic that sets the value of `altstack_size_`. When deploying Pixie on a 7th gen AMI running bottle rocket, the value of `altstack_size_` was set to `MINSIGSTKSZ`. This value was 39616 and was not a multiple of the system page size.
In this [line of code](https://github.com/pixie-io/pixie/blob/0888c38df2dc414a36cc84198c7b159c39eea0e0/src/common/signal/signal_action.cc#L149) `mprotect` was then applied on a non page aligned region since its address was set as `altstack_ + guard_size_ + altstack_size_` leading to an error. This region in `altstack_` was also not the tailing `guard_size_` area as [mmap](https://github.com/pixie-io/pixie/blob/0888c38df2dc414a36cc84198c7b159c39eea0e0/src/common/signal/signal_action.cc#L145) would have added extra bytes to …
> Make sure altstack_size_ is a multiple of the system page size

- .arclint
- k8s/operator/helm/crds/olm_crd.yaml
- k8s/operator/helm/templates/00_olm.yaml
Summary: Upgrade OLM to v0.27.0
Test Plan: Verified that the [v0.1.5-pre-z0v27.0](https://github.com/pixie-io/pixie/releases/tag/release%2Foperator%2Fv0.1.5-pre-z0v27.0) operator pre-release passed the release checklist
Changelog Message: Upgrade OLM from v0.24 to v0.27.0. This fixes an issue where OLM could not be scheduled on an ARM only k8s cluster (see https://github.com/operator-framework/operator-lifecycle-manager/pull/2958 for more details)
> Upgrade OLM to v0.27.0

- .golangci.yaml
- src/operator/controllers/vizier_controller.go
Summary: Exclude DaemonSets (PEMs) from modification by a Vizier's nodeSelector
This accomplishes part of #1861. The remaining work is to include new additional node selector configuration values that only apply to PEMs -- similar to how `pemMemoryLimit` and `pemMemoryRequest` work. From my investigation so far, it appears that adding the PEM specific selectors will require a different implementation (via the vizier yaml templating on the Pixie cloud side) and so I thought staging this in two changes made sense.
Relevant Issues: #1861
Test Plan: Skaffolded a vizier operator and verified that setting a `kubernetes.io/hostname` node selector no longer prevents PEMs from being scheduled on all nodes
Changelog Message: Fixed an issue that caused the `Vizier` CRD to …
> Exclude DaemonSets (PEMs) from modification by a Vizier's nodeSelector

- src/operator/controllers/BUILD.bazel
- src/operator/controllers/vizier_controller.go
Summary: Revert change that causes `px deploy` to timeout on initial deployment
This reverts #1670, which creates a circular dependency between the operator and the cloud connector service. The cloud connector service is responsible for [registering a vizier](https://github.com/pixie-io/pixie/blob/fb18345808e6fbd8aed02dac8163469322b84205/src/vizier/services/cloud_connector/bridge/server.go#L290-L302) and populating the `pl-cluster-secrets` k8s secret with its vizier ID. The operator is responsible for creating the vizier services (including the cloud connector), so [this call](https://github.com/pixie-io/pixie/blob/fb18345808e6fbd8aed02dac8163469322b84205/src/operator/controllers/vizier_controller.go#L503) will never succeed on a fresh install.
This bug doesn't cause pixie installs to …
> Revert change that causes `px deploy` to timeout on initial deployment

- k8s/cloud/public/base/artifact_tracker_versions.yaml
Summary: Update self-hosted vizier version in artifact tracker configuration
Relevant Issues: #1907
Type of change: /kind dependency
Test Plan: Performed the same change on an existing artifact tracker deployment and verified subsequent `px deploy`s use new version
Changelog Message: Updated the vizier version bundled within self-hosted cloud to 0.14.9
> Update self-hosted vizier version in artifact tracker configuration

- src/experimental/standalone_pem/standalone_pem_manager.cc
- src/vizier/services/agent/pem/pem_manager.cc
Summary: When some or all of the tables `http_events, stirling_error, probe_status, proc_exit_events` are disabled via stirling flags (`PL_STIRLING_SOURCES=...`) the `other_table_size` calculation returns a negative output if `num_tables < 4`. It also attempts division by zero when `num_tables = 4`
```cpp
int64_t other_table_size = (memory_limit - http_table_size - stirling_error_table_size -
probe_status_table_size - proc_exit_events_table_size) /
(num_tables - 4);
```
This PR streamlines the table size calculation and fixes the edge condition.
Test Plan: deployed to node and manually checked calculated table sizes.
> Fix negative table size calculation when socket tracer disabled via stirling flag

- bazel/repository_locations.bzl
- src/stirling/bpf_tools/bcc_symbolizer_bpf_test.cc
Summary: Upgrade bcc and libbpf to fix Google COS socket tracer issues
See GitHub issue comments below for more details. This pulls in the following BCC fix (https://github.com/iovisor/bcc/commit/57ca51bdd9c86870a43b9f76e062b3aede226ca4).
Relevant Issues: Closes #1900, part of #1905
Test Plan: Skaffold'ed this change to a Ubuntu and Google COS cluster and verified socket tracer works again
```
ddelnano@noble-dev:~/code/bcc/build (pixie8) $ git diff pixie/pixie8 ddelnano/pixie8
ddelnano@noble-dev:~/code/bcc/build (pixie8) $
```
Changelog Message: Fix issue with socket tracer on recent Google COS instances
> Upgrade bcc and libbpf to fix Google COS socket tracer issues

- k8s/operator/helm/templates/00_olm.yaml
- k8s/operator/helm/templates/02_catalog.yaml
- k8s/operator/helm/templates/03_subscription.yaml
- k8s/operator/helm/values.yaml
Summary: Add node selectors fields in helm chart to control scheduling of OLM and operator pods
Previously a helm chart user could only specify the node selectors for the vizier components. This PR allows for applying node selectors to OLM and the operator. This was feedback from @ashutoshrathore after the functionality from #1887 was released.
Relevant Issues: #1861
Test Plan: Tested the following scenarios
```
$ helm template pixie-operator k8s/operator/helm/ -f k8s/operator/helm/values.yaml --debug  > new.yaml
install.go:200: [debug] Original chart version: ""
install.go:217: [debug] CHART PATH: /home/ddelnano/code/pixie-worktree/k8s/operator/helm
$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
$ helm template …
```
> Add node selectors fields in helm chart to control scheduling of OLM and operator pods

- scripts/regclient/regbot_releases.yaml
- scripts/regclient/releases.lua
Summary: The image mirroring wasn't updated in #1593 and as a result the releases weren't getting mirrored. This fixes the same and also ensures that the signatures get copied over.
Test Plan: Ran a regbot dry run to ensure new images would get copied over.
> Update release image locations

- .github/workflows/oss_scorecard.yaml
Summary: This upgrades pulls in a fix for github.com/ossf/scorecard-action/issues/998 which was causing the action to fail.
Test Plan: Scorecard runs should succeed again after this.
> chore: Bump scorecard action

- .github/workflows/mirror_demos.yaml
- .github/workflows/mirror_deps.yaml
Summary: Fix use of GitHub expression to fix image mirroring dry run logic
The version of the workflow on main always runs with `--dry-run` provided regardless of the input value. I thought that the 'else' case of a ternary could be omitted, but that was incorrect. The latest implementation aligns with the example in the [GitHub docs](https://docs.github.com/en/actions/learn-github-actions/expressions#example).
Relevant Issues: Precursor to fixing px-sock-shop (https://github.com/pixie-io/pixie/issues/1905)
Test Plan: Updated based on the docs. Needs to be validated with a workflow run against a branch in the pixie-io org
> Fix dry run logic

- .github/workflows/mirror_demos.yaml
- .github/workflows/mirror_deps.yaml
Summary: Remove dry_run inputs responsible for regbot dry runs to always execute
I attempted to fix the bug where `--dry-run` is always passed to the `regbot` cli in the mirror workflows in #1921. That attempt unfortunatley did not work, so let's remove the input and the cli argument templating entirely. Running `regbot --dry-run` locally is an easy enough mechanism for testing the workflow logic.
Relevant Issues: Precursor to fixing px-sock-shop (https://github.com/pixie-io/pixie/issues/1905)
Test Plan: Expecting that the next run off main after this change will result in mirrored demo container images
> Remove dry_run inputs responsible for regbot dry runs to always execute

- scripts/regclient/deps.lua
Summary: Fix incorrect sha for demo image mirror source
This was identified on the first mirror demos GitHub action run ([link](https://github.com/pixie-io/pixie/actions/runs/9263712385/job/25482607834)).
```
time="2024-05-28T05:08:04Z" level=warning msg="Error running script" error="./deps.lua:146: Failed copying \"gcr.io/pixie-oss/demo-apps/px-sock-shop/carts@sha256:0bcf0ac7a03157b3a311e28e9e73ca827fc7b8c6454600b8626a3b129e41886c\" to \"docker.io/pxio/px-sock-shop-carts:latest@sha256:0bcf0ac7a03157b3a311e28e9e73ca827fc7b8c6454600b8626a3b129e41886c\": failed to get manifest gcr.io/pixie-oss/demo-apps/px-sock-shop/carts@sha256:0bcf0ac7a03157b3a311e28e9e73ca827fc7b8c6454600b8626a3b129e41886c: request failed: not found [http 404]: {\"errors\":[{\"code\":\"MANIFEST_UNKNOWN\",\"message\":\"Req …
```
> Fix incorrect sha for demo image mirror source

- scripts/regclient/deps.lua
Summary: Fix outstanding issues and missing images from mirror demos job
Test Plan: Identified these from previous GitHub action output and as I've created PRs to use these images
> Fix outstanding issues and missing images from mirror demos job

- demos/kafka/kafka.yaml
Summary: Update px-kafka demo to use ghcr.io mirrored images
Test Plan: Deployed the demo by building and serving the px-kafka tar.gz locally
```
$ bazel build //demos:px-kafka
$ cp bazel-bin/demos/px-kafka.tar.gz demos/ && cd demos && python -m http.server
$ px demo deploy  --artifacts http://localhost:8000 px-kafka
```
Changelog Message: Moved hosting of px-kafka demo container images from gcr.io to ghcr.io
> Update px-kafka demo to use ghcr.io mirrored images

- demos/finagle/finagle.yaml
Summary: Update px-finagle demo to use ghcr.io mirrored images
Test Plan: Deployed the demo by building and serving the px-finagle tar.gz locally
```
$ bazel build //demos:px-finagle
$ cp bazel-bin/demos/px-finagle.tar.gz demos/ && cd demos && python -m http.server
$ px demo deploy  --artifacts http://localhost:8000 px-finagle
```
Changelog Message: Moved hosting of px-finagle demo container images from gcr.io to ghcr.io
> Update px-finagle demo to use ghcr.io mirrored images

- demos/sock-shop/sock-shop-loadgen.yaml
- demos/sock-shop/sock-shop.yaml
Summary: Update px-sock-shop demo to use ghcr.io mirrored images
Relevant Issues: Fixes the sock shop issues of #1905
Test Plan: Deployed the demo by building and serving the px-sock-shop tar.gz locally
```
$ bazel build //demos:px-sock-shop
$ cp bazel-bin/demos/px-sock-shop.tar.gz demos/ && cd demos && python -m http.server
$ px demo deploy  --artifacts http://localhost:8000 px-sock-shop
```
Changelog Message: Moved hosting of px-sock-shop container images from gcr.io to ghcr.io
> Update px-sock-shop demo to use ghcr.io mirrored images

- demos/online-boutique/online-boutique.yaml
Summary: Update px-online-boutique demo to use ghcr.io mirrored images
Relevant Issues: Addresses #1830 in addition to registry change
Test Plan: Deployed the demo by building and serving the px-online-boutique tar.gz locally
```
$ bazel build //demos:px-online-boutique
$ cp bazel-bin/demos/px-online-boutique.tar.gz demos/ && cd demos && python -m http.server
$ px demo deploy  --artifacts http://localhost:8000 px-online-boutique
```
Changelog Message: Moved hosting of px-online-boutique container images from gcr.io to ghcr.io
> Update px-online-boutique demo to use ghcr.io mirrored images

- scripts/regclient/deps.lua
Summary: Mirror curl multiarch image to ghcr.io and other mirror registries
Test Plan: Verified the image used pulls successfully
```
$ docker pull gcr.io/pixie-oss/pixie-dev-public/curl:multiarch-7.87.0@sha256:f7f265d5c64eb4463a43a99b6bf773f9e61a50aaa7cefaf564f43e42549a01dd
gcr.io/pixie-oss/pixie-dev-public/curl@sha256:f7f265d5c64eb4463a43a99b6bf773f9e61a50aaa7cefaf564f43e42549a01dd: Pulling from pixie-oss/pixie-dev-public/curl
Digest: sha256:f7f265d5c64eb4463a43a99b6bf773f9e61a50aaa7cefaf564f43e42549a01dd
Status: Image is up to date for gcr.io/pixie-oss/pixie-dev-public/curl@sha256:f7f265d5c64eb4463a43a99b6bf773f9e61a50aaa7cefaf564f43e42549a01dd
gcr.io/pixie-oss/pixie-dev-public/curl:multiarch-7.87.0@sha256:f7f265d5c64eb4463a43a99b6bf773f9 …
```
> Mirror curl multiarch image to ghcr.io and other mirror registries

- bazel/container_images.bzl
- demos/sock-shop/sock-shop-loadgen.yaml
- k8s/cloud/base/ory_auth/kratos/kratos_deployment.yaml
- k8s/devinfra/buildbuddy-executor/values.yaml
- k8s/vizier/base/kelvin_deployment.yaml
- k8s/vizier/base/patch_sentry.yaml
- k8s/vizier/base/query_broker_deployment.yaml
- k8s/vizier/bootstrap/cloud_connector_deployment.yaml
- k8s/vizier/etcd_metadata/base/metadata_deployment.yaml
- k8s/vizier/pem/base/pem_daemonset.yaml
- k8s/vizier/persistent_metadata/base/metadata_statefulset.yaml
- k8s/vizier/sanitizer/kelvin_deployment.yaml
- src/e2e_test/jetstream_loadtest/k8s/subscriber_deployment.yaml
- src/e2e_test/protocol_loadtest/http/wrk/k8s/client_deployment.yaml
- src/e2e_test/protocol_loadtest/k8s/client/client_deployment.yaml
Summary: Unify curl image usage to use curl 7.87.0 multiarch image
```
$ docker images
REPOSITORY                                                                       TAG       IMAGE ID       CREATED         SIZE
bazel/image                                                                      image     3148ec916ea7   17 months ago   15MB
curlimages/curl                                                                  7.87.0    3148ec916ea7   17 months ago   15MB
gcr.io/pixie-oss/pixie-dev-public/curl                                           <none>    3148ec916ea7   17 months ago   15MB
ghcr.io/pixie-io/pixie-oss-pixie-dev-public-curl                                 <none>    3148ec916ea7   17 months …
```
> Unify curl image usage to use curl 7.87.0 multiarch image

- k8s/cloud_deps/dev/elastic/kustomization.yaml
- k8s/cloud_deps/prod/elastic/kustomization.yaml
- k8s/cloud_deps/public/elastic/kustomization.yaml
- k8s/cloud_deps/staging/elastic/kustomization.yaml
- k8s/cloud_deps/testing/elastic/kustomization.yaml
Summary: Replace deprecated kustomize constructs with their new equivalent
Test Plan: Modified these files with `kustomize edit fix` and verified the following:
```
(ddelnano/replace-deprecated-kustomize-patches-config) $ for env in dev prod public staging; do kustomize build k8s/cloud_deps/$env/elastic > k8s/cloud_deps/$env/elastic/new; done
(main) $ for env in dev prod public staging; do kustomize build k8s/cloud_deps/$env/elastic > k8s/cloud_deps/$env/elastic/old; done
$ for env in dev prod public staging; do sha256sum k8s/cloud_deps/$env/elastic/{old,new}; done
2c7459bcc8de323dd30ced4459257d130eef9b56f417b66317e64596d047b8ea  k8s/cloud_deps/dev/elastic/old
2c7459bcc8de323dd30ced4459257d130eef9b56f417b66317e64596d047b8ea …
```
> Replace deprecated kustomize constructs with their new equivalent

- k8s/cloud/dev/kustomization.yaml
- k8s/cloud/prod/kustomization.yaml
- k8s/cloud/public/base/kustomization.yaml
- k8s/cloud/staging/kustomization.yaml
- k8s/cloud/testing/kustomization.yaml
- k8s/cloud_deps/dev/nats/kustomization.yaml
- k8s/cloud_deps/prod/nats/kustomization.yaml
- k8s/cloud_deps/public/nats/kustomization.yaml
- k8s/cloud_deps/staging/nats/kustomization.yaml
- k8s/cloud_deps/testing/nats/kustomization.yaml
- k8s/vizier/sanitizer/kustomization.yaml
Summary: Use kustomize edit fix to remove deprecated constructs (patchesJson6902 and other fixes)
Test Plan: Modified these files with `kustomize edit fix` and verified the following:
<details><summary> output </summary>
```
(ddelnano/update-deprecated-patches-strategic-merge) $ git diff HEAD~1 --name-only > files
(ddelnano/update-deprecated-patches-strategic-merge) $ cat files  | xargs -I{} dirname {} | sort -u | xargs -I{} bash -c "kustomize build {} > {}/new"
(master) $ cat files | xargs -I{} bash -c "sha256sum {}/new; sha256 {}/old"
$ cat dirs | xargs -I{} bash -c "echo 'Testing {}'; diff {}/new {}/old"
Testing k8s/cloud/dev
Testing k8s/cloud/prod
835a836,849
>       - command:
>         - /cloud_sql_proxy
>         - …
```
> Use kustomize edit fix to remove deprecated constructs (patchesJson6902 and other fixes)

- k8s/cloud/prod/db_sidecar.yaml
- k8s/cloud/staging/db_sidecar.yaml
- k8s/cloud/testing/db_sidecar.yaml
Summary: Upgrade cloud-sql-proxy from v1 to v2
Type of change: /kind dependency
Test Plan: Deployed new testing cloud and verified database access works with v2 image
> Upgrade cloud-sql-proxy from v1 to v2

- k8s/cloud/prod/kustomization.yaml
- k8s/cloud/testing/kustomization.yaml
Summary: Reorder kustomization patches to keep consistent ordering between envs
This reordering was introduced in https://github.com/pixie-io/pixie/pull/1938. Note how the testing performed on that PR required looking at how the yaml was reordered for a few cases. This change fixes that reordering.
Test Plan: Verified with `kustomize build k8s/cloud/prod` and `kustomize build k8s/cloud/testing` that the yaml before #1938 and after this fix match exactly
> Reorder kustomization patches to keep consistent ordering between envs

- .github/workflows/perf.yaml
Summary: We need to rethink how we trigger perf on PRs.
Test Plan: Disables the perf action, no test necessary.
> [actions] Disable Perf PR action

- skaffold/skaffold_cloud.yaml
- skaffold/skaffold_operator.yaml
Summary: Add x86_64 sysroot profile to cloud and operator skaffold configs
Deploying builds from a noble (Ubuntu 24.04) environment requires using the x86_64 sysroot at all times. Add this to the config to make this addition easy to opt into.
Type of change: /kind compatibility
Test Plan: Deployed a new cloud and got it successfully running with `skaffold run -p ${env},x86_64_sysroot -f skaffold/skaffold_cloud.yaml`
> Add x86_64 sysroot profile to cloud and operator skaffold configs

- demos/mongodb/mongodb.yaml
Summary: Update px-mongo demo to use ghcr.io mirrored images
Test Plan: Deployed the demo by building and serving the px-mongo tar.gz locally
```
$ bazel build //demos:px-mongo
$ cp bazel-bin/demos/px-mongo.tar.gz demos/ && cd demos && python -m http.server
$ px demo deploy  --artifacts http://localhost:8000 px-mongo
```
Changelog Message: Moved hosting of px-mongo demo container images from gcr.io to ghcr.io
> Update px-mongo demo to use ghcr.io mirrored images

- k8s/cloud/overlays/plugin_job/plugin_job.yaml
- k8s/clusters/prod/db_reader.yaml
- k8s/clusters/staging/db_reader.yaml
- k8s/clusters/testing/db_reader.yaml
Summary: Upgrade remaining references to cloud-sql-proxy v1 to v2
This is a continuation of #1942.
```
$ git grep gce-proxy
$
```
> Upgrade remaining references to cloud-sql-proxy v1 to v2

- k8s/cloud/overlays/plugin_job/plugin_job.yaml
Summary: Fix busybox path in plugin job with switch to `x86_64_sysroot` skaffold profile
#1941 switched the cloud skaffold build to use the x86_64_sysroot profile. After that was introduced, the plugin load job no longer runs due to a missing `/busybox` path. This change updates the kubernetes manifests to work with the correct path.
```
$ bazel run --config=x86_64_sysroot --config=stamp -c opt src/cloud/plugin/load_db:plugin_db_updater_image
INFO: Analyzed target //src/cloud/plugin/load_db:plugin_db_updater_image (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //src/cloud/plugin/load_db:plugin_db_updater_image up-to-date: …
```
> Fix busybox path in plugin job with switch to `x86_64_sysroot` skaffold profile

- src/ui/package.json
- src/ui/yarn.lock
Summary: Replace deprecated react-cookie-banner with react-cookie-consent
The react-cookie-banner library was deprecated in March 2024 (see [Github page](https://github.com/buildo/react-cookie-banner)). This replaces it with a similarly minimal library that is maintained.
Test Plan: Skaffold'ed a cloud and verified the new cookie banner works properly
> Replace deprecated react-cookie-banner with react-cookie-consent

- src/ui/src/components/mui-theme.tsx
- src/ui/src/configurables/base/theme-colors.ts
Summary: Refactor base colors to configurables directory. Allow customizing primary color for light and dark mode
This change makes it possible to have different main colors for light and dark mode. The contrast difference between the light mode background and the text color scores poorly with the [contrast checker](https://webaim.org/resources/contrastchecker/?fcolor=12D6D6&bcolor=F6F6F6).
Test Plan: Tested UI to verify that it looks the same in light and dark mode
> Refactor base colors to configurables directory. Allow customizing primary color for light and dark mode

- src/ui/src/configurables/base/signup.ts
- src/ui/src/pages/auth/signup.tsx
Summary: Refactor vendor specific signup message to configurables
Type of change: /kind clenaup
Test Plan:  Verified `/auth/signup`'s text is displayed as it was before
> Refactor vendor specific signup message to configurables

- go.mod
- go.sum
- go_deps.bzl
- src/pixie_cli/pkg/cmd/BUILD.bazel
- src/pixie_cli/pkg/cmd/deploy.go
- src/pixie_cli/pkg/cmd/root.go
- src/pixie_cli/pkg/cmd/run.go
Summary: Update px cli to make `--cloud_addr` a required argument
This removes the CC4P dependency on the Pixie cli so that the project is agnostic to any vendor provided Pixie cloud. While this argument is now required, if the cli is run within an interactive shell, the user will be presented with the available Pixie clouds and have the opportunity to select the one they want to use (see Test Plan below).
My plan is to take this a step further for the interactive case and have the cli populate the `~/.pixie/config.json` (or similar) file if the user wants to save their selected cloud. Future invocations of the cli will use what is stored in `~/.pixie`.
Test Plan: Tested the following scenarios
```
$ ssh host-with-pixie-cli "/bin/bash -c …
```
> Update px cli to make `--cloud_addr` a required argument

- src/ui/src/components/auth/auth-box.tsx
- src/ui/src/configurables/base/signup.ts
- src/ui/src/configurables/base/tos-privacy.tsx
- src/ui/src/pages/auth/signup.tsx
Summary: Move all terms and privacy links to tos-privacy configurables module
Test Plan: Verified that the links on `/auth/signup` are correct with ui local dev workflow
> Move all terms and privacy links to tos-privacy configurables module

- src/carnot/exec/otel_export_sink_node.cc
- src/carnot/planner/objects/otel.cc
Summary: Addresses a couple of small-ish bugs
- `ConsumeSpans` is mistakenly clearing the `metrics_response_` (which is used in `ConsumeMetrics`) instead of the `trace_response_`.
- There is a duplicate return statement in `OTelModule::Init`.
Test Plan: CI, skaffold-ed standalone pem and ran OTel export scripts
> Clear trace response instead of metric response in `OTelExportSinkNode::ConsumeSpans`

- bazel/repository_locations.bzl
- src/carnot/exec/otel_export_sink_node.cc
- src/carnot/exec/otel_export_sink_node_test.cc
Summary: Upgrade open telemetry protobufs from v0.10.0 to v1.3.2
This is a continuation of #1849. Since there was a new minor patch release since that PR was created, I decided to upgrade this to the latest version. This version of the protobufs adds support in the OTLP protocol for histograms.
Relevant Issues: #1968
> Upgrade open telemetry protobufs from v0.10.0 to v1.3.2

- src/carnot/exec/otel_export_sink_node_test.cc
Summary: Add test to verify that ConsumeMetrics and ConsumeTraces clear response members
This adds test coverage for the bug fix in #1910. This is a follow up to the conversation [here](https://github.com/pixie-io/pixie/pull/1910#discussion_r1607339561)
Test Plan: Verified that unit test fails if #1910 is reverted
```
$ git show HEAD
commit 4ab4a9ce58bd394e4cd8287b44767e870fedd127 (HEAD -> ddelnano/add-tests-for-otel-sink-bug, ddelnano/ddelnano/add-tests-for-otel-sink-bug)
Author: Dom Del Nano <ddelnano@gmail.com>
Date:   Fri Jul 26 12:17:00 2024 +0000
Revert "Clear trace response instead of metric response in `OTelExportSinkNode::ConsumeSpans` (#1910)"
This reverts commit 970a54a7b9deb9469c406d73069c1e310a53ea96.
$ bazel test …
```
> Add test to verify that ConsumeMetrics and ConsumeTraces clear response members

- src/stirling/source_connectors/socket_tracer/uprobe_manager.cc
- src/stirling/source_connectors/socket_tracer/uprobe_manager.h
- src/stirling/utils/detect_application.cc
- src/stirling/utils/detect_application.h
- src/stirling/utils/detect_application_test.cc
Summary: Add `--stirling_uprobe_opt_out` cli flag to allow opting binaries from uprobe attachment
See https://github.com/pixie-io/pixie/issues/1970 for the motivation of this change.
Relevant Issues: https://github.com/pixie-io/pixie/issues/1970
Test Plan: Verified the following scenarios
```
[ .. ]
I20240723 17:40:54.208112 739524 uprobe_manager.cc:584] binary filename '/proc/738767/root/usr/sbin/nginx' contained in uprobe opt out list, skipping.
I20240723 17:40:54.209451 739524 uprobe_manager.cc:584] binary filename '/proc/738731/root/usr/sbin/nginx' contained in uprobe opt out list, skipping.
```
```
[ .. ]
I20240723 17:51:14.265595 742187 uprobe_manager.cc:584] binary filename '/proc/741971/root/app/bssl.runfiles/boringssl/bssl' contained in uprobe opt …
```
> Add `--stirling_uprobe_opt_out` cli flag to allow opting binaries from uprobe attachment

- src/stirling/binaries/BUILD.bazel
- src/stirling/binaries/go_binary_parse_profiling.cc
- src/stirling/obj_tools/elf_reader.cc
- src/stirling/obj_tools/elf_reader.h
- src/stirling/obj_tools/elf_reader_test.cc
- src/stirling/obj_tools/go_syms.cc
- src/stirling/source_connectors/socket_tracer/uprobe_symaddrs.cc
- src/stirling/source_connectors/socket_tracer/uprobe_symaddrs.h
Summary: Address PEM crash caused by parsing certain older Go application binaries
This PR fixes a crash caused by certain older Go application binaries. In addition, this change includes the `//src/stirling/binaries:go_binary_parse_profiling` cli tool. This tool was helpful for debugging the previous 32 bit issue and aided in debugging this problem (see Background section for more details). This change is best reviewed commit by commit.
**Background**
Our Golang binary parsing was revamped in https://github.com/pixie-io/pixie/pull/1605 to support Go 1.20.4 applications and later (https://github.com/pixie-io/pixie/issues/1318) in addition to fixing a PEM crash caused by 32 bit go binaries (https://github.com/pixie-io/pixie/issues/1300). While this solved the aforementioned issues, it …
> Address PEM crash caused by parsing certain older Go application binaries

- src/pixie_cli/pkg/cmd/root.go
Summary: Restore cli default cloud and allow opting into interactive selection
We've received feedback from users that is confusing to no longer have a default cloud for the pixie cli. This change restores the previous behavior and picks the alphabetically first option as the default (per [CNCF requirements](https://github.com/cncf/foundation/blob/42bc2197cce2f58b31eae5f5067f0fd04ab73482/website-guidelines.md)). Users can pick from the available clouds through the new `--interactive_cloud_select` flag.
Test Plan: Verified the following scenarios
```
$ ./px --interactive_cloud_select get viziers
Pixie CLI
✔ withpixie.ai:443
Failed to authenticate. Please retry `px auth login`.
```
> Restore cli default cloud and allow opting into interactive selection

- bazel/cc_toolchains/clang/toolchain_files.BUILD
- src/stirling/obj_tools/BUILD.bazel
- src/stirling/obj_tools/elf_reader_test.cc
- src/stirling/obj_tools/testdata/cc/BUILD.bazel
- src/stirling/obj_tools/testdata/cc/test_exe_fixture.h
- src/stirling/obj_tools/testdata/go/BUILD.bazel
Summary: Update `ElfReaderTest`'s nm usage to be hermetic
This was feedback from #1976. See [this comment](https://github.com/pixie-io/pixie/pull/1976#discussion_r1707595841) for the previous discussion.
Test Plan: Elf reader tests pass with updates
> Update `ElfReaderTest`'s nm usage to be hermetic

- bazel/test_runners/qemu_with_kernel/runner.bzl
Summary: Update reference to old kernel label since most recent update
The 6.1.8 kernel was updated to the latest patch version in #1995.
Test Plan: Build without specifying `--//bazel/test_runners/qemu_with_kernel:kernel_version` succeeds
> Update reference to old kernel label since most recent update

- bazel/test_runners/qemu_with_kernel/runner.bzl
- ci/github/matrix.sh
Summary: Update GitHub matrix to use correct 6.1.x kernel
Builds after #1995 would fail since GitHub would attempt to run the 6.1.8 kernel build, which bazel no longer understands. This also updates the qemu test runner kernel that was incorrectly updated in #1999. I thought I had exercised that default value with my testing, but it didn't trigger that default value.
Test Plan: GitHub build on #2002 which pulls in the matrix change is no longer failing
> Update GitHub matrix to use correct 6.1.x kernel

- .github/workflows/cli_release.yaml
- ci/cli_upload_signed.sh
- ci/gon.hcl
Summary: Use maintained gon fork to address Apple signing deprecation
This is a continuation of #1994. Rather than using the macos tools directly, we can continue using gon by switching to the maintained fork ([github.com/Bearer/gon](https://github.com/Bearer/gon))
Relevant Issues: Closes https://github.com/pixie-io/pixie/issues/1993
Test Plan: cli-release GitHub workflow [succeeds](https://github.com/pixie-io/pixie/actions/runs/10724342153/job/29740236170) when built from this branch
Changelog Message: Fix macos signing for px cli releases
> Use maintained gon fork to address Apple signing deprecation

- ci/cli_build_release.sh
Summary: Fix production cli release build by using seccomp profile recommended by podman maintainers
The cli pre-release builds do not trigger our RPM and deb packaging. This packaging step is accomplished by running podman containers and failed during our most recent production cli release (error below):
```
+ podman run -i --rm -v /tmp/tmp.xkTyDurlVW:/src/ -v /__w/pixie/pixie:/image docker.io/cdrx/fpm-fedora:24 fpm -f -p /image/pixie-px-0.8.3.x86_64.rpm -s dir -t rpm -n pixie-px -v 0.8.3 --prefix /usr/local/bin px
time="2024-09-05T22:47:26Z" level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers"
cannot clone: Operation not permitted
Error: cannot re-exec process
```
This is an attempt to remediate the issue by following what …
> Fix production cli release build by using seccomp profile recommended by podman maintainers

- .github/workflows/cli_release.yaml
- ci/cli_build_release.sh
Summary: Another attempt to remediate user namespace issues with ubuntu 24.04 runners
This reverts the failed previous attempt and re-enables user namespaces on ubuntu 24.04. This is a well known behavior change between Ubuntu 22.04 and 24.04 (https://github.com/actions/runner-images/issues/10443#issuecomment-2296608244). Since podman is running rootless, I think it's possible that the user namespace creation (clone syscall) is failing.
Relevant Issues: #1993
Test Plan: Run another production release build after merging this
- Verified that this sysctl cli invocation is similar to our [existing example](https://github.com/pixie-io/pixie/blob/aa1f72a69f0a072d97accd721081f89cb8108fd1/.github/workflows/build_and_test.yaml#L87)
> Another attempt to remediate user namespace issues with ubuntu24 runners

- .github/workflows/cli_release.yaml
- ci/cli_build_release.sh
Summary: Use privileged container for running cli build release steps
This reverts my second attempt at fixing the issue with our recent cli builds and tries to address the issue by running the GitHub action's container privileged. This is to address the following error seen in recent cli release builds:
```
+ podman run -i --rm -v /tmp/tmp.xkTyDurlVW:/src/ -v /__w/pixie/pixie:/image docker.io/cdrx/fpm-fedora:24 fpm -f -p /image/pixie-px-0.8.3.x86_64.rpm -s dir -t rpm -n pixie-px -v 0.8.3 --prefix /usr/local/bin px
time="2024-09-05T22:47:26Z" level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers"
cannot clone: Operation not permitted
Error: cannot re-exec process
```
Relevant Issues: #1993
Test Plan: …
> Use privileged container for running cli build release steps

- ci/cli_build_release.sh
Summary: Use fpm binary from within dev_image_extras container for cli releases
With #2012 merged, the `dev_image_with_extras` container image now contains `fpm`. This change removes the use of podman to avoid the permission issues seen in recent cli builds. This should allow the production cli release build to succeed.
Relevant Issues: Closes #1993
Test Plan: Verified that `fpm` exists in most recent image and packaging building commands work (see testing on #2012). Running a production cli release build is needed after this is merged to complete the testing.
```
$ ./scripts/run_docker.sh
sha256:c14b06e5753d4d9c6b2ff8671843043113cdcfa3f3cb36a492a665d71dc42fad
grep: /etc/bazelrc: No such file or directory
Run Parameters:
Build Buddy:             Disabled …
```
> Use fpm binary from within dev_image_extras container for cli releases

- ci/cli_build_release.sh
Summary: Fix path to cli artifacts and output file now that container volume mounts are removed
In #2015, I forgot to account for [the](https://github.com/pixie-io/pixie/commit/4528883d85f3f372f9b298346d74b36aba87febd#diff-ff4ee1801a9dce2de46b26ff5fd877e777db222b39dcc48a086ba5fb6f10a887L57) volume [mounts](https://github.com/pixie-io/pixie/commit/4528883d85f3f372f9b298346d74b36aba87febd#diff-ff4ee1801a9dce2de46b26ff5fd877e777db222b39dcc48a086ba5fb6f10a887L58) used to place the `px` build artifacts in the container's working directory. This restores the filepath access that the containerized version had.
Relevant Issues: #1993
Test Plan: Reviewed the previous podman command more closely. Still needs to be validated with a successful production cli release.
> Fix path to cli artifacts and output file now that container volume mounts are removed

- src/stirling/source_connectors/tcp_stats/bcc_bpf/tcp_stats.c
- src/stirling/source_connectors/tcp_stats/tcp_stats_bpf_test.cc
Summary: Use correct byte ordering function for kernel struct member (skc_num)
This change doesn't result in a functional difference since `ntohs` and `htons` are inverses of each other on little endian machines (and noops for big endian machines). This field's byte order caused me confusion in #1989, so I wanted to make this struct access consistent.
Test Plan: Testing during #1989 (details [here](https://github.com/pixie-io/pixie/pull/1989#discussion_r1743081397))
> Use correct byte ordering function for kernel struct member (skc_num)

- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
Summary: Allow configuring all ConnTrackers' debug trace level at runtime
When debugging tracing issues with servers that handle requests pre-fork, it's not practical to use `--stirling_conn_trace_pid` (each request is served by a new PID). This change allows enabling debug tracing for all conn trackers to facilitate easier debugging.
Test Plan: Skaffolded this change and verified that the following `stirling_ctrl` command enables `CONN_TRACE` globally.
```
$ ./stirling_ctrl ${pid_of_pem} 1 2
```
Changelog Message: Provide mechanism for debugging a PEM's connection tracking more easily at runtime
> Allow configuring all ConnTrackers' debug trace level at runtime

- k8s/cloud/base/proxy_deployment.yaml
- k8s/cloud/base/proxy_nginx_config.yaml
- src/cloud/proxy/entrypoint.sh
Summary: Fix cloud proxy entrypoint by avoiding modifying a RO directory (Configmap mount directory)
This bug was introduced between 0a44b36b3b058402739426dd2b1c7aa67646869c and c3e0fba3ce266d19dca4207295d58b8737305f46 on #2018 when the individual file mounts were changed to a directory mount. Deploying the cloud proxy from main results in the following error:
```
$ kubectl -n plc logs cloud-proxy-5df85487bf-hrglr
Defaulted container "cloud-proxy-server" out of: cloud-proxy-server, envoy
/scripts/entrypoint.sh: line 20: can't create /usr/local/openresty/nginx/conf/nginx.conf: Read-only file system
```
When I originally tested the final change, I must have only looked at the resulting directory and missed that the pod was crashing. This issue was detected during the 0.1.8 cloud prerelease …
> Fix cloud proxy entrypoint by avoiding modifying a RO directory (Configmap mount directory)

- k8s/cloud/public/kustomization.yaml
Summary: Fix self hosted cloud image pull error for plugin db updater Job
During the 0.1.8 cloud prerelease testing, I noticed that the plugin db updater Job hits an image pull error. This was something that was also reported in the Community slack for the latest release (0.1.7).
Test Plan: The Job is successfully created without any additional manifest edits
Changelog Message: Fixed an issue where the self-hosted cloud install hit an image pull error for the plugin db updater Job
> Fix self hosted cloud image pull error for plugin db updater Job

- src/pixie_cli/px.go
Summary: Use active sentry DSN for px cli
The previous DSN is for a project that no longer exists.
Test Plan: Verified that errors are reported
> Use active sentry DSN for px cli

- src/utils/shared/k8s/delete.go
Summary: Skip k8s resources that have an empty name during resource deletion
Newer versions of k8s break our `px delete` cli logic (see details on #2029). I tracked this down to the the [condition function](https://github.com/kubernetes/kubectl/blob/0315be426ca25e6554f1c9089534b62ce12254d4/pkg/cmd/wait/delete.go#L41-L43) in our ObjectDeleter. I believe the newer versions of k8s added resources that match our visitor, but don't have a resource name. From my testing, it seemed related to the `ValidatingAdmissionPolicies` or `ValidatingAdmissionPolicyBindings` resources.
Relevant Issues: Closes #2029
Test Plan: Deployed a vizier and verified that a subsequent `px delete` deleted the following
* `pl` namespace
* `px-operator` namespace
* Cluster scoped resources: …
> Skip k8s resources that have an empty name during resource deletion

- src/carnot/funcs/builtins/json_ops.cc
- src/carnot/funcs/builtins/json_ops.h
- src/carnot/funcs/builtins/json_ops_test.cc
Summary: Add split UDF func to ease certain string handling
This is functionality that I'm planning to use for my upcoming Kubecon demo/talk. For this use case, I want to access the individual fields of the XFCC header just like the example in the UDF docstring.
Test Plan: New tests pass
Changelog Message: Added `px.split` function to support parsing strings that contain delimiters
> Add split UDF func to ease certain string handling

- bazel/repository_locations.bzl
Summary: Upgrade bcc and libbpf to fix BPF program compilation on 6.10 and later kernels
Bcc provides some "[virtual](https://github.com/iovisor/bcc/blob/cb1ba20f4800f556dc940682ba7016c50bd0a3ac/src/cc/exported_files.cc#L28-L48)" includes to BPF programs. The `compat/linux/virtual_bpf.h` file in particular needs to be kept in sync with libbpf and matches the [header guard](https://github.com/iovisor/bcc/blob/cb1ba20f4800f556dc940682ba7016c50bd0a3ac/src/cc/compat/linux/virtual_bpf.h#L9) of the `include/uapi/linux/bpf.h` file. This means that while our linux headers were updated, our older bcc install was inserting an older copy of the `uapi/linux/bpf.h` file -- one that didn't contain the `bpf_wq` declaration.
```
include/linux/bpf.h:348:10: error: invalid application of 'sizeof' to an …
```
> Upgrade bcc and libbpf to fix BPF program compilation on 6.10 and later kernels

- src/stirling/utils/linux_headers.cc
Summary: Fix bug with resolving relative symlinks during linux header detection
Please see linked issue for details
Relevant Issues: Closes #2037
```
ddelnano@dev-vm:/lib/modules/6.8.0-1015-gcp$ ls -l build
lrwxrwxrwx 1 root root 37 Sep  2 14:42 build -> /usr/src/linux-headers-6.8.0-1015-gcp
$ sudo docker run -v /:/host -v /sys:/sys -v /var/lib/docker:/var/lib/docker --pid=host --cgroupns host --env "PL_HOST_PATH=/host"  bazel/src/stirling/binaries:stirling_wrapper_image
I20241011 21:32:38.893605 395713 linux_headers.cc:257] Looking for host Linux headers at /host/lib/modules/6.8.0-1015-gcp/build.
I20241011 21:32:38.893646 395713 linux_headers.cc:237] Symlink target is an absolute path. Converting that to host path: …
```
> Fix bug with resolving relative symlinks during linux header detection

- src/pxl_scripts/px/differential_flamegraph/differential.pxl
- src/pxl_scripts/px/differential_flamegraph/manifest.yaml
- src/pxl_scripts/px/differential_flamegraph/vis.json
Summary: Add differential flamegraph script
This depends on #2043.
Test Plan: Ran the local UI and verified that the non negated version works as expected
Changelog Message: Add `px/differential_flamegraph` script for comparing flamegraphs profiles between pods. See [this post](https://www.brendangregg.com/blog/2014-11-09/differential-flame-graphs.html) for more background on how to use a differential flamegraph.
> [2/2] Add differential flamegraph script

- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
Summary: Allow newer kernels to opt into explicit loop and chunk limit overrides
Overwriting non default values of the bpf chunk and loop limit is frustrating since it undoes configuration a user explicitly requested. This also will allow for working around #2042, which causes kernels 6.10 and later to fail to start the socket tracer.
In addition to this, I tweaked the kernel upgrade logic slightly. The previous logic would have upgraded a 5.0.x kernel to use the new loop limit when the 1M instruction limit isn't available until 5.1.
Relevant Issues: Helps to work around #2042
Test Plan: Verified the following on a 6.x kernel running `stirling_wrapper`
```
$ sudo ./bazel-bin/src/stirling/binaries/stirling_wrapper
I20241118 05:52:37.358364 3104175 …
```
> Allow newer kernels to opt into explicit loop and chunk limit overrides

- src/stirling/source_connectors/socket_tracer/socket_trace_connector.h
Summary: Add missing protocol contribution marker
I've been working on a new protocol parser and through that I realized there was a missing [PROTOCOL_LIST marker](https://github.com/pixie-io/pixie/blob/03184ccb3014dfea45058af7e077d090534ca975/src/stirling/protocol_contribution_guide_part2.md?plain=1#L60).
Test Plan: Verified there was no marker in the `socket_trace_connector.h` file
> Add missing protocol contribution marker

- src/pixie_cli/pkg/utils/checks.go
Summary: Update cli to detect OpenShift and provide notice to install SCC
This updates `px deploy` to detect OpenShift clusters. In addition, it also prompts a user that they need to install a SecurityContextConstraint before continuing with the deployment. Note: the existing SCC instructions no longer work. I've raised https://github.com/pixie-io/docs.px.dev/pull/291 and verified that a pixie deploy works properly with the updated instructions.
Test Plan: Verified the following with a locally built `px` cli
```
$ oc status
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
In project default on server https://api.test-openshift.testing.getcosmic.ai:6443
svc/openshift - …
```
> Update cli to detect OpenShift and provide notice to install SCC

- src/carnot/planner/logical_planner_test.cc
- src/carnot/udf/registry.cc
- src/carnot/udf/registry_test.cc
- src/vizier/funcs/md_udtfs/md_udtfs_impl.h
Summary: Update `GetAgentStatus` and kernel header UDTF to allow kelvin filtering
In order to leverage the `GetAgentStatus`'s `kernel_headers_installed` column for #2051, it would be convenient for the the UDTF to provide the ability to filter kelvins out -- they don't have access to kernel headers since they don't have the host filesystem volume mounted. This change introduces an `include_kelvin` init argument to the UDTFs with a default of `true` to preserve the existing behavior.
This change also fixes a bug with UDTF's init arg default values, which didn't work prior to this change. Please review commit by commit to see the default arg bug fix followed by the UDTF changes.
Relevant Issues: #2051
Test Plan: New logical planner test no longer fails with the …
> Update `GetAgentStatus` and kernel header UDTF to allow kelvin filtering

- scripts/create_release_tag.sh
Summary: Fix release note generation script
Our releases have blank release notes. This makes it difficult for end users to understand what has changed between releases. This PR updates the existing script that was built to auto generate changelog notes.
Test Plan: Ran the script for each artifact type and verified the output was expected
```
$ ./scripts/create_release_tag.sh cli -n
$ git tag -l --format='%(contents)' release/cli/v0.9.0-pre-ddelnano-fix-release-note-generation.4
- (#2048) Enhanced the `px` cli to detect OpenShift clusters
and prompt to install the appropriate SecurityContextConstraints before
proceeding with a deploy
```
```
$ ./scripts/create_release_tag.sh vizier -n
$ git tag -l --format='%(contents)' …
```
> Fix release note generation script

- k8s/operator/helm/templates/00_olm.yaml
Summary: Ensure OLM finalizer runs to prevent px-operator namespace from being stuck terminating
The helm install process followed by a helm uninstall does not fully clean up all pixie resources in the v0.1.7 operator release. The OLM project [added](https://github.com/operator-framework/operator-lifecycle-manager/commit/f94a5edc69027aefc2f902d6b16cb849b9e18f0a) a csv-cleanup finalizer in [v0.27.0](https://github.com/operator-framework/operator-lifecycle-manager/releases/tag/v0.27.0) that causes the px-operator to get stuck in a terminating state if the `olm` and `px-operator` namespaces are deleted at the same time.
In order to address this, a new Job is introduced within the olm namespace that triggers the deletion of the olm operator namespace (px-operator) from a `pre-delete` hook. …
> Ensure OLM finalizer runs to prevent px-operator namespace from being stuck terminating

- ci/operator_helm_build_release.sh
- k8s/operator/helm/templates/00_olm.yaml
- k8s/operator/helm/templates/csv-deleter.yaml
Summary: Ensure helm release build consistently handles deployOLM toggle
Splitting the csv-deleter Job into its own file in #2063 introduced a bug where the `px-operator` namespace becomes stuck on `helm uninstall` again. This is because helm's `deployOLM` configuration key is patched for the [00_olm.yaml file](https://github.com/pixie-io/pixie/blob/5c5e9dcb259c6548c9ab2c4b31c80d31f5f90124/ci/operator_helm_build_release.sh#L60) during the release build. When I initially tested in https://github.com/pixie-io/pixie/pull/2059, the csv-deleter Job existed in the file and received this special treatment, but after #2063 it no longer did.
In order to address this, this change introduces a Go template comment placeholder that `sed` will look to make it clear that helm operates with a different …
> Ensure helm release build consistently handles deployOLM toggle

- k8s/vizier_deps/base/etcd/etcd_statefulset.yaml
Summary: Ensure etcd stateful set has required capabilities to run on OpenShift
When using the etcd metadata store on an Openshift cluster, the container gets stuck in its start up script and continuously prints the following error.
```
Waiting for pl-etcd-1.pl-etcd.pl to come up
ping: permission denied (are you root?)
Waiting for pl-etcd-1.pl-etcd.pl to come up
ping: permission denied (are you root?)
```
The etcd stateful set requires an additional capability, which was missed when the other services had stricter security context settings added. This change also requires the following `SecurityContextConstraints` changes (https://github.com/pixie-io/docs.px.dev/pull/292)
Test Plan: Deployed the non-operator version of Pixie to an Openshift …
> Ensure etcd stateful set has required capabilities to run on OpenShift

- k8s/vizier_deps/base/etcd/etcd_statefulset.yaml
Summary: Ensure securityContext key is inside StatefulSet's containers block
While testing the [0.14.14-pre-r1.0 Vizier release](https://github.com/pixie-io/pixie/releases/tag/release%2Fvizier%2Fv0.14.14-pre-r1.0), I realized that the fix from #2069 wasn't applied properly. The `securityContext` block was indented too far and results in an invalid manifest.
```
$ kubectl -n pl apply -k k8s/vizier_deps/base/etcd
The request is invalid: patch: Invalid value: "map[metadata:map[annotations:map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"apps/v1\",\"kind\":\"StatefulSet\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"pl-monitoring\",\"etcd_cluster\":\"pl-etcd\"},\"name\":\"pl-etcd\", …
```
> Ensure securityContext key is inside StatefulSet's containers block

- src/pxl_scripts/px/agent_status_diagnostics/agent_status.pxl
- src/pxl_scripts/px/agent_status_diagnostics/manifest.yaml
Summary: Add px/agent_status_diagnostics pxl script
This PR adds a new pxl script that helps identify if linux headers are missing on any PEMs. This can be extended in the future, but the first use cause will be to execute the script during `px deploy` and `px collect-logs`.
Relevant Issues: #2051
Test Plan: Ran the script in the UI and tested it as part of the validation for #2065
Changelog Message: Add `px/agent_status_diagnostics` pxl script for checking common issues
> Add px/agent_status_diagnostics pxl script

- src/pixie_cli/pkg/cmd/collect_logs.go
- src/pixie_cli/pkg/cmd/deploy.go
- src/pixie_cli/pkg/cmd/root.go
- src/pixie_cli/pkg/vizier/BUILD.bazel
- src/pixie_cli/pkg/vizier/logs.go
- src/pixie_cli/pkg/vizier/script.go
- src/utils/script/well_known.go
- src/utils/shared/k8s/logs.go
Summary: Use `px/agent_status_diagnostics` script within px cli to detect missing kernel headers
This PR leverages the script added in #2064 to detect missing kernel headers during cli deploys and `px collect-logs` commands. This solves 2/3 of the use cases I was hoping to identify for #2051 (the last being helm installs).
A recent example of this problem is https://github.com/pixie-io/pixie/issues/1986, where a Go TLS tracing bug went undiagnosed for months (August to December). Amazon Linux 2023's headers are different enough that it breaks Go TLS tracing when pixie's pre-packaged headers are used. The tooling in this PR would have provided a few opportunities for this to be caught.
Relevant Issues: #2051
Test Plan: Verified the following scenarios …
> Use `px/agent_status_diagnostics` script within px cli to detect missing kernel headers

- src/common/system/proc_parser_test.cc
- src/common/system/testdata/proc/123/fd/1
Summary: Fix out-of-bound symlink for gitops tools
I'm working on deploying pixie cloud via gitops.
For security reasons argocd block the deployment if an out of bound symlink is detected in the monorepo.
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = 
repository contains out-of-bounds symlinks. file: src/common/system/testdata/proc/123/fd/1
```
Changing the dummy symlink to a relative path that don't leave the root fixes the issue.
Test Plan: the items below
Additional documentation: see the links below
- https://github.com/argoproj/argo-cd/issues/12593#issuecomment-2575569453
- https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.4-2.5/#out-of-bounds-symlinks-n …
> Fix out-of-bound symlink for gitops tools

- k8s/cloud/public/base/artifact_tracker_versions.yaml
Summary: Update self-hosted cloud's cli, operator and vizier versions
The latest vizier (v0.14.14) and cli (v0.8.5) include support for detect missing kernel headers (#2051). This detection is only enabled when the `px/agent_diagnostic_status` script is present. Since this script will become available in the next release, this change ensures that self hosted users can benefit from this additional diagnostic information as soon as possible.
Relevant Issues: #2051
Test Plan: Verified the version numbers
> Update self-hosted cloud's cli, operator and vizier versions

- .github/workflows/build_and_test.yaml
- .github/workflows/cli_release.yaml
- .github/workflows/cloud_release.yaml
- .github/workflows/operator_release.yaml
- .github/workflows/perf_common.yaml
- .github/workflows/release_update_docs_px_dev.yaml
- .github/workflows/update_script_bundle.yaml
- .github/workflows/vizier_release.yaml
Summary: Migrate the deprecated (v3) download/upload artifact actions to v4
These are slated for deprecation on Jan 30th, but GitHub is failing builds already for using these old versions (output copied below).
> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: 0b7f8abb1508181956e8e162db84b466c27e18ce`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
The breaking changes are described [here](https://github.com/actions/download-artifact/blob/7fba95161a0924506ed1ae69cdbae8371ee00b3f/docs/MIGRATION.md#migration) and upon review I don't believe those cases are relevant to our workflows.
Test Plan: PR build should succeed. As …
> Migrate the deprecated (v3) download/upload artifact actions to v4

- .github/workflows/build_and_test.yaml
Summary: Fix accidentally malformed yaml in GitHub action
This was a minor mistake from #2079.
Test Plan: GitHub actions on PR builds should pass once this is merged (since `pull_request_target` uses the copy off main)
- Also visually inspected the #2079 change again to verify nothing else was missed.
> Fix accidentally malformed yaml in GitHub action

- .github/dependabot.yml
Summary: Opt into dependabot GitHub actions version updates
Earlier today, the download/upload artifacts actions were deprecated and started failing builds (#2079). There are other actions will be deprecated soon, so let's opt into dependabots updates to stay ahead of these notices.
> Your workflow is using a version of actions/cache that is scheduled for deprecation, actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8. Please update your workflow to use either v3 or v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
There are other alternatives (like Renovatebot). I went for this since it's already in …
> Opt into dependabot GitHub actions version updates

- .github/workflows/cli_release.yaml
Summary: Prevent cli release from mutating previously uploaded artifact
The v3 artifacts Action was deprecated and migrated from in #2079. The new API has [breaking changes](https://github.com/actions/upload-artifact/tree/main?tab=readme-ov-file#breaking-changes) including that artifacts are now immutable. During #2079, I missed that the cli release uploads to the same name twice (see grep below) and caused the following [build failure](https://github.com/pixie-io/pixie/actions/runs/12818680277/job/35745089942).
Test Plan: Verified that the `macos-artifacts` artifact name is no longer used multiple times
```
(main) $ git grep -A2 upload-artifact | grep name | uniq -c
1 .github/workflows/build_and_test.yaml-        name: target_files
1 …
```
> Prevent cli release from mutating previously uploaded artifact

- ci/update_files_with_release_versions.sh
Summary: Ensure Artifact tracker versions aren't "v" prefixed
This job ran for the first time and it accidentally added a version string prefixed with a "v". See the commits from https://github.com/pixie-io/pixie/pull/2089. This change fixes that minor error.
Relevant Issues: Closes #1907
Test Plan: Verified the script works with or without a leading "v"
```
$ ./ci/update_files_with_release_versions.sh vizier 0.14.15 '<!--vizier-latest-release'
$ git diff k8s/
diff --git a/k8s/cloud/public/base/artifact_tracker_versions.yaml b/k8s/cloud/public/base/artifact_tracker_versions.yaml
index 6b8497ad1..17995a8bb 100644
--- a/k8s/cloud/public/base/artifact_tracker_versions.yaml
+++ b/k8s/cloud/public/base/artifact_tracker_versions.yaml
@@ -11,7 +11,7 @@ spec:
- name: …
```
> Ensure Artifact tracker versions aren't "v" prefixed

- src/pixie_cli/BUILD.bazel
- src/pixie_cli/pkg/cmd/collect_logs.go
- src/pixie_cli/pkg/cmd/deploy.go
- src/pixie_cli/pkg/cmd/root.go
- src/pixie_cli/pkg/vizier/BUILD.bazel
- src/pixie_cli/pkg/vizier/logs.go
- src/pixie_cli/pkg/vizier/script.go
- src/pixie_cli/px.go
- src/utils/script/well_known.go
- src/utils/shared/k8s/logs.go
Summary: Re-introduce use of `px/agent_status_diagnostics` in px cli to detect missing kernel headers
The original version of this was reverted since it resulted in hung `px deploy` and `px collect-logs` commands on larger clusters. This PR reintroduces the change with the fixes necessary to prevent the previous issue and is best reviewed commit by commit as outlined below:
Commit 1: Cherry-pick of #2065
Commit 2: Fix for goroutine deadlock
Commit 3: Add bundle flag to the `px collect-logs` command
Commit 4: Introduce `PX_LOG_FILE` env var for redirecting `px` log output to a file -- useful for debugging the cli since its terminal spinners complicate logging to stdout
Commits 1, 3 and 4 should be self explanatory. As for Commit 2, the goroutine deadlock occurred from the `streamCh` …
> Re-introduce use of `px/agent_status_diagnostics` in px cli to detect missing kernel headers 

- README.md
- k8s/cloud/public/base/artifact_tracker_versions.yaml
> [bot][releases] Update readme with link to latest cli release.

- src/stirling/source_connectors/socket_tracer/protocols/tls/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/protocols/tls/stitcher.cc
- src/stirling/source_connectors/socket_tracer/protocols/tls/stitcher.h
- src/stirling/source_connectors/socket_tracer/protocols/tls/stitcher_test.cc
Summary: Add TLS protocol stitcher
This is meant to be a relatively bare bones stitcher at first. It will be later extended but I wanted to get the minimal viable version in first. My plan is to revisit this and other parser enhancements as an excuse to "build in public" and video record hacking on Pixie's socket tracer.
> Add TLS protocol stitcher

- src/carnot/funcs/metadata/metadata_ops.cc
- src/carnot/funcs/metadata/metadata_ops.h
- src/carnot/planner/compiler/analyzer/convert_metadata_rule.cc
- src/carnot/planner/compiler/analyzer/convert_metadata_rule_test.cc
- src/carnot/planner/logical_planner_test.cc
- src/carnot/planner/test_utils.h
Summary: Make metadata pod lookups more resilient to short lived processes
This is a continuation of the work started from #1989. Since the `local_addr` column is populated for client side traces, it can be used as a fallback lookup for these traces. This doesn't solve all of the permutations of  missing short lived processes (#1638), but provides more coverage than before.
Relevant Issues: #1638
```
$ ./exectime benchmark -a testing.getcosmic.ai:443 -c <cluster_id> 2>&1 | tee baseline_for_simple_udf_swap_e20880ffd.txt
./exectime benchmark -a testing.getcosmic.ai:443 -c <cluster_id> 2>&1 | tee simple_udf_swap_cd217c05c.txt
```
[simple_udf_swap_cd217c05c.txt](https://github.com/user-attachments/files/18497709/simple_udf_swap_cd2 …
> Make metadata pod lookups more resilient to short lived processes

- bazel/repository_locations.bzl
Summary: Upgrade rules_go to v0.47.1 for go 1.22 support
The work to remove our dependence on go 1.16 will be complete soon (once #2108 is merged). With that done, we can upgrade our go dependencies and go version. This rules_go change is needed to support go 1.22 as there was an assembler fix in [v0.46.0](https://github.com/bazel-contrib/rules_go/releases/tag/v0.46.0) (https://github.com/bazel-contrib/rules_go/pull/3756 specifically).
This was the most recent rules_go version I could upgrade to without dealing with breaking changes. I'll revisit upgrading this to a newer version soon, but my primary goal was to be able to upgrade go and our go deps.
Test Plan: Existing tests and verified my branch to add go 1.22 as a supported version …
> Upgrade rules_go to v0.47.1 for go 1.22 support

- src/stirling/obj_tools/testdata/cc/test_exe.cc
- src/stirling/source_connectors/dynamic_tracer/BUILD.bazel
- src/stirling/source_connectors/dynamic_tracer/dynamic_trace_bpf_test.cc
- src/stirling/source_connectors/dynamic_tracer/dynamic_tracing/BUILD.bazel
- src/stirling/source_connectors/dynamic_tracer/dynamic_tracing/autogen_test.cc
- src/stirling/source_connectors/dynamic_tracer/dynamic_tracing/code_gen_test.cc
- src/stirling/source_connectors/dynamic_tracer/dynamic_tracing/dwarvifier.cc
- src/stirling/source_connectors/dynamic_tracer/dynamic_tracing/dwarvifier_test.cc
- src/stirling/source_connectors/dynamic_tracer/dynamic_tracing/dynamic_tracer_test.cc
- src/stirling/source_connectors/dynamic_tracer/dynamic_tracing/probe_transformer_test.cc
- src/stirling/source_connectors/dynamic_tracer/stirling_dt_bpf_test.cc
Summary: Update dynamic logging to work with Go's 1.17+ calling convention
Despite our earlier messaging that dynamic logging would be deprecated in #2105, I decided that it was easier to handle the new ABI instead of deprecating the Go parts of the dynamic tracer. My rationale for this is that the blocker for achieving feature parity for the new Go ABI, handling `STRUCT_BLOB` variables, is actually a concern for c/c++ tracepoint programs as well. I felt it was important to keep the dynamic tracer rather than deprecate it entirely.
As mentioned above, this change does not have full feature parity with the legacy ABI since `STRUCT_BLOB` variables don't work with register based calling conventions -- these variables copy a blob of memory with the assumption that a packed struct exists in a …
> Update dynamic logging to work with Go's 1.17+ calling convention

- src/shared/protocols/protocols.h
- src/stirling/binaries/stirling_wrapper.cc
- src/stirling/source_connectors/socket_tracer/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/bcc_bpf/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/bcc_bpf/protocol_inference.h
- src/stirling/source_connectors/socket_tracer/bcc_bpf/protocol_inference_test.cc
- src/stirling/source_connectors/socket_tracer/bcc_bpf_intf/common.h
- src/stirling/source_connectors/socket_tracer/conn_tracker.cc
- src/stirling/source_connectors/socket_tracer/data_stream.cc
- src/stirling/source_connectors/socket_tracer/protocols/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/protocols/stitchers.h
- src/stirling/source_connectors/socket_tracer/protocols/tls/parse.cc
- src/stirling/source_connectors/socket_tracer/protocols/tls/parse.h
- src/stirling/source_connectors/socket_tracer/protocols/tls/parse_test.cc
- src/stirling/source_connectors/socket_tracer/protocols/tls/types.h
- src/stirling/source_connectors/socket_tracer/protocols/types.h
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.h
- src/stirling/source_connectors/socket_tracer/socket_trace_tables.h
- src/stirling/source_connectors/socket_tracer/testing/protocol_checkers.cc
- src/stirling/source_connectors/socket_tracer/testing/protocol_checkers.h
- src/stirling/source_connectors/socket_tracer/tls_table.h
- src/stirling/source_connectors/socket_tracer/tls_trace_bpf_test.cc
Summary: Add support for TLS protocol tracing
This is the final change to wire up the tls protocol parser and stitcher into stirling. I've also filed #2095 to track supporting tracing TLS handshakes and the application data.
Test Plan: New tests verify functionality works end to end
Changelog Message: Added support for tracing TLS handshakes. This can be enabled with `--stirling_enable_tls_tracing=1` or through the `PX_STIRLING_ENABLE_TLS_TRACING` environment variable. Until #2095 is addressed, this will disable tracing the plaintext within encrypted connections.
> Add support for TLS protocol tracing

- src/carnot/funcs/builtins/json_ops.h
Summary: Fix error in `px.split` docs
Test Plan: N/A
> Fix error in px.split docs

- scripts/collect_heap_pprofs.sh
- scripts/download_heap_prof_mapped_files.sh
- src/pxl_scripts/px/collect_heap_dumps.pxl
Summary: Add `collect_heap_pprofs.sh` script for easier collection of heap profiles
I've been profiling PEM memory usage often. The existing script was difficult to use when collecting profiles across an entire cluster -- the `download_heap_prof_mapped_files.sh` script hard codes a file path causing each profile to overwrite the previously downloaded one.
This new script orchestrates collecting the heap profiles via the `px` cli and uses a modified version of the `download_heap_prof_mapped_files.sh` to collect the memory mapped files.
Test Plan: Script runs successfully on cluster with 9 nodes and pprof command printed to console works
```
$ ./scripts/collect_heap_pprofs.sh heap_capture <vizier_id> --project=<gcp_project>
$ …
```
> Add `collect_heap_pprofs.sh` script for easier collection of heap profiles

- .github/workflows/build_and_test.yaml
- .github/workflows/cacher.yaml
- .github/workflows/cli_release.yaml
- .github/workflows/cloud_release.yaml
- .github/workflows/codeql.yaml
- .github/workflows/mirror_demos.yaml
- .github/workflows/mirror_deps.yaml
- .github/workflows/mirror_releases.yaml
- .github/workflows/operator_release.yaml
- .github/workflows/perf_common.yaml
- .github/workflows/pr_genfiles.yml
- .github/workflows/pr_linter.yml
- .github/workflows/release_update_docs_px_dev.yaml
- .github/workflows/trivy_images.yaml
- .github/workflows/vizier_release.yaml
Summary: CNCF has hosted ephemeral GitHub runners on Oracle that we want projects to use instead of the GitHub-hosted ones, which now incur a cost to use.
Please direct any questions to me, @jeefy, @krook, and @RobertKielty.
Type of change: /kind chore
Test Plan: Updated gh actions should not fail due to the runners.
> Update github runners to oci gh arc runners

- .github/workflows/codeql.yaml
- go.mod
Summary: There were two issues on main related to codeql. This attempts to address both of them.
1) since go 1.21, the go.mod file is expected to have a version of the form v1.X.Y instead of v1.X codeql warns about this, so this fixes the same.
2) given the recent change in GH action runners, the runners don't seem to have nodejs installed by default, this ensures that nodejs is indeed installed.
Test Plan: Tested e2e.
> Fixup codeql runs

- src/api/python/BUILD.bazel
Summary: TSIA
Relevant Issues: Closes #2140
Test Plan: N/A
> Bump version of pxapi pypi package and update Author email

- src/api/python/wheel_upload.bzl
Summary: TSIA
Figured we should upgrade this while I was working on uploading the new pxapi pypi version.
Relevant Issues: #2140
Type of change: /kind dependency
Test Plan: Ran the upload to test pypi and verified the virtualenv had the new twine version
> Upgrade twine package version used for pypi upload

- bazel/BUILD.bazel
- k8s/devinfra/buildbuddy-executor/README.md
- k8s/devinfra/buildbuddy-executor/values.yaml
Summary: This upgrades the executors and the image used for the executors.
Test Plan: CI run on this PR should pass.
> [ci] Upgrade buildbuddy executors

- k8s/devinfra/buildbuddy-executor/README.md
- k8s/devinfra/buildbuddy-executor/values.yaml
Summary: This adds autoscaling and moves the secret to be externally specified.
Test Plan: Check this CI run and see if the executors scale up.
> [ci] Add autoscaling to executors and make API_KEY external secret

- src/common/fs/fs_wrapper.cc
- src/common/fs/fs_wrapper.h
- src/stirling/obj_tools/elf_reader.cc
- src/stirling/obj_tools/elf_reader.h
- src/stirling/source_connectors/socket_tracer/socket_trace_bpf_tables.cc
Summary: Add PEM command line flag for enforcing a max file size for ElfReader
While memory profiling the PEM, I noticed that large binaries caused the PEM's ElfReader code to make > 100 MiB allocations. This PR adds a cli flag (`--elf_reader_max_file_size`) that allows memory conscious users to prevent the PEM from parsing binaries that would cause these large memory allocations.
Test Plan: Existing tests and skaffold
Changelog Message: Added `--elf_reader_max_file_size` flag to PEM. This flag allows memory conscious users to prevent the PEM from parsing large binaries in order to avoid large memory allocations.
> Add PEM command line flag for enforcing a max file size for ElfReader

- bazel/linux_headers.bzl
Summary: Upgrade linux_headers to artifact that includes 6.6 kernel support
Test Plan: Build should pass
Changelog Message: Fixes an issue where ARM Container OS (COS) clusters running a 6.6.x kernel failed to start the socket tracer
> Upgrade linux_headers to artifact that includes 6.6 kernel support

- src/stirling/source_connectors/socket_tracer/socket_trace_connector.cc
- src/stirling/source_connectors/socket_tracer/socket_trace_connector.h
Summary: Provide configurable memory limit for Conn tracker buffer usage
Some memory conscious users want to prevent PEM's from having unbounded memory use. The socket tracer's conn tracker component allows unbounded memory growth due to storing an uncapped amount of socket data. From profiling the [PEM's heap use](https://github.com/pixie-io/pixie/blob/301198f2af6739f0de8b01e1cbcb3451b3075e28/scripts/collect_heap_pprofs.sh), this memory growth is a significant contributor to the PEM's memory footprint.
By leveraging the existing [table store limit](https://github.com/pixie-io/pixie/blob/301198f2af6739f0de8b01e1cbcb3451b3075e28/src/table_store/table/table.cc#L44) and this new configuration option, these memory conscious users run Pixie with a smaller and more predictable steady state …
> Provide configurable memory limit for Conn tracker buffer usage

- scripts/collect_heap_pprofs.sh
- scripts/download_heap_prof_mapped_files.sh
- src/pxl_scripts/px/collect_heap_dumps.pxl
Summary: Make PEM heap dump scripts compatible with Kelvin
A community member reported their kelvin instances having a significantly large memory footprint. This updates our existing tooling to support kelvin to aid debugging these types of issues.
Test Plan: Ran the heap dump script for a single node cluster (1 PEM, 1 Kelvin) and verified the pprofs rendered in a browser
```
$ ./scripts/collect_heap_pprofs.sh new_test  97838d18-bfa1-4ee4-9ee5-28332354c994 --gcloud-common-args '--project=csmc-dev' --gcloud-ssh-args '--internal-ip'
Wrote heap profile for ASID 3 on host gke-dev-cluster-ddelnano-default-pool-193a440d-1fz9 to new_test/gke-dev-cluster-ddelnano-default-pool-193a440d-1fz9-3.txt
Wrote heap profile for ASID 1 on host …
```
> Make PEM heap dump scripts compatible with Kelvin

- src/shared/services/httpmiddleware/middleware.go
- src/vizier/services/cloud_connector/cloud_connector_server.go
- src/vizier/services/metadata/metadata_server.go
- src/vizier/services/query_broker/query_broker_server.go
Summary: Add pprof endpoints to vizier go services
I'm working with a few community users who are seeing the metadata service consume lots of memory. This change adds the Go pprof endpoints to all vizier Go services to facilitate debugging heap usage.
Type of change: /kind functionality
Test Plan: Skaffolded the change and verified I can use the `/debug/pprof` endpoints without auth
> Add pprof endpoints to vizier go services

- src/stirling/obj_tools/dwarf_reader.cc
- src/stirling/obj_tools/dwarf_reader.h
- src/stirling/obj_tools/dwarf_reader_test.cc
- src/stirling/obj_tools/elf_reader.h
- src/stirling/source_connectors/dynamic_tracer/dynamic_tracing/autogen.cc
- src/stirling/source_connectors/dynamic_tracer/dynamic_tracing/autogen.h
- src/stirling/source_connectors/dynamic_tracer/dynamic_tracing/autogen_test.cc
- src/stirling/source_connectors/dynamic_tracer/dynamic_tracing/dynamic_tracer.cc
- src/stirling/source_connectors/socket_tracer/BUILD.bazel
- src/stirling/source_connectors/socket_tracer/uprobe_symaddrs_test.cc
Summary: Remove `DwarfReader::DetectSourceLanguage` API to address issues with multi language binaries
Our previous `DwarfReader::DetectSourceLanguage` API assumes that a binary contains a single type of `DW_AT_language` attribute -- meaning a Go binary would include only DIEs with `DW_AT_language=DW_LANG_Go`. With our upgrade to Go 1.24, this assumption is no longer true. For example, Go binaries built under ASAN contain a variety of `DW_AT_language` attribute values depending on the DIE compile unit (see Test plan output).
This PR removes this API and updates all callers to determine their use case's language from the relevant compile unit DIE.
Test Plan: Verified that the tests introduced in commit 1 fail w/ ASAN enabled. New APIs fix …
> Remove `DwarfReader::DetectSourceLanguage` API to address issues with multi language binaries

- .github/workflows/trivy_images.yaml
- k8s/cloud/BUILD.bazel
- k8s/cloud_deps/BUILD.bazel
Summary: [trivy] Include vizier and cloud dependency images in image scan
While are aware of CVEs and vulnerabilities with Pixie's code, our dependency images are a blind spot in our security scanning. This change updates the trivy-image GitHub action to include the cloud and vizier dependency images so we can address those vulnerabilities in a timely manner.
This change makes it possible to add the operator dependency images in the future, but for now I've omitted them (dealing with helm is a bit challenging without some additional work).
```
$ bazel build k8s/cloud:cloud_image_list
$ cat bazel-bin/k8s/cloud/cloud_image_list.txt | grep -v '\/cloud'  | xargs -I{} sh -c 'trivy image {}'
$ bazel build …
```
> [trivy] Include vizier and cloud dependency images in image scan

- demos/sock-shop/sock-shop-loadgen.yaml
- k8s/cloud/base/ory_auth/kratos/kratos_deployment.yaml
- k8s/devinfra/buildbuddy-executor/values.yaml
- k8s/operator/helm/templates/csv-deleter.yaml
- k8s/vizier/base/kelvin_deployment.yaml
- k8s/vizier/base/patch_sentry.yaml
- k8s/vizier/base/query_broker_deployment.yaml
- k8s/vizier/bootstrap/cloud_connector_deployment.yaml
- k8s/vizier/etcd_metadata/base/metadata_deployment.yaml
- k8s/vizier/pem/base/pem_daemonset.yaml
- k8s/vizier/persistent_metadata/base/metadata_statefulset.yaml
- k8s/vizier/sanitizer/kelvin_deployment.yaml
- src/e2e_test/jetstream_loadtest/k8s/subscriber_deployment.yaml
- src/e2e_test/protocol_loadtest/http/wrk/k8s/client_deployment.yaml
- src/e2e_test/protocol_loadtest/k8s/client/client_deployment.yaml
Summary: Upgrade curl to latest version
This image was copied from the upstream `curlimages/curl` image:
```
$ crane copy curlimages/curl:8.15.0@sha256:4026b29997dc7c823b51c164b71e2b51e0fd95cce4601f78202c513d97da2922 ghcr.io/pixie-io/pixie-oss-pixie-dev-public-curl:8.15.0
```
Test Plan: Skaffold'ed a cloud and vizier with the new image
```
$ crane manifest ghcr.io/pixie-io/pixie-oss-pixie-dev-public-curl:8.15.0@sha256:4026b29997dc7c823b51c164b71e2b51e0fd95cce4601f78202c513d97da2922 | jq '.manifests[].platform.architecture'
"386"
"arm"
"amd64"
"arm64"
"ppc64le"
```
> Upgrade curl to latest version

- k8s/cloud_deps/base/nats/statefulset.yaml
- k8s/vizier_deps/base/nats/nats_statefulset.yaml
- tools/docker/Makefile
- tools/docker/nats_image/Dockerfile
Summary: Upgrade nats to 2.9.x version with new on-disk storage and patch security vulnerabilities.
This change aims to prepare for a seamless upgrade to a more recent NATS version while addressing some security vulnerabilities. As mentioned in the [NATS release notes](https://nats.io/blog/nats-server-2.9.22-release/), the v2.9.22+ release is aware of the on-disk storage changes introduced in v2.10.x. This makes it possible to downgrade from v2.10.x safely should the next, more ambitious upgrade result in issues.
Test Plan: Skaffold'ed a cloud and vizier and acceptance tested common flows end to end
```
trivy image --scanners vuln ghcr.io/pixie-io/nats:2.9.25-scratch@sha256:869605f46ad21b76be1998e89345640671dbe46714105cf67676ddb0b78d3 …
```
> Upgrade nats to 2.9.x version with new on-disk storage and patch security vulnerabilties

- src/pxl_scripts/px/collect_agent_heaps/collect_agent_heaps.pxl
- src/pxl_scripts/px/collect_agent_heaps/manifest.yaml
- src/pxl_scripts/px/collect_agent_heaps/vis.json
Summary: Fix script bundle creation and improve PEM/Kelvin heap dump collection for large clusters
The `src/pxl_scripts/px/collect_heap_dumps.pxl` was added at the root of a top level script directory. Since this script is largely used adhoc, this went unnoticed until I worked on #2245 and #2246. This moves the script into a proper directory structure and updates it to accommodate very large clusters (see relevant issue for more details).
Relevant Issues: https://github.com/pixie-io/pixie/issues/2245
Test Plan: Verified pxl script runs in the UI and that bundle creation works again
```
(main) $ make bundle-oss.json
px create-bundle --search_path /home/ddelnano/code/pixie-extra/src/pxl_scripts --base bpftrace --base px --base pxbeta --base sotw -o …
```
> Fix script bundle creation and improve PEM/Kelvin heap dump collection for large clusters

- .github/workflows/pr_genfiles.yml
Summary: Add pxl script readme generation to pr_genfiles job
Test Plan: This job should fail since the `src/pxl_scripts/README.md` is stale
> Add pxl script readme generation to pr_genfiles job

- tools/docker/Makefile
- tools/docker/hydra_image/Dockerfile
- tools/docker/kratos_image/Dockerfile
Summary: Add Pixie hydra and kratos images to fix security vulns (upgrade Go and vuln deps)
Ory's OSS projects are released every ~6 months. This means non Enterprise customers are stuck running images built with old go versions and out of date dependencies.
I've split out adding these images with the change to use them since the upgrade itself requires quite a few changes.
Test Plan: Skaffold'ed a cloud running these versions and verified auth functionality works e2e
<details><summary>trivy scan</summary>
```
$ trivy image --scanners vuln ghcr.io/pixie-io/hydra:2.3.0-scratch@sha256:cc4503bc8d0f97624e3d6fa004ebda13ef26407b5cc1284191f2958fa93d312c
2025-07-24T18:40:46.806Z        INFO    Vulnerability scanning is enabled …
```
> Add Pixie hydra and kratos images to fix security vulns (upgrade Go and vuln deps)
